// -------------------------------------------------------------
// 
// File Name: /home/mori/Downloads/tomori_fft/hdlsrc/fft_overlap_tomori/alpha4_1_block8.v
// Created: 2025-04-26 11:44:22
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: alpha4_1_block8
// Source Path: fft_overlap_tomori/FFT64_outMuxed/64pointFFTchan/FFT64/FFT32_1/FFT16/multByExp(-j*Pi//4)1
// Hierarchy Level: 5
// Model version: 3.27
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module alpha4_1_block8
          (clk,
           reset,
           enb_1_64_0,
           x4_re,
           x4_im,
           Out1_re,
           Out1_im);


  input   clk;
  input   reset;
  input   enb_1_64_0;
  input   signed [21:0] x4_re;  // sfix22_En15
  input   signed [21:0] x4_im;  // sfix22_En15
  output  signed [21:0] Out1_re;  // sfix22_En15
  output  signed [21:0] Out1_im;  // sfix22_En15


  wire signed [39:0] Gain_out1_re;  // sfix40_En32
  wire signed [39:0] Gain_out1_im;  // sfix40_En32
  reg signed [39:0] Delay1_out1_re;  // sfix40_En32
  reg signed [39:0] Delay1_out1_im;  // sfix40_En32
  wire signed [21:0] Data_Type_Conversion_out1_re;  // sfix22_En15
  wire signed [21:0] Data_Type_Conversion_out1_im;  // sfix22_En15
  reg signed [21:0] Delay24_out1_re;  // sfix22_En15
  reg signed [21:0] Delay24_out1_im;  // sfix22_En15
  wire signed [31:0] Add_add_cast;  // sfix32_En15
  wire signed [31:0] Add_add_cast_1;  // sfix32_En15
  wire signed [31:0] Add_add_temp;  // sfix32_En15
  wire signed [21:0] Add_out1;  // sfix22_En15
  wire signed [31:0] Add1_sub_cast;  // sfix32_En15
  wire signed [31:0] Add1_sub_cast_1;  // sfix32_En15
  wire signed [31:0] Add1_sub_temp;  // sfix32_En15
  wire signed [21:0] Add1_out1;  // sfix22_En15


  assign Gain_out1_re = 18'sb010110101000001010 * x4_re;
  assign Gain_out1_im = 18'sb010110101000001010 * x4_im;



  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1_re <= 40'sh0000000000;
        Delay1_out1_im <= 40'sh0000000000;
      end
      else begin
        if (enb_1_64_0) begin
          Delay1_out1_re <= Gain_out1_re;
          Delay1_out1_im <= Gain_out1_im;
        end
      end
    end



  assign Data_Type_Conversion_out1_re = Delay1_out1_re[38:17] + $signed({1'b0, Delay1_out1_re[16] & (( ~ Delay1_out1_re[39]) | (|Delay1_out1_re[15:0]))});
  assign Data_Type_Conversion_out1_im = Delay1_out1_im[38:17] + $signed({1'b0, Delay1_out1_im[16] & (( ~ Delay1_out1_im[39]) | (|Delay1_out1_im[15:0]))});



  always @(posedge clk or posedge reset)
    begin : Delay24_process
      if (reset == 1'b1) begin
        Delay24_out1_re <= 22'sb0000000000000000000000;
        Delay24_out1_im <= 22'sb0000000000000000000000;
      end
      else begin
        if (enb_1_64_0) begin
          Delay24_out1_re <= Data_Type_Conversion_out1_re;
          Delay24_out1_im <= Data_Type_Conversion_out1_im;
        end
      end
    end



  assign Add_add_cast = {{10{Delay24_out1_re[21]}}, Delay24_out1_re};
  assign Add_add_cast_1 = {{10{Delay24_out1_im[21]}}, Delay24_out1_im};
  assign Add_add_temp = Add_add_cast + Add_add_cast_1;
  assign Add_out1 = Add_add_temp[21:0];



  assign Out1_re = Add_out1;

  assign Add1_sub_cast = {{10{Delay24_out1_im[21]}}, Delay24_out1_im};
  assign Add1_sub_cast_1 = {{10{Delay24_out1_re[21]}}, Delay24_out1_re};
  assign Add1_sub_temp = Add1_sub_cast - Add1_sub_cast_1;
  assign Add1_out1 = Add1_sub_temp[21:0];



  assign Out1_im = Add1_out1;

endmodule  // alpha4_1_block8

