// -------------------------------------------------------------
// 
// File Name: /home/mori/Downloads/tomori_fft/hdlsrc/fft_overlap_tomori/FFT16_block.v
// Created: 2025-04-26 11:44:22
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FFT16_block
// Source Path: fft_overlap_tomori/FFT64_outMuxed/64pointFFTchan/FFT64/FFT32_1/FFT16
// Hierarchy Level: 4
// Model version: 3.27
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FFT16_block
          (clk,
           reset,
           enb_1_64_0,
           In1_re,
           In1_im,
           In2_re,
           In2_im,
           In3_re,
           In3_im,
           In4_re,
           In4_im,
           In5_re,
           In5_im,
           In6_re,
           In6_im,
           In7_re,
           In7_im,
           In8_re,
           In8_im,
           In9_re,
           In9_im,
           In10_re,
           In10_im,
           In11_re,
           In11_im,
           In12_re,
           In12_im,
           In13_re,
           In13_im,
           In14_re,
           In14_im,
           In15_re,
           In15_im,
           In16_re,
           In16_im,
           x0_re,
           x0_im,
           x1_re,
           x1_im,
           x2_re,
           x2_im,
           x3_re,
           x3_im,
           x4_re,
           x4_im,
           x5_re,
           x5_im,
           x6_re,
           x6_im,
           x7_re,
           x7_im,
           x8_re,
           x8_im,
           x9_re,
           x9_im,
           x10_re,
           x10_im,
           x11_re,
           x11_im,
           x12_re,
           x12_im,
           x13_re,
           x13_im,
           x14_re,
           x14_im,
           x15_re,
           x15_im);


  input   clk;
  input   reset;
  input   enb_1_64_0;
  input   signed [15:0] In1_re;  // sfix16_En15
  input   signed [15:0] In1_im;  // sfix16_En15
  input   signed [15:0] In2_re;  // sfix16_En15
  input   signed [15:0] In2_im;  // sfix16_En15
  input   signed [15:0] In3_re;  // sfix16_En15
  input   signed [15:0] In3_im;  // sfix16_En15
  input   signed [15:0] In4_re;  // sfix16_En15
  input   signed [15:0] In4_im;  // sfix16_En15
  input   signed [15:0] In5_re;  // sfix16_En15
  input   signed [15:0] In5_im;  // sfix16_En15
  input   signed [15:0] In6_re;  // sfix16_En15
  input   signed [15:0] In6_im;  // sfix16_En15
  input   signed [15:0] In7_re;  // sfix16_En15
  input   signed [15:0] In7_im;  // sfix16_En15
  input   signed [15:0] In8_re;  // sfix16_En15
  input   signed [15:0] In8_im;  // sfix16_En15
  input   signed [15:0] In9_re;  // sfix16_En15
  input   signed [15:0] In9_im;  // sfix16_En15
  input   signed [15:0] In10_re;  // sfix16_En15
  input   signed [15:0] In10_im;  // sfix16_En15
  input   signed [15:0] In11_re;  // sfix16_En15
  input   signed [15:0] In11_im;  // sfix16_En15
  input   signed [15:0] In12_re;  // sfix16_En15
  input   signed [15:0] In12_im;  // sfix16_En15
  input   signed [15:0] In13_re;  // sfix16_En15
  input   signed [15:0] In13_im;  // sfix16_En15
  input   signed [15:0] In14_re;  // sfix16_En15
  input   signed [15:0] In14_im;  // sfix16_En15
  input   signed [15:0] In15_re;  // sfix16_En15
  input   signed [15:0] In15_im;  // sfix16_En15
  input   signed [15:0] In16_re;  // sfix16_En15
  input   signed [15:0] In16_im;  // sfix16_En15
  output  signed [21:0] x0_re;  // sfix22_En15
  output  signed [21:0] x0_im;  // sfix22_En15
  output  signed [21:0] x1_re;  // sfix22_En15
  output  signed [21:0] x1_im;  // sfix22_En15
  output  signed [21:0] x2_re;  // sfix22_En15
  output  signed [21:0] x2_im;  // sfix22_En15
  output  signed [21:0] x3_re;  // sfix22_En15
  output  signed [21:0] x3_im;  // sfix22_En15
  output  signed [21:0] x4_re;  // sfix22_En15
  output  signed [21:0] x4_im;  // sfix22_En15
  output  signed [21:0] x5_re;  // sfix22_En15
  output  signed [21:0] x5_im;  // sfix22_En15
  output  signed [21:0] x6_re;  // sfix22_En15
  output  signed [21:0] x6_im;  // sfix22_En15
  output  signed [21:0] x7_re;  // sfix22_En15
  output  signed [21:0] x7_im;  // sfix22_En15
  output  signed [21:0] x8_re;  // sfix22_En15
  output  signed [21:0] x8_im;  // sfix22_En15
  output  signed [21:0] x9_re;  // sfix22_En15
  output  signed [21:0] x9_im;  // sfix22_En15
  output  signed [21:0] x10_re;  // sfix22_En15
  output  signed [21:0] x10_im;  // sfix22_En15
  output  signed [21:0] x11_re;  // sfix22_En15
  output  signed [21:0] x11_im;  // sfix22_En15
  output  signed [21:0] x12_re;  // sfix22_En15
  output  signed [21:0] x12_im;  // sfix22_En15
  output  signed [21:0] x13_re;  // sfix22_En15
  output  signed [21:0] x13_im;  // sfix22_En15
  output  signed [21:0] x14_re;  // sfix22_En15
  output  signed [21:0] x14_im;  // sfix22_En15
  output  signed [21:0] x15_re;  // sfix22_En15
  output  signed [21:0] x15_im;  // sfix22_En15


  wire signed [21:0] FFT8_out1_re;  // sfix22_En15
  wire signed [21:0] FFT8_out1_im;  // sfix22_En15
  wire signed [21:0] FFT8_out2_re;  // sfix22_En15
  wire signed [21:0] FFT8_out2_im;  // sfix22_En15
  wire signed [21:0] FFT8_out3_re;  // sfix22_En15
  wire signed [21:0] FFT8_out3_im;  // sfix22_En15
  wire signed [21:0] FFT8_out4_re;  // sfix22_En15
  wire signed [21:0] FFT8_out4_im;  // sfix22_En15
  wire signed [21:0] FFT8_out5_re;  // sfix22_En15
  wire signed [21:0] FFT8_out5_im;  // sfix22_En15
  wire signed [21:0] FFT8_out6_re;  // sfix22_En15
  wire signed [21:0] FFT8_out6_im;  // sfix22_En15
  wire signed [21:0] FFT8_out7_re;  // sfix22_En15
  wire signed [21:0] FFT8_out7_im;  // sfix22_En15
  wire signed [21:0] FFT8_out8_re;  // sfix22_En15
  wire signed [21:0] FFT8_out8_im;  // sfix22_En15
  reg signed [21:0] Delay22_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay22_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay22_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay22_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay22_out1_re;  // sfix22_En15
  reg signed [21:0] Delay22_out1_im;  // sfix22_En15
  reg signed [21:0] Delay33_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay33_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay33_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay33_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay33_out1_re;  // sfix22_En15
  reg signed [21:0] Delay33_out1_im;  // sfix22_En15
  wire signed [21:0] FFT8_1_out1_re;  // sfix22_En15
  wire signed [21:0] FFT8_1_out1_im;  // sfix22_En15
  wire signed [21:0] FFT8_1_out2_re;  // sfix22_En15
  wire signed [21:0] FFT8_1_out2_im;  // sfix22_En15
  wire signed [21:0] FFT8_1_out3_re;  // sfix22_En15
  wire signed [21:0] FFT8_1_out3_im;  // sfix22_En15
  wire signed [21:0] FFT8_1_out4_re;  // sfix22_En15
  wire signed [21:0] FFT8_1_out4_im;  // sfix22_En15
  wire signed [21:0] FFT8_1_out5_re;  // sfix22_En15
  wire signed [21:0] FFT8_1_out5_im;  // sfix22_En15
  wire signed [21:0] FFT8_1_out6_re;  // sfix22_En15
  wire signed [21:0] FFT8_1_out6_im;  // sfix22_En15
  wire signed [21:0] FFT8_1_out7_re;  // sfix22_En15
  wire signed [21:0] FFT8_1_out7_im;  // sfix22_En15
  wire signed [21:0] FFT8_1_out8_re;  // sfix22_En15
  wire signed [21:0] FFT8_1_out8_im;  // sfix22_En15
  reg signed [21:0] Delay17_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay17_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay17_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay17_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay17_out1_re;  // sfix22_En15
  reg signed [21:0] Delay17_out1_im;  // sfix22_En15
  reg signed [21:0] Delay30_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay30_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay30_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay30_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay30_out1_re;  // sfix22_En15
  reg signed [21:0] Delay30_out1_im;  // sfix22_En15
  wire signed [31:0] Add_add_cast;  // sfix32_En15
  wire signed [31:0] Add_add_cast_1;  // sfix32_En15
  wire signed [31:0] Add_add_temp;  // sfix32_En15
  wire signed [31:0] Add_add_cast_2;  // sfix32_En15
  wire signed [31:0] Add_add_cast_3;  // sfix32_En15
  wire signed [31:0] Add_add_temp_1;  // sfix32_En15
  wire signed [21:0] Add_out1_re;  // sfix22_En15
  wire signed [21:0] Add_out1_im;  // sfix22_En15
  reg signed [21:0] Delay28_reg_re [0:1];  // sfix22_En15 [2]
  reg signed [21:0] Delay28_reg_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay28_reg_next_re [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay28_reg_next_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay28_out1_re;  // sfix22_En15
  wire signed [21:0] Delay28_out1_im;  // sfix22_En15
  reg signed [21:0] Delay18_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay18_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay18_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay18_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay18_out1_re;  // sfix22_En15
  reg signed [21:0] Delay18_out1_im;  // sfix22_En15
  reg signed [21:0] Delay31_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay31_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay31_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay31_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay31_out1_re;  // sfix22_En15
  reg signed [21:0] Delay31_out1_im;  // sfix22_En15
  wire signed [17:0] Constant1_out1_re;  // sfix18_En17
  wire signed [17:0] Constant1_out1_im;  // sfix18_En17
  wire signed [21:0] complexmult_out1_re;  // sfix22_En15
  wire signed [21:0] complexmult_out1_im;  // sfix22_En15
  reg signed [21:0] Delay38_out1_re;  // sfix22_En15
  reg signed [21:0] Delay38_out1_im;  // sfix22_En15
  wire signed [31:0] Add2_add_cast;  // sfix32_En15
  wire signed [31:0] Add2_add_cast_1;  // sfix32_En15
  wire signed [31:0] Add2_add_temp;  // sfix32_En15
  wire signed [31:0] Add2_add_cast_2;  // sfix32_En15
  wire signed [31:0] Add2_add_cast_3;  // sfix32_En15
  wire signed [31:0] Add2_add_temp_1;  // sfix32_En15
  wire signed [21:0] Add2_out1_re;  // sfix22_En15
  wire signed [21:0] Add2_out1_im;  // sfix22_En15
  reg signed [21:0] Delay13_reg_re [0:1];  // sfix22_En15 [2]
  reg signed [21:0] Delay13_reg_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay13_reg_next_re [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay13_reg_next_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay13_out1_re;  // sfix22_En15
  wire signed [21:0] Delay13_out1_im;  // sfix22_En15
  reg signed [21:0] Delay19_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay19_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay19_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay19_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay19_out1_re;  // sfix22_En15
  reg signed [21:0] Delay19_out1_im;  // sfix22_En15
  reg signed [21:0] Delay32_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay32_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay32_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay32_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay32_out1_re;  // sfix22_En15
  reg signed [21:0] Delay32_out1_im;  // sfix22_En15
  wire signed [21:0] multByExp_j_Pi_4_out1_re;  // sfix22_En15
  wire signed [21:0] multByExp_j_Pi_4_out1_im;  // sfix22_En15
  reg signed [21:0] Delay20_out1_re;  // sfix22_En15
  reg signed [21:0] Delay20_out1_im;  // sfix22_En15
  reg signed [21:0] Delay39_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay39_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay39_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay39_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay39_out1_re;  // sfix22_En15
  reg signed [21:0] Delay39_out1_im;  // sfix22_En15
  wire signed [31:0] Add4_add_cast;  // sfix32_En15
  wire signed [31:0] Add4_add_cast_1;  // sfix32_En15
  wire signed [31:0] Add4_add_temp;  // sfix32_En15
  wire signed [31:0] Add4_add_cast_2;  // sfix32_En15
  wire signed [31:0] Add4_add_cast_3;  // sfix32_En15
  wire signed [31:0] Add4_add_temp_1;  // sfix32_En15
  wire signed [21:0] Add4_out1_re;  // sfix22_En15
  wire signed [21:0] Add4_out1_im;  // sfix22_En15
  reg signed [21:0] Delay11_reg_re [0:1];  // sfix22_En15 [2]
  reg signed [21:0] Delay11_reg_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay11_reg_next_re [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay11_reg_next_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay11_out1_re;  // sfix22_En15
  wire signed [21:0] Delay11_out1_im;  // sfix22_En15
  reg signed [21:0] Delay16_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay16_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay16_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay16_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay16_out1_re;  // sfix22_En15
  reg signed [21:0] Delay16_out1_im;  // sfix22_En15
  reg signed [21:0] Delay29_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay29_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay29_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay29_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay29_out1_re;  // sfix22_En15
  reg signed [21:0] Delay29_out1_im;  // sfix22_En15
  wire signed [17:0] Constant2_out1_re;  // sfix18_En17
  wire signed [17:0] Constant2_out1_im;  // sfix18_En17
  wire signed [21:0] complexmult1_out1_re;  // sfix22_En15
  wire signed [21:0] complexmult1_out1_im;  // sfix22_En15
  reg signed [21:0] Delay40_out1_re;  // sfix22_En15
  reg signed [21:0] Delay40_out1_im;  // sfix22_En15
  wire signed [31:0] Add6_add_cast;  // sfix32_En15
  wire signed [31:0] Add6_add_cast_1;  // sfix32_En15
  wire signed [31:0] Add6_add_temp;  // sfix32_En15
  wire signed [31:0] Add6_add_cast_2;  // sfix32_En15
  wire signed [31:0] Add6_add_cast_3;  // sfix32_En15
  wire signed [31:0] Add6_add_temp_1;  // sfix32_En15
  wire signed [21:0] Add6_out1_re;  // sfix22_En15
  wire signed [21:0] Add6_out1_im;  // sfix22_En15
  reg signed [21:0] Delay9_reg_re [0:1];  // sfix22_En15 [2]
  reg signed [21:0] Delay9_reg_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay9_reg_next_re [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay9_reg_next_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay9_out1_re;  // sfix22_En15
  wire signed [21:0] Delay9_out1_im;  // sfix22_En15
  reg signed [21:0] Delay23_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay23_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay23_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay23_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay23_out1_re;  // sfix22_En15
  reg signed [21:0] Delay23_out1_im;  // sfix22_En15
  reg signed [21:0] Delay34_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay34_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay34_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay34_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay34_out1_re;  // sfix22_En15
  reg signed [21:0] Delay34_out1_im;  // sfix22_En15
  wire signed [21:0] multByMinusJ_out1_re;  // sfix22_En15
  wire signed [21:0] multByMinusJ_out1_im;  // sfix22_En15
  reg signed [21:0] Delay21_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay21_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay21_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay21_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay21_out1_re;  // sfix22_En15
  reg signed [21:0] Delay21_out1_im;  // sfix22_En15
  reg signed [21:0] Delay41_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay41_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay41_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay41_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay41_out1_re;  // sfix22_En15
  reg signed [21:0] Delay41_out1_im;  // sfix22_En15
  wire signed [31:0] Add8_add_cast;  // sfix32_En15
  wire signed [31:0] Add8_add_cast_1;  // sfix32_En15
  wire signed [31:0] Add8_add_temp;  // sfix32_En15
  wire signed [31:0] Add8_add_cast_2;  // sfix32_En15
  wire signed [31:0] Add8_add_cast_3;  // sfix32_En15
  wire signed [31:0] Add8_add_temp_1;  // sfix32_En15
  wire signed [21:0] Add8_out1_re;  // sfix22_En15
  wire signed [21:0] Add8_out1_im;  // sfix22_En15
  reg signed [21:0] Delay7_reg_re [0:1];  // sfix22_En15 [2]
  reg signed [21:0] Delay7_reg_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay7_reg_next_re [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay7_reg_next_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay7_out1_re;  // sfix22_En15
  wire signed [21:0] Delay7_out1_im;  // sfix22_En15
  reg signed [21:0] Delay24_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay24_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay24_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay24_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay24_out1_re;  // sfix22_En15
  reg signed [21:0] Delay24_out1_im;  // sfix22_En15
  reg signed [21:0] Delay35_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay35_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay35_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay35_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay35_out1_re;  // sfix22_En15
  reg signed [21:0] Delay35_out1_im;  // sfix22_En15
  wire signed [17:0] Constant3_out1_re;  // sfix18_En17
  wire signed [17:0] Constant3_out1_im;  // sfix18_En17
  wire signed [21:0] complexmult2_out1_re;  // sfix22_En15
  wire signed [21:0] complexmult2_out1_im;  // sfix22_En15
  reg signed [21:0] Delay42_out1_re;  // sfix22_En15
  reg signed [21:0] Delay42_out1_im;  // sfix22_En15
  wire signed [31:0] Add10_add_cast;  // sfix32_En15
  wire signed [31:0] Add10_add_cast_1;  // sfix32_En15
  wire signed [31:0] Add10_add_temp;  // sfix32_En15
  wire signed [31:0] Add10_add_cast_2;  // sfix32_En15
  wire signed [31:0] Add10_add_cast_3;  // sfix32_En15
  wire signed [31:0] Add10_add_temp_1;  // sfix32_En15
  wire signed [21:0] Add10_out1_re;  // sfix22_En15
  wire signed [21:0] Add10_out1_im;  // sfix22_En15
  reg signed [21:0] Delay5_reg_re [0:1];  // sfix22_En15 [2]
  reg signed [21:0] Delay5_reg_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay5_reg_next_re [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay5_reg_next_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay5_out1_re;  // sfix22_En15
  wire signed [21:0] Delay5_out1_im;  // sfix22_En15
  reg signed [21:0] Delay26_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay26_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay26_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay26_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay26_out1_re;  // sfix22_En15
  reg signed [21:0] Delay26_out1_im;  // sfix22_En15
  reg signed [21:0] Delay36_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay36_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay36_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay36_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay36_out1_re;  // sfix22_En15
  reg signed [21:0] Delay36_out1_im;  // sfix22_En15
  wire signed [21:0] multByExp_j_Pi_4_1_out1_re;  // sfix22_En15
  wire signed [21:0] multByExp_j_Pi_4_1_out1_im;  // sfix22_En15
  wire signed [21:0] multByMinusJ3_out1_re;  // sfix22_En15
  wire signed [21:0] multByMinusJ3_out1_im;  // sfix22_En15
  reg signed [21:0] Delay43_out1_re;  // sfix22_En15
  reg signed [21:0] Delay43_out1_im;  // sfix22_En15
  reg signed [21:0] Delay25_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay25_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay25_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay25_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay25_out1_re;  // sfix22_En15
  reg signed [21:0] Delay25_out1_im;  // sfix22_En15
  wire signed [31:0] Add12_add_cast;  // sfix32_En15
  wire signed [31:0] Add12_add_cast_1;  // sfix32_En15
  wire signed [31:0] Add12_add_temp;  // sfix32_En15
  wire signed [31:0] Add12_add_cast_2;  // sfix32_En15
  wire signed [31:0] Add12_add_cast_3;  // sfix32_En15
  wire signed [31:0] Add12_add_temp_1;  // sfix32_En15
  wire signed [21:0] Add12_out1_re;  // sfix22_En15
  wire signed [21:0] Add12_out1_im;  // sfix22_En15
  reg signed [21:0] Delay3_reg_re [0:1];  // sfix22_En15 [2]
  reg signed [21:0] Delay3_reg_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay3_reg_next_re [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay3_reg_next_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay3_out1_re;  // sfix22_En15
  wire signed [21:0] Delay3_out1_im;  // sfix22_En15
  reg signed [21:0] Delay27_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay27_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay27_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay27_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay27_out1_re;  // sfix22_En15
  reg signed [21:0] Delay27_out1_im;  // sfix22_En15
  reg signed [21:0] Delay37_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay37_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay37_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay37_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay37_out1_re;  // sfix22_En15
  reg signed [21:0] Delay37_out1_im;  // sfix22_En15
  wire signed [17:0] Constant4_out1_re;  // sfix18_En17
  wire signed [17:0] Constant4_out1_im;  // sfix18_En17
  wire signed [21:0] complexmult3_out1_re;  // sfix22_En15
  wire signed [21:0] complexmult3_out1_im;  // sfix22_En15
  reg signed [21:0] Delay44_out1_re;  // sfix22_En15
  reg signed [21:0] Delay44_out1_im;  // sfix22_En15
  wire signed [31:0] Add14_add_cast;  // sfix32_En15
  wire signed [31:0] Add14_add_cast_1;  // sfix32_En15
  wire signed [31:0] Add14_add_temp;  // sfix32_En15
  wire signed [31:0] Add14_add_cast_2;  // sfix32_En15
  wire signed [31:0] Add14_add_cast_3;  // sfix32_En15
  wire signed [31:0] Add14_add_temp_1;  // sfix32_En15
  wire signed [21:0] Add14_out1_re;  // sfix22_En15
  wire signed [21:0] Add14_out1_im;  // sfix22_En15
  reg signed [21:0] Delay1_reg_re [0:1];  // sfix22_En15 [2]
  reg signed [21:0] Delay1_reg_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay1_reg_next_re [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay1_reg_next_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay1_out1_re;  // sfix22_En15
  wire signed [21:0] Delay1_out1_im;  // sfix22_En15
  wire signed [31:0] Add1_sub_cast;  // sfix32_En15
  wire signed [31:0] Add1_sub_cast_1;  // sfix32_En15
  wire signed [31:0] Add1_sub_temp;  // sfix32_En15
  wire signed [31:0] Add1_sub_cast_2;  // sfix32_En15
  wire signed [31:0] Add1_sub_cast_3;  // sfix32_En15
  wire signed [31:0] Add1_sub_temp_1;  // sfix32_En15
  wire signed [21:0] Add1_out1_re;  // sfix22_En15
  wire signed [21:0] Add1_out1_im;  // sfix22_En15
  reg signed [21:0] Delay14_reg_re [0:1];  // sfix22_En15 [2]
  reg signed [21:0] Delay14_reg_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay14_reg_next_re [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay14_reg_next_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay14_out1_re;  // sfix22_En15
  wire signed [21:0] Delay14_out1_im;  // sfix22_En15
  wire signed [31:0] Add3_sub_cast;  // sfix32_En15
  wire signed [31:0] Add3_sub_cast_1;  // sfix32_En15
  wire signed [31:0] Add3_sub_temp;  // sfix32_En15
  wire signed [31:0] Add3_sub_cast_2;  // sfix32_En15
  wire signed [31:0] Add3_sub_cast_3;  // sfix32_En15
  wire signed [31:0] Add3_sub_temp_1;  // sfix32_En15
  wire signed [21:0] Add3_out1_re;  // sfix22_En15
  wire signed [21:0] Add3_out1_im;  // sfix22_En15
  reg signed [21:0] Delay12_reg_re [0:1];  // sfix22_En15 [2]
  reg signed [21:0] Delay12_reg_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay12_reg_next_re [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay12_reg_next_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay12_out1_re;  // sfix22_En15
  wire signed [21:0] Delay12_out1_im;  // sfix22_En15
  wire signed [31:0] Add5_sub_cast;  // sfix32_En15
  wire signed [31:0] Add5_sub_cast_1;  // sfix32_En15
  wire signed [31:0] Add5_sub_temp;  // sfix32_En15
  wire signed [31:0] Add5_sub_cast_2;  // sfix32_En15
  wire signed [31:0] Add5_sub_cast_3;  // sfix32_En15
  wire signed [31:0] Add5_sub_temp_1;  // sfix32_En15
  wire signed [21:0] Add5_out1_re;  // sfix22_En15
  wire signed [21:0] Add5_out1_im;  // sfix22_En15
  reg signed [21:0] Delay10_reg_re [0:1];  // sfix22_En15 [2]
  reg signed [21:0] Delay10_reg_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay10_reg_next_re [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay10_reg_next_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay10_out1_re;  // sfix22_En15
  wire signed [21:0] Delay10_out1_im;  // sfix22_En15
  wire signed [31:0] Add7_sub_cast;  // sfix32_En15
  wire signed [31:0] Add7_sub_cast_1;  // sfix32_En15
  wire signed [31:0] Add7_sub_temp;  // sfix32_En15
  wire signed [31:0] Add7_sub_cast_2;  // sfix32_En15
  wire signed [31:0] Add7_sub_cast_3;  // sfix32_En15
  wire signed [31:0] Add7_sub_temp_1;  // sfix32_En15
  wire signed [21:0] Add7_out1_re;  // sfix22_En15
  wire signed [21:0] Add7_out1_im;  // sfix22_En15
  reg signed [21:0] Delay8_reg_re [0:1];  // sfix22_En15 [2]
  reg signed [21:0] Delay8_reg_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay8_reg_next_re [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay8_reg_next_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay8_out1_re;  // sfix22_En15
  wire signed [21:0] Delay8_out1_im;  // sfix22_En15
  wire signed [31:0] Add9_sub_cast;  // sfix32_En15
  wire signed [31:0] Add9_sub_cast_1;  // sfix32_En15
  wire signed [31:0] Add9_sub_temp;  // sfix32_En15
  wire signed [31:0] Add9_sub_cast_2;  // sfix32_En15
  wire signed [31:0] Add9_sub_cast_3;  // sfix32_En15
  wire signed [31:0] Add9_sub_temp_1;  // sfix32_En15
  wire signed [21:0] Add9_out1_re;  // sfix22_En15
  wire signed [21:0] Add9_out1_im;  // sfix22_En15
  reg signed [21:0] Delay6_reg_re [0:1];  // sfix22_En15 [2]
  reg signed [21:0] Delay6_reg_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay6_reg_next_re [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay6_reg_next_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay6_out1_re;  // sfix22_En15
  wire signed [21:0] Delay6_out1_im;  // sfix22_En15
  wire signed [31:0] Add11_sub_cast;  // sfix32_En15
  wire signed [31:0] Add11_sub_cast_1;  // sfix32_En15
  wire signed [31:0] Add11_sub_temp;  // sfix32_En15
  wire signed [31:0] Add11_sub_cast_2;  // sfix32_En15
  wire signed [31:0] Add11_sub_cast_3;  // sfix32_En15
  wire signed [31:0] Add11_sub_temp_1;  // sfix32_En15
  wire signed [21:0] Add11_out1_re;  // sfix22_En15
  wire signed [21:0] Add11_out1_im;  // sfix22_En15
  reg signed [21:0] Delay4_reg_re [0:1];  // sfix22_En15 [2]
  reg signed [21:0] Delay4_reg_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay4_reg_next_re [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay4_reg_next_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay4_out1_re;  // sfix22_En15
  wire signed [21:0] Delay4_out1_im;  // sfix22_En15
  wire signed [31:0] Add13_sub_cast;  // sfix32_En15
  wire signed [31:0] Add13_sub_cast_1;  // sfix32_En15
  wire signed [31:0] Add13_sub_temp;  // sfix32_En15
  wire signed [31:0] Add13_sub_cast_2;  // sfix32_En15
  wire signed [31:0] Add13_sub_cast_3;  // sfix32_En15
  wire signed [31:0] Add13_sub_temp_1;  // sfix32_En15
  wire signed [21:0] Add13_out1_re;  // sfix22_En15
  wire signed [21:0] Add13_out1_im;  // sfix22_En15
  reg signed [21:0] Delay2_reg_re [0:1];  // sfix22_En15 [2]
  reg signed [21:0] Delay2_reg_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay2_reg_next_re [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay2_reg_next_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay2_out1_re;  // sfix22_En15
  wire signed [21:0] Delay2_out1_im;  // sfix22_En15
  wire signed [31:0] Add15_sub_cast;  // sfix32_En15
  wire signed [31:0] Add15_sub_cast_1;  // sfix32_En15
  wire signed [31:0] Add15_sub_temp;  // sfix32_En15
  wire signed [31:0] Add15_sub_cast_2;  // sfix32_En15
  wire signed [31:0] Add15_sub_cast_3;  // sfix32_En15
  wire signed [31:0] Add15_sub_temp_1;  // sfix32_En15
  wire signed [21:0] Add15_out1_re;  // sfix22_En15
  wire signed [21:0] Add15_out1_im;  // sfix22_En15
  reg signed [21:0] Delay15_reg_re [0:1];  // sfix22_En15 [2]
  reg signed [21:0] Delay15_reg_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay15_reg_next_re [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay15_reg_next_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay15_out1_re;  // sfix22_En15
  wire signed [21:0] Delay15_out1_im;  // sfix22_En15
  reg signed [31:0] Delay22_t_0_0;  // int32
  reg signed [31:0] Delay22_t_0_1;  // int32
  reg signed [31:0] Delay22_t_1;  // int32
  reg signed [31:0] Delay33_t_0_0;  // int32
  reg signed [31:0] Delay33_t_0_1;  // int32
  reg signed [31:0] Delay33_t_1;  // int32
  reg signed [31:0] Delay17_t_0_0;  // int32
  reg signed [31:0] Delay17_t_0_1;  // int32
  reg signed [31:0] Delay17_t_1;  // int32
  reg signed [31:0] Delay30_t_0_0;  // int32
  reg signed [31:0] Delay30_t_0_1;  // int32
  reg signed [31:0] Delay30_t_1;  // int32
  reg signed [31:0] Delay28_t_0_0;  // int32
  reg signed [31:0] Delay28_t_1;  // int32
  reg signed [31:0] Delay18_t_0_0;  // int32
  reg signed [31:0] Delay18_t_0_1;  // int32
  reg signed [31:0] Delay18_t_1;  // int32
  reg signed [31:0] Delay31_t_0_0;  // int32
  reg signed [31:0] Delay31_t_0_1;  // int32
  reg signed [31:0] Delay31_t_1;  // int32
  reg signed [31:0] Delay13_t_0_0;  // int32
  reg signed [31:0] Delay13_t_1;  // int32
  reg signed [31:0] Delay19_t_0_0;  // int32
  reg signed [31:0] Delay19_t_0_1;  // int32
  reg signed [31:0] Delay19_t_1;  // int32
  reg signed [31:0] Delay32_t_0_0;  // int32
  reg signed [31:0] Delay32_t_0_1;  // int32
  reg signed [31:0] Delay32_t_1;  // int32
  reg signed [31:0] Delay39_t_0_0;  // int32
  reg signed [31:0] Delay39_t_0_1;  // int32
  reg signed [31:0] Delay39_t_1;  // int32
  reg signed [31:0] Delay11_t_0_0;  // int32
  reg signed [31:0] Delay11_t_1;  // int32
  reg signed [31:0] Delay16_t_0_0;  // int32
  reg signed [31:0] Delay16_t_0_1;  // int32
  reg signed [31:0] Delay16_t_1;  // int32
  reg signed [31:0] Delay29_t_0_0;  // int32
  reg signed [31:0] Delay29_t_0_1;  // int32
  reg signed [31:0] Delay29_t_1;  // int32
  reg signed [31:0] Delay9_t_0_0;  // int32
  reg signed [31:0] Delay9_t_1;  // int32
  reg signed [31:0] Delay23_t_0_0;  // int32
  reg signed [31:0] Delay23_t_0_1;  // int32
  reg signed [31:0] Delay23_t_1;  // int32
  reg signed [31:0] Delay34_t_0_0;  // int32
  reg signed [31:0] Delay34_t_0_1;  // int32
  reg signed [31:0] Delay34_t_1;  // int32
  reg signed [31:0] Delay21_t_0_0;  // int32
  reg signed [31:0] Delay21_t_0_1;  // int32
  reg signed [31:0] Delay21_t_1;  // int32
  reg signed [31:0] Delay41_t_0_0;  // int32
  reg signed [31:0] Delay41_t_0_1;  // int32
  reg signed [31:0] Delay41_t_1;  // int32
  reg signed [31:0] Delay7_t_0_0;  // int32
  reg signed [31:0] Delay7_t_1;  // int32
  reg signed [31:0] Delay24_t_0_0;  // int32
  reg signed [31:0] Delay24_t_0_1;  // int32
  reg signed [31:0] Delay24_t_1;  // int32
  reg signed [31:0] Delay35_t_0_0;  // int32
  reg signed [31:0] Delay35_t_0_1;  // int32
  reg signed [31:0] Delay35_t_1;  // int32
  reg signed [31:0] Delay5_t_0_0;  // int32
  reg signed [31:0] Delay5_t_1;  // int32
  reg signed [31:0] Delay26_t_0_0;  // int32
  reg signed [31:0] Delay26_t_0_1;  // int32
  reg signed [31:0] Delay26_t_1;  // int32
  reg signed [31:0] Delay36_t_0_0;  // int32
  reg signed [31:0] Delay36_t_0_1;  // int32
  reg signed [31:0] Delay36_t_1;  // int32
  reg signed [31:0] Delay25_t_0_0;  // int32
  reg signed [31:0] Delay25_t_0_1;  // int32
  reg signed [31:0] Delay25_t_1;  // int32
  reg signed [31:0] Delay3_t_0_0;  // int32
  reg signed [31:0] Delay3_t_1;  // int32
  reg signed [31:0] Delay27_t_0_0;  // int32
  reg signed [31:0] Delay27_t_0_1;  // int32
  reg signed [31:0] Delay27_t_1;  // int32
  reg signed [31:0] Delay37_t_0_0;  // int32
  reg signed [31:0] Delay37_t_0_1;  // int32
  reg signed [31:0] Delay37_t_1;  // int32
  reg signed [31:0] Delay1_t_0_0;  // int32
  reg signed [31:0] Delay1_t_1;  // int32
  reg signed [31:0] Delay14_t_0_0;  // int32
  reg signed [31:0] Delay14_t_1;  // int32
  reg signed [31:0] Delay12_t_0_0;  // int32
  reg signed [31:0] Delay12_t_1;  // int32
  reg signed [31:0] Delay10_t_0_0;  // int32
  reg signed [31:0] Delay10_t_1;  // int32
  reg signed [31:0] Delay8_t_0_0;  // int32
  reg signed [31:0] Delay8_t_1;  // int32
  reg signed [31:0] Delay6_t_0_0;  // int32
  reg signed [31:0] Delay6_t_1;  // int32
  reg signed [31:0] Delay4_t_0_0;  // int32
  reg signed [31:0] Delay4_t_1;  // int32
  reg signed [31:0] Delay2_t_0_0;  // int32
  reg signed [31:0] Delay2_t_1;  // int32
  reg signed [31:0] Delay15_t_0_0;  // int32
  reg signed [31:0] Delay15_t_1;  // int32

  // s(5)


  FFT8_block1 u_FFT8 (.clk(clk),
                      .reset(reset),
                      .enb_1_64_0(enb_1_64_0),
                      .In1_re(In1_re),  // sfix16_En15
                      .In1_im(In1_im),  // sfix16_En15
                      .In2_re(In3_re),  // sfix16_En15
                      .In2_im(In3_im),  // sfix16_En15
                      .In3_re(In5_re),  // sfix16_En15
                      .In3_im(In5_im),  // sfix16_En15
                      .In4_re(In7_re),  // sfix16_En15
                      .In4_im(In7_im),  // sfix16_En15
                      .In5_re(In9_re),  // sfix16_En15
                      .In5_im(In9_im),  // sfix16_En15
                      .In6_re(In11_re),  // sfix16_En15
                      .In6_im(In11_im),  // sfix16_En15
                      .In7_re(In13_re),  // sfix16_En15
                      .In7_im(In13_im),  // sfix16_En15
                      .In8_re(In15_re),  // sfix16_En15
                      .In8_im(In15_im),  // sfix16_En15
                      .x0_re(FFT8_out1_re),  // sfix22_En15
                      .x0_im(FFT8_out1_im),  // sfix22_En15
                      .x1_re(FFT8_out2_re),  // sfix22_En15
                      .x1_im(FFT8_out2_im),  // sfix22_En15
                      .x2_re(FFT8_out3_re),  // sfix22_En15
                      .x2_im(FFT8_out3_im),  // sfix22_En15
                      .x3_re(FFT8_out4_re),  // sfix22_En15
                      .x3_im(FFT8_out4_im),  // sfix22_En15
                      .x4_re(FFT8_out5_re),  // sfix22_En15
                      .x4_im(FFT8_out5_im),  // sfix22_En15
                      .x5_re(FFT8_out6_re),  // sfix22_En15
                      .x5_im(FFT8_out6_im),  // sfix22_En15
                      .x6_re(FFT8_out7_re),  // sfix22_En15
                      .x6_im(FFT8_out7_im),  // sfix22_En15
                      .x7_re(FFT8_out8_re),  // sfix22_En15
                      .x7_im(FFT8_out8_im)  // sfix22_En15
                      );

  always @(posedge clk or posedge reset)
    begin : Delay22_process
      if (reset == 1'b1) begin
        for(Delay22_t_1 = 32'sd0; Delay22_t_1 <= 32'sd2; Delay22_t_1 = Delay22_t_1 + 32'sd1) begin
          Delay22_reg_re[Delay22_t_1] <= 22'sb0000000000000000000000;
          Delay22_reg_im[Delay22_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay22_t_0_1 = 32'sd0; Delay22_t_0_1 <= 32'sd2; Delay22_t_0_1 = Delay22_t_0_1 + 32'sd1) begin
            Delay22_reg_re[Delay22_t_0_1] <= Delay22_reg_next_re[Delay22_t_0_1];
            Delay22_reg_im[Delay22_t_0_1] <= Delay22_reg_next_im[Delay22_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay22_out1_re = Delay22_reg_re[2];
    Delay22_out1_im = Delay22_reg_im[2];
    Delay22_reg_next_re[0] = FFT8_out1_re;
    Delay22_reg_next_im[0] = FFT8_out1_im;

    for(Delay22_t_0_0 = 32'sd0; Delay22_t_0_0 <= 32'sd1; Delay22_t_0_0 = Delay22_t_0_0 + 32'sd1) begin
      Delay22_reg_next_re[Delay22_t_0_0 + 32'sd1] = Delay22_reg_re[Delay22_t_0_0];
      Delay22_reg_next_im[Delay22_t_0_0 + 32'sd1] = Delay22_reg_im[Delay22_t_0_0];
    end

  end



  always @(posedge clk or posedge reset)
    begin : Delay33_process
      if (reset == 1'b1) begin
        for(Delay33_t_1 = 32'sd0; Delay33_t_1 <= 32'sd2; Delay33_t_1 = Delay33_t_1 + 32'sd1) begin
          Delay33_reg_re[Delay33_t_1] <= 22'sb0000000000000000000000;
          Delay33_reg_im[Delay33_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay33_t_0_1 = 32'sd0; Delay33_t_0_1 <= 32'sd2; Delay33_t_0_1 = Delay33_t_0_1 + 32'sd1) begin
            Delay33_reg_re[Delay33_t_0_1] <= Delay33_reg_next_re[Delay33_t_0_1];
            Delay33_reg_im[Delay33_t_0_1] <= Delay33_reg_next_im[Delay33_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay33_out1_re = Delay33_reg_re[2];
    Delay33_out1_im = Delay33_reg_im[2];
    Delay33_reg_next_re[0] = Delay22_out1_re;
    Delay33_reg_next_im[0] = Delay22_out1_im;

    for(Delay33_t_0_0 = 32'sd0; Delay33_t_0_0 <= 32'sd1; Delay33_t_0_0 = Delay33_t_0_0 + 32'sd1) begin
      Delay33_reg_next_re[Delay33_t_0_0 + 32'sd1] = Delay33_reg_re[Delay33_t_0_0];
      Delay33_reg_next_im[Delay33_t_0_0 + 32'sd1] = Delay33_reg_im[Delay33_t_0_0];
    end

  end



  FFT8_1_block1 u_FFT8_1 (.clk(clk),
                          .reset(reset),
                          .enb_1_64_0(enb_1_64_0),
                          .In1_re(In2_re),  // sfix16_En15
                          .In1_im(In2_im),  // sfix16_En15
                          .In2_re(In4_re),  // sfix16_En15
                          .In2_im(In4_im),  // sfix16_En15
                          .In3_re(In6_re),  // sfix16_En15
                          .In3_im(In6_im),  // sfix16_En15
                          .In4_re(In8_re),  // sfix16_En15
                          .In4_im(In8_im),  // sfix16_En15
                          .In5_re(In10_re),  // sfix16_En15
                          .In5_im(In10_im),  // sfix16_En15
                          .In6_re(In12_re),  // sfix16_En15
                          .In6_im(In12_im),  // sfix16_En15
                          .In7_re(In14_re),  // sfix16_En15
                          .In7_im(In14_im),  // sfix16_En15
                          .In8_re(In16_re),  // sfix16_En15
                          .In8_im(In16_im),  // sfix16_En15
                          .x0_re(FFT8_1_out1_re),  // sfix22_En15
                          .x0_im(FFT8_1_out1_im),  // sfix22_En15
                          .x1_re(FFT8_1_out2_re),  // sfix22_En15
                          .x1_im(FFT8_1_out2_im),  // sfix22_En15
                          .x2_re(FFT8_1_out3_re),  // sfix22_En15
                          .x2_im(FFT8_1_out3_im),  // sfix22_En15
                          .x3_re(FFT8_1_out4_re),  // sfix22_En15
                          .x3_im(FFT8_1_out4_im),  // sfix22_En15
                          .x4_re(FFT8_1_out5_re),  // sfix22_En15
                          .x4_im(FFT8_1_out5_im),  // sfix22_En15
                          .x5_re(FFT8_1_out6_re),  // sfix22_En15
                          .x5_im(FFT8_1_out6_im),  // sfix22_En15
                          .x6_re(FFT8_1_out7_re),  // sfix22_En15
                          .x6_im(FFT8_1_out7_im),  // sfix22_En15
                          .x7_re(FFT8_1_out8_re),  // sfix22_En15
                          .x7_im(FFT8_1_out8_im)  // sfix22_En15
                          );

  always @(posedge clk or posedge reset)
    begin : Delay17_process
      if (reset == 1'b1) begin
        for(Delay17_t_1 = 32'sd0; Delay17_t_1 <= 32'sd2; Delay17_t_1 = Delay17_t_1 + 32'sd1) begin
          Delay17_reg_re[Delay17_t_1] <= 22'sb0000000000000000000000;
          Delay17_reg_im[Delay17_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay17_t_0_1 = 32'sd0; Delay17_t_0_1 <= 32'sd2; Delay17_t_0_1 = Delay17_t_0_1 + 32'sd1) begin
            Delay17_reg_re[Delay17_t_0_1] <= Delay17_reg_next_re[Delay17_t_0_1];
            Delay17_reg_im[Delay17_t_0_1] <= Delay17_reg_next_im[Delay17_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay17_out1_re = Delay17_reg_re[2];
    Delay17_out1_im = Delay17_reg_im[2];
    Delay17_reg_next_re[0] = FFT8_1_out1_re;
    Delay17_reg_next_im[0] = FFT8_1_out1_im;

    for(Delay17_t_0_0 = 32'sd0; Delay17_t_0_0 <= 32'sd1; Delay17_t_0_0 = Delay17_t_0_0 + 32'sd1) begin
      Delay17_reg_next_re[Delay17_t_0_0 + 32'sd1] = Delay17_reg_re[Delay17_t_0_0];
      Delay17_reg_next_im[Delay17_t_0_0 + 32'sd1] = Delay17_reg_im[Delay17_t_0_0];
    end

  end



  always @(posedge clk or posedge reset)
    begin : Delay30_process
      if (reset == 1'b1) begin
        for(Delay30_t_1 = 32'sd0; Delay30_t_1 <= 32'sd2; Delay30_t_1 = Delay30_t_1 + 32'sd1) begin
          Delay30_reg_re[Delay30_t_1] <= 22'sb0000000000000000000000;
          Delay30_reg_im[Delay30_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay30_t_0_1 = 32'sd0; Delay30_t_0_1 <= 32'sd2; Delay30_t_0_1 = Delay30_t_0_1 + 32'sd1) begin
            Delay30_reg_re[Delay30_t_0_1] <= Delay30_reg_next_re[Delay30_t_0_1];
            Delay30_reg_im[Delay30_t_0_1] <= Delay30_reg_next_im[Delay30_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay30_out1_re = Delay30_reg_re[2];
    Delay30_out1_im = Delay30_reg_im[2];
    Delay30_reg_next_re[0] = Delay17_out1_re;
    Delay30_reg_next_im[0] = Delay17_out1_im;

    for(Delay30_t_0_0 = 32'sd0; Delay30_t_0_0 <= 32'sd1; Delay30_t_0_0 = Delay30_t_0_0 + 32'sd1) begin
      Delay30_reg_next_re[Delay30_t_0_0 + 32'sd1] = Delay30_reg_re[Delay30_t_0_0];
      Delay30_reg_next_im[Delay30_t_0_0 + 32'sd1] = Delay30_reg_im[Delay30_t_0_0];
    end

  end



  assign Add_add_cast = {{10{Delay33_out1_re[21]}}, Delay33_out1_re};
  assign Add_add_cast_1 = {{10{Delay30_out1_re[21]}}, Delay30_out1_re};
  assign Add_add_temp = Add_add_cast + Add_add_cast_1;
  assign Add_out1_re = Add_add_temp[21:0];
  assign Add_add_cast_2 = {{10{Delay33_out1_im[21]}}, Delay33_out1_im};
  assign Add_add_cast_3 = {{10{Delay30_out1_im[21]}}, Delay30_out1_im};
  assign Add_add_temp_1 = Add_add_cast_2 + Add_add_cast_3;
  assign Add_out1_im = Add_add_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay28_process
      if (reset == 1'b1) begin
        for(Delay28_t_1 = 32'sd0; Delay28_t_1 <= 32'sd1; Delay28_t_1 = Delay28_t_1 + 32'sd1) begin
          Delay28_reg_re[Delay28_t_1] <= 22'sb0000000000000000000000;
          Delay28_reg_im[Delay28_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay28_t_0_0 = 32'sd0; Delay28_t_0_0 <= 32'sd1; Delay28_t_0_0 = Delay28_t_0_0 + 32'sd1) begin
            Delay28_reg_re[Delay28_t_0_0] <= Delay28_reg_next_re[Delay28_t_0_0];
            Delay28_reg_im[Delay28_t_0_0] <= Delay28_reg_next_im[Delay28_t_0_0];
          end
        end
      end
    end

  assign Delay28_out1_re = Delay28_reg_re[1];
  assign Delay28_out1_im = Delay28_reg_im[1];
  assign Delay28_reg_next_re[0] = Add_out1_re;
  assign Delay28_reg_next_im[0] = Add_out1_im;
  assign Delay28_reg_next_re[1] = Delay28_reg_re[0];
  assign Delay28_reg_next_im[1] = Delay28_reg_im[0];



  assign x0_re = Delay28_out1_re;

  assign x0_im = Delay28_out1_im;

  always @(posedge clk or posedge reset)
    begin : Delay18_process
      if (reset == 1'b1) begin
        for(Delay18_t_1 = 32'sd0; Delay18_t_1 <= 32'sd2; Delay18_t_1 = Delay18_t_1 + 32'sd1) begin
          Delay18_reg_re[Delay18_t_1] <= 22'sb0000000000000000000000;
          Delay18_reg_im[Delay18_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay18_t_0_1 = 32'sd0; Delay18_t_0_1 <= 32'sd2; Delay18_t_0_1 = Delay18_t_0_1 + 32'sd1) begin
            Delay18_reg_re[Delay18_t_0_1] <= Delay18_reg_next_re[Delay18_t_0_1];
            Delay18_reg_im[Delay18_t_0_1] <= Delay18_reg_next_im[Delay18_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay18_out1_re = Delay18_reg_re[2];
    Delay18_out1_im = Delay18_reg_im[2];
    Delay18_reg_next_re[0] = FFT8_out2_re;
    Delay18_reg_next_im[0] = FFT8_out2_im;

    for(Delay18_t_0_0 = 32'sd0; Delay18_t_0_0 <= 32'sd1; Delay18_t_0_0 = Delay18_t_0_0 + 32'sd1) begin
      Delay18_reg_next_re[Delay18_t_0_0 + 32'sd1] = Delay18_reg_re[Delay18_t_0_0];
      Delay18_reg_next_im[Delay18_t_0_0 + 32'sd1] = Delay18_reg_im[Delay18_t_0_0];
    end

  end



  always @(posedge clk or posedge reset)
    begin : Delay31_process
      if (reset == 1'b1) begin
        for(Delay31_t_1 = 32'sd0; Delay31_t_1 <= 32'sd2; Delay31_t_1 = Delay31_t_1 + 32'sd1) begin
          Delay31_reg_re[Delay31_t_1] <= 22'sb0000000000000000000000;
          Delay31_reg_im[Delay31_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay31_t_0_1 = 32'sd0; Delay31_t_0_1 <= 32'sd2; Delay31_t_0_1 = Delay31_t_0_1 + 32'sd1) begin
            Delay31_reg_re[Delay31_t_0_1] <= Delay31_reg_next_re[Delay31_t_0_1];
            Delay31_reg_im[Delay31_t_0_1] <= Delay31_reg_next_im[Delay31_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay31_out1_re = Delay31_reg_re[2];
    Delay31_out1_im = Delay31_reg_im[2];
    Delay31_reg_next_re[0] = Delay18_out1_re;
    Delay31_reg_next_im[0] = Delay18_out1_im;

    for(Delay31_t_0_0 = 32'sd0; Delay31_t_0_0 <= 32'sd1; Delay31_t_0_0 = Delay31_t_0_0 + 32'sd1) begin
      Delay31_reg_next_re[Delay31_t_0_0 + 32'sd1] = Delay31_reg_re[Delay31_t_0_0];
      Delay31_reg_next_im[Delay31_t_0_0 + 32'sd1] = Delay31_reg_im[Delay31_t_0_0];
    end

  end



  assign Constant1_out1_re = 18'sb011101100100000111;
  assign Constant1_out1_im = 18'sb110011110000010001;



  complexmult_block2 u_complexmult (.clk(clk),
                                    .reset(reset),
                                    .enb_1_64_0(enb_1_64_0),
                                    .x1_re(FFT8_1_out2_re),  // sfix22_En15
                                    .x1_im(FFT8_1_out2_im),  // sfix22_En15
                                    .In3_re(Constant1_out1_re),  // sfix18_En17
                                    .In3_im(Constant1_out1_im),  // sfix18_En17
                                    .Out1_re(complexmult_out1_re),  // sfix22_En15
                                    .Out1_im(complexmult_out1_im)  // sfix22_En15
                                    );

  always @(posedge clk or posedge reset)
    begin : Delay38_process
      if (reset == 1'b1) begin
        Delay38_out1_re <= 22'sb0000000000000000000000;
        Delay38_out1_im <= 22'sb0000000000000000000000;
      end
      else begin
        if (enb_1_64_0) begin
          Delay38_out1_re <= complexmult_out1_re;
          Delay38_out1_im <= complexmult_out1_im;
        end
      end
    end



  assign Add2_add_cast = {{10{Delay31_out1_re[21]}}, Delay31_out1_re};
  assign Add2_add_cast_1 = {{10{Delay38_out1_re[21]}}, Delay38_out1_re};
  assign Add2_add_temp = Add2_add_cast + Add2_add_cast_1;
  assign Add2_out1_re = Add2_add_temp[21:0];
  assign Add2_add_cast_2 = {{10{Delay31_out1_im[21]}}, Delay31_out1_im};
  assign Add2_add_cast_3 = {{10{Delay38_out1_im[21]}}, Delay38_out1_im};
  assign Add2_add_temp_1 = Add2_add_cast_2 + Add2_add_cast_3;
  assign Add2_out1_im = Add2_add_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay13_process
      if (reset == 1'b1) begin
        for(Delay13_t_1 = 32'sd0; Delay13_t_1 <= 32'sd1; Delay13_t_1 = Delay13_t_1 + 32'sd1) begin
          Delay13_reg_re[Delay13_t_1] <= 22'sb0000000000000000000000;
          Delay13_reg_im[Delay13_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay13_t_0_0 = 32'sd0; Delay13_t_0_0 <= 32'sd1; Delay13_t_0_0 = Delay13_t_0_0 + 32'sd1) begin
            Delay13_reg_re[Delay13_t_0_0] <= Delay13_reg_next_re[Delay13_t_0_0];
            Delay13_reg_im[Delay13_t_0_0] <= Delay13_reg_next_im[Delay13_t_0_0];
          end
        end
      end
    end

  assign Delay13_out1_re = Delay13_reg_re[1];
  assign Delay13_out1_im = Delay13_reg_im[1];
  assign Delay13_reg_next_re[0] = Add2_out1_re;
  assign Delay13_reg_next_im[0] = Add2_out1_im;
  assign Delay13_reg_next_re[1] = Delay13_reg_re[0];
  assign Delay13_reg_next_im[1] = Delay13_reg_im[0];



  assign x1_re = Delay13_out1_re;

  assign x1_im = Delay13_out1_im;

  always @(posedge clk or posedge reset)
    begin : Delay19_process
      if (reset == 1'b1) begin
        for(Delay19_t_1 = 32'sd0; Delay19_t_1 <= 32'sd2; Delay19_t_1 = Delay19_t_1 + 32'sd1) begin
          Delay19_reg_re[Delay19_t_1] <= 22'sb0000000000000000000000;
          Delay19_reg_im[Delay19_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay19_t_0_1 = 32'sd0; Delay19_t_0_1 <= 32'sd2; Delay19_t_0_1 = Delay19_t_0_1 + 32'sd1) begin
            Delay19_reg_re[Delay19_t_0_1] <= Delay19_reg_next_re[Delay19_t_0_1];
            Delay19_reg_im[Delay19_t_0_1] <= Delay19_reg_next_im[Delay19_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay19_out1_re = Delay19_reg_re[2];
    Delay19_out1_im = Delay19_reg_im[2];
    Delay19_reg_next_re[0] = FFT8_out3_re;
    Delay19_reg_next_im[0] = FFT8_out3_im;

    for(Delay19_t_0_0 = 32'sd0; Delay19_t_0_0 <= 32'sd1; Delay19_t_0_0 = Delay19_t_0_0 + 32'sd1) begin
      Delay19_reg_next_re[Delay19_t_0_0 + 32'sd1] = Delay19_reg_re[Delay19_t_0_0];
      Delay19_reg_next_im[Delay19_t_0_0 + 32'sd1] = Delay19_reg_im[Delay19_t_0_0];
    end

  end



  always @(posedge clk or posedge reset)
    begin : Delay32_process
      if (reset == 1'b1) begin
        for(Delay32_t_1 = 32'sd0; Delay32_t_1 <= 32'sd2; Delay32_t_1 = Delay32_t_1 + 32'sd1) begin
          Delay32_reg_re[Delay32_t_1] <= 22'sb0000000000000000000000;
          Delay32_reg_im[Delay32_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay32_t_0_1 = 32'sd0; Delay32_t_0_1 <= 32'sd2; Delay32_t_0_1 = Delay32_t_0_1 + 32'sd1) begin
            Delay32_reg_re[Delay32_t_0_1] <= Delay32_reg_next_re[Delay32_t_0_1];
            Delay32_reg_im[Delay32_t_0_1] <= Delay32_reg_next_im[Delay32_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay32_out1_re = Delay32_reg_re[2];
    Delay32_out1_im = Delay32_reg_im[2];
    Delay32_reg_next_re[0] = Delay19_out1_re;
    Delay32_reg_next_im[0] = Delay19_out1_im;

    for(Delay32_t_0_0 = 32'sd0; Delay32_t_0_0 <= 32'sd1; Delay32_t_0_0 = Delay32_t_0_0 + 32'sd1) begin
      Delay32_reg_next_re[Delay32_t_0_0 + 32'sd1] = Delay32_reg_re[Delay32_t_0_0];
      Delay32_reg_next_im[Delay32_t_0_0 + 32'sd1] = Delay32_reg_im[Delay32_t_0_0];
    end

  end



  alpha4_block8 u_multByExp_j_Pi_4 (.clk(clk),
                                    .reset(reset),
                                    .enb_1_64_0(enb_1_64_0),
                                    .x4_re(FFT8_1_out3_re),  // sfix22_En15
                                    .x4_im(FFT8_1_out3_im),  // sfix22_En15
                                    .Out1_re(multByExp_j_Pi_4_out1_re),  // sfix22_En15
                                    .Out1_im(multByExp_j_Pi_4_out1_im)  // sfix22_En15
                                    );

  always @(posedge clk or posedge reset)
    begin : Delay20_process
      if (reset == 1'b1) begin
        Delay20_out1_re <= 22'sb0000000000000000000000;
        Delay20_out1_im <= 22'sb0000000000000000000000;
      end
      else begin
        if (enb_1_64_0) begin
          Delay20_out1_re <= multByExp_j_Pi_4_out1_re;
          Delay20_out1_im <= multByExp_j_Pi_4_out1_im;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : Delay39_process
      if (reset == 1'b1) begin
        for(Delay39_t_1 = 32'sd0; Delay39_t_1 <= 32'sd2; Delay39_t_1 = Delay39_t_1 + 32'sd1) begin
          Delay39_reg_re[Delay39_t_1] <= 22'sb0000000000000000000000;
          Delay39_reg_im[Delay39_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay39_t_0_1 = 32'sd0; Delay39_t_0_1 <= 32'sd2; Delay39_t_0_1 = Delay39_t_0_1 + 32'sd1) begin
            Delay39_reg_re[Delay39_t_0_1] <= Delay39_reg_next_re[Delay39_t_0_1];
            Delay39_reg_im[Delay39_t_0_1] <= Delay39_reg_next_im[Delay39_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay39_out1_re = Delay39_reg_re[2];
    Delay39_out1_im = Delay39_reg_im[2];
    Delay39_reg_next_re[0] = Delay20_out1_re;
    Delay39_reg_next_im[0] = Delay20_out1_im;

    for(Delay39_t_0_0 = 32'sd0; Delay39_t_0_0 <= 32'sd1; Delay39_t_0_0 = Delay39_t_0_0 + 32'sd1) begin
      Delay39_reg_next_re[Delay39_t_0_0 + 32'sd1] = Delay39_reg_re[Delay39_t_0_0];
      Delay39_reg_next_im[Delay39_t_0_0 + 32'sd1] = Delay39_reg_im[Delay39_t_0_0];
    end

  end



  assign Add4_add_cast = {{10{Delay32_out1_re[21]}}, Delay32_out1_re};
  assign Add4_add_cast_1 = {{10{Delay39_out1_re[21]}}, Delay39_out1_re};
  assign Add4_add_temp = Add4_add_cast + Add4_add_cast_1;
  assign Add4_out1_re = Add4_add_temp[21:0];
  assign Add4_add_cast_2 = {{10{Delay32_out1_im[21]}}, Delay32_out1_im};
  assign Add4_add_cast_3 = {{10{Delay39_out1_im[21]}}, Delay39_out1_im};
  assign Add4_add_temp_1 = Add4_add_cast_2 + Add4_add_cast_3;
  assign Add4_out1_im = Add4_add_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay11_process
      if (reset == 1'b1) begin
        for(Delay11_t_1 = 32'sd0; Delay11_t_1 <= 32'sd1; Delay11_t_1 = Delay11_t_1 + 32'sd1) begin
          Delay11_reg_re[Delay11_t_1] <= 22'sb0000000000000000000000;
          Delay11_reg_im[Delay11_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay11_t_0_0 = 32'sd0; Delay11_t_0_0 <= 32'sd1; Delay11_t_0_0 = Delay11_t_0_0 + 32'sd1) begin
            Delay11_reg_re[Delay11_t_0_0] <= Delay11_reg_next_re[Delay11_t_0_0];
            Delay11_reg_im[Delay11_t_0_0] <= Delay11_reg_next_im[Delay11_t_0_0];
          end
        end
      end
    end

  assign Delay11_out1_re = Delay11_reg_re[1];
  assign Delay11_out1_im = Delay11_reg_im[1];
  assign Delay11_reg_next_re[0] = Add4_out1_re;
  assign Delay11_reg_next_im[0] = Add4_out1_im;
  assign Delay11_reg_next_re[1] = Delay11_reg_re[0];
  assign Delay11_reg_next_im[1] = Delay11_reg_im[0];



  assign x2_re = Delay11_out1_re;

  assign x2_im = Delay11_out1_im;

  always @(posedge clk or posedge reset)
    begin : Delay16_process
      if (reset == 1'b1) begin
        for(Delay16_t_1 = 32'sd0; Delay16_t_1 <= 32'sd2; Delay16_t_1 = Delay16_t_1 + 32'sd1) begin
          Delay16_reg_re[Delay16_t_1] <= 22'sb0000000000000000000000;
          Delay16_reg_im[Delay16_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay16_t_0_1 = 32'sd0; Delay16_t_0_1 <= 32'sd2; Delay16_t_0_1 = Delay16_t_0_1 + 32'sd1) begin
            Delay16_reg_re[Delay16_t_0_1] <= Delay16_reg_next_re[Delay16_t_0_1];
            Delay16_reg_im[Delay16_t_0_1] <= Delay16_reg_next_im[Delay16_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay16_out1_re = Delay16_reg_re[2];
    Delay16_out1_im = Delay16_reg_im[2];
    Delay16_reg_next_re[0] = FFT8_out4_re;
    Delay16_reg_next_im[0] = FFT8_out4_im;

    for(Delay16_t_0_0 = 32'sd0; Delay16_t_0_0 <= 32'sd1; Delay16_t_0_0 = Delay16_t_0_0 + 32'sd1) begin
      Delay16_reg_next_re[Delay16_t_0_0 + 32'sd1] = Delay16_reg_re[Delay16_t_0_0];
      Delay16_reg_next_im[Delay16_t_0_0 + 32'sd1] = Delay16_reg_im[Delay16_t_0_0];
    end

  end



  always @(posedge clk or posedge reset)
    begin : Delay29_process
      if (reset == 1'b1) begin
        for(Delay29_t_1 = 32'sd0; Delay29_t_1 <= 32'sd2; Delay29_t_1 = Delay29_t_1 + 32'sd1) begin
          Delay29_reg_re[Delay29_t_1] <= 22'sb0000000000000000000000;
          Delay29_reg_im[Delay29_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay29_t_0_1 = 32'sd0; Delay29_t_0_1 <= 32'sd2; Delay29_t_0_1 = Delay29_t_0_1 + 32'sd1) begin
            Delay29_reg_re[Delay29_t_0_1] <= Delay29_reg_next_re[Delay29_t_0_1];
            Delay29_reg_im[Delay29_t_0_1] <= Delay29_reg_next_im[Delay29_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay29_out1_re = Delay29_reg_re[2];
    Delay29_out1_im = Delay29_reg_im[2];
    Delay29_reg_next_re[0] = Delay16_out1_re;
    Delay29_reg_next_im[0] = Delay16_out1_im;

    for(Delay29_t_0_0 = 32'sd0; Delay29_t_0_0 <= 32'sd1; Delay29_t_0_0 = Delay29_t_0_0 + 32'sd1) begin
      Delay29_reg_next_re[Delay29_t_0_0 + 32'sd1] = Delay29_reg_re[Delay29_t_0_0];
      Delay29_reg_next_im[Delay29_t_0_0 + 32'sd1] = Delay29_reg_im[Delay29_t_0_0];
    end

  end



  assign Constant2_out1_re = 18'sb001100001111101111;
  assign Constant2_out1_im = 18'sb100010011011111001;



  complexmult1_block2 u_complexmult1 (.clk(clk),
                                      .reset(reset),
                                      .enb_1_64_0(enb_1_64_0),
                                      .x1_re(FFT8_1_out4_re),  // sfix22_En15
                                      .x1_im(FFT8_1_out4_im),  // sfix22_En15
                                      .In3_re(Constant2_out1_re),  // sfix18_En17
                                      .In3_im(Constant2_out1_im),  // sfix18_En17
                                      .Out1_re(complexmult1_out1_re),  // sfix22_En15
                                      .Out1_im(complexmult1_out1_im)  // sfix22_En15
                                      );

  always @(posedge clk or posedge reset)
    begin : Delay40_process
      if (reset == 1'b1) begin
        Delay40_out1_re <= 22'sb0000000000000000000000;
        Delay40_out1_im <= 22'sb0000000000000000000000;
      end
      else begin
        if (enb_1_64_0) begin
          Delay40_out1_re <= complexmult1_out1_re;
          Delay40_out1_im <= complexmult1_out1_im;
        end
      end
    end



  assign Add6_add_cast = {{10{Delay29_out1_re[21]}}, Delay29_out1_re};
  assign Add6_add_cast_1 = {{10{Delay40_out1_re[21]}}, Delay40_out1_re};
  assign Add6_add_temp = Add6_add_cast + Add6_add_cast_1;
  assign Add6_out1_re = Add6_add_temp[21:0];
  assign Add6_add_cast_2 = {{10{Delay29_out1_im[21]}}, Delay29_out1_im};
  assign Add6_add_cast_3 = {{10{Delay40_out1_im[21]}}, Delay40_out1_im};
  assign Add6_add_temp_1 = Add6_add_cast_2 + Add6_add_cast_3;
  assign Add6_out1_im = Add6_add_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay9_process
      if (reset == 1'b1) begin
        for(Delay9_t_1 = 32'sd0; Delay9_t_1 <= 32'sd1; Delay9_t_1 = Delay9_t_1 + 32'sd1) begin
          Delay9_reg_re[Delay9_t_1] <= 22'sb0000000000000000000000;
          Delay9_reg_im[Delay9_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay9_t_0_0 = 32'sd0; Delay9_t_0_0 <= 32'sd1; Delay9_t_0_0 = Delay9_t_0_0 + 32'sd1) begin
            Delay9_reg_re[Delay9_t_0_0] <= Delay9_reg_next_re[Delay9_t_0_0];
            Delay9_reg_im[Delay9_t_0_0] <= Delay9_reg_next_im[Delay9_t_0_0];
          end
        end
      end
    end

  assign Delay9_out1_re = Delay9_reg_re[1];
  assign Delay9_out1_im = Delay9_reg_im[1];
  assign Delay9_reg_next_re[0] = Add6_out1_re;
  assign Delay9_reg_next_im[0] = Add6_out1_im;
  assign Delay9_reg_next_re[1] = Delay9_reg_re[0];
  assign Delay9_reg_next_im[1] = Delay9_reg_im[0];



  assign x3_re = Delay9_out1_re;

  assign x3_im = Delay9_out1_im;

  always @(posedge clk or posedge reset)
    begin : Delay23_process
      if (reset == 1'b1) begin
        for(Delay23_t_1 = 32'sd0; Delay23_t_1 <= 32'sd2; Delay23_t_1 = Delay23_t_1 + 32'sd1) begin
          Delay23_reg_re[Delay23_t_1] <= 22'sb0000000000000000000000;
          Delay23_reg_im[Delay23_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay23_t_0_1 = 32'sd0; Delay23_t_0_1 <= 32'sd2; Delay23_t_0_1 = Delay23_t_0_1 + 32'sd1) begin
            Delay23_reg_re[Delay23_t_0_1] <= Delay23_reg_next_re[Delay23_t_0_1];
            Delay23_reg_im[Delay23_t_0_1] <= Delay23_reg_next_im[Delay23_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay23_out1_re = Delay23_reg_re[2];
    Delay23_out1_im = Delay23_reg_im[2];
    Delay23_reg_next_re[0] = FFT8_out5_re;
    Delay23_reg_next_im[0] = FFT8_out5_im;

    for(Delay23_t_0_0 = 32'sd0; Delay23_t_0_0 <= 32'sd1; Delay23_t_0_0 = Delay23_t_0_0 + 32'sd1) begin
      Delay23_reg_next_re[Delay23_t_0_0 + 32'sd1] = Delay23_reg_re[Delay23_t_0_0];
      Delay23_reg_next_im[Delay23_t_0_0 + 32'sd1] = Delay23_reg_im[Delay23_t_0_0];
    end

  end



  always @(posedge clk or posedge reset)
    begin : Delay34_process
      if (reset == 1'b1) begin
        for(Delay34_t_1 = 32'sd0; Delay34_t_1 <= 32'sd2; Delay34_t_1 = Delay34_t_1 + 32'sd1) begin
          Delay34_reg_re[Delay34_t_1] <= 22'sb0000000000000000000000;
          Delay34_reg_im[Delay34_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay34_t_0_1 = 32'sd0; Delay34_t_0_1 <= 32'sd2; Delay34_t_0_1 = Delay34_t_0_1 + 32'sd1) begin
            Delay34_reg_re[Delay34_t_0_1] <= Delay34_reg_next_re[Delay34_t_0_1];
            Delay34_reg_im[Delay34_t_0_1] <= Delay34_reg_next_im[Delay34_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay34_out1_re = Delay34_reg_re[2];
    Delay34_out1_im = Delay34_reg_im[2];
    Delay34_reg_next_re[0] = Delay23_out1_re;
    Delay34_reg_next_im[0] = Delay23_out1_im;

    for(Delay34_t_0_0 = 32'sd0; Delay34_t_0_0 <= 32'sd1; Delay34_t_0_0 = Delay34_t_0_0 + 32'sd1) begin
      Delay34_reg_next_re[Delay34_t_0_0 + 32'sd1] = Delay34_reg_re[Delay34_t_0_0];
      Delay34_reg_next_im[Delay34_t_0_0 + 32'sd1] = Delay34_reg_im[Delay34_t_0_0];
    end

  end



  multByMinusJ_block8 u_multByMinusJ (.x4_re(FFT8_1_out5_re),  // sfix22_En15
                                      .x4_im(FFT8_1_out5_im),  // sfix22_En15
                                      .Out1_re(multByMinusJ_out1_re),  // sfix22_En15
                                      .Out1_im(multByMinusJ_out1_im)  // sfix22_En15
                                      );

  always @(posedge clk or posedge reset)
    begin : Delay21_process
      if (reset == 1'b1) begin
        for(Delay21_t_1 = 32'sd0; Delay21_t_1 <= 32'sd2; Delay21_t_1 = Delay21_t_1 + 32'sd1) begin
          Delay21_reg_re[Delay21_t_1] <= 22'sb0000000000000000000000;
          Delay21_reg_im[Delay21_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay21_t_0_1 = 32'sd0; Delay21_t_0_1 <= 32'sd2; Delay21_t_0_1 = Delay21_t_0_1 + 32'sd1) begin
            Delay21_reg_re[Delay21_t_0_1] <= Delay21_reg_next_re[Delay21_t_0_1];
            Delay21_reg_im[Delay21_t_0_1] <= Delay21_reg_next_im[Delay21_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay21_out1_re = Delay21_reg_re[2];
    Delay21_out1_im = Delay21_reg_im[2];
    Delay21_reg_next_re[0] = multByMinusJ_out1_re;
    Delay21_reg_next_im[0] = multByMinusJ_out1_im;

    for(Delay21_t_0_0 = 32'sd0; Delay21_t_0_0 <= 32'sd1; Delay21_t_0_0 = Delay21_t_0_0 + 32'sd1) begin
      Delay21_reg_next_re[Delay21_t_0_0 + 32'sd1] = Delay21_reg_re[Delay21_t_0_0];
      Delay21_reg_next_im[Delay21_t_0_0 + 32'sd1] = Delay21_reg_im[Delay21_t_0_0];
    end

  end



  always @(posedge clk or posedge reset)
    begin : Delay41_process
      if (reset == 1'b1) begin
        for(Delay41_t_1 = 32'sd0; Delay41_t_1 <= 32'sd2; Delay41_t_1 = Delay41_t_1 + 32'sd1) begin
          Delay41_reg_re[Delay41_t_1] <= 22'sb0000000000000000000000;
          Delay41_reg_im[Delay41_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay41_t_0_1 = 32'sd0; Delay41_t_0_1 <= 32'sd2; Delay41_t_0_1 = Delay41_t_0_1 + 32'sd1) begin
            Delay41_reg_re[Delay41_t_0_1] <= Delay41_reg_next_re[Delay41_t_0_1];
            Delay41_reg_im[Delay41_t_0_1] <= Delay41_reg_next_im[Delay41_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay41_out1_re = Delay41_reg_re[2];
    Delay41_out1_im = Delay41_reg_im[2];
    Delay41_reg_next_re[0] = Delay21_out1_re;
    Delay41_reg_next_im[0] = Delay21_out1_im;

    for(Delay41_t_0_0 = 32'sd0; Delay41_t_0_0 <= 32'sd1; Delay41_t_0_0 = Delay41_t_0_0 + 32'sd1) begin
      Delay41_reg_next_re[Delay41_t_0_0 + 32'sd1] = Delay41_reg_re[Delay41_t_0_0];
      Delay41_reg_next_im[Delay41_t_0_0 + 32'sd1] = Delay41_reg_im[Delay41_t_0_0];
    end

  end



  assign Add8_add_cast = {{10{Delay34_out1_re[21]}}, Delay34_out1_re};
  assign Add8_add_cast_1 = {{10{Delay41_out1_re[21]}}, Delay41_out1_re};
  assign Add8_add_temp = Add8_add_cast + Add8_add_cast_1;
  assign Add8_out1_re = Add8_add_temp[21:0];
  assign Add8_add_cast_2 = {{10{Delay34_out1_im[21]}}, Delay34_out1_im};
  assign Add8_add_cast_3 = {{10{Delay41_out1_im[21]}}, Delay41_out1_im};
  assign Add8_add_temp_1 = Add8_add_cast_2 + Add8_add_cast_3;
  assign Add8_out1_im = Add8_add_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay7_process
      if (reset == 1'b1) begin
        for(Delay7_t_1 = 32'sd0; Delay7_t_1 <= 32'sd1; Delay7_t_1 = Delay7_t_1 + 32'sd1) begin
          Delay7_reg_re[Delay7_t_1] <= 22'sb0000000000000000000000;
          Delay7_reg_im[Delay7_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay7_t_0_0 = 32'sd0; Delay7_t_0_0 <= 32'sd1; Delay7_t_0_0 = Delay7_t_0_0 + 32'sd1) begin
            Delay7_reg_re[Delay7_t_0_0] <= Delay7_reg_next_re[Delay7_t_0_0];
            Delay7_reg_im[Delay7_t_0_0] <= Delay7_reg_next_im[Delay7_t_0_0];
          end
        end
      end
    end

  assign Delay7_out1_re = Delay7_reg_re[1];
  assign Delay7_out1_im = Delay7_reg_im[1];
  assign Delay7_reg_next_re[0] = Add8_out1_re;
  assign Delay7_reg_next_im[0] = Add8_out1_im;
  assign Delay7_reg_next_re[1] = Delay7_reg_re[0];
  assign Delay7_reg_next_im[1] = Delay7_reg_im[0];



  assign x4_re = Delay7_out1_re;

  assign x4_im = Delay7_out1_im;

  always @(posedge clk or posedge reset)
    begin : Delay24_process
      if (reset == 1'b1) begin
        for(Delay24_t_1 = 32'sd0; Delay24_t_1 <= 32'sd2; Delay24_t_1 = Delay24_t_1 + 32'sd1) begin
          Delay24_reg_re[Delay24_t_1] <= 22'sb0000000000000000000000;
          Delay24_reg_im[Delay24_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay24_t_0_1 = 32'sd0; Delay24_t_0_1 <= 32'sd2; Delay24_t_0_1 = Delay24_t_0_1 + 32'sd1) begin
            Delay24_reg_re[Delay24_t_0_1] <= Delay24_reg_next_re[Delay24_t_0_1];
            Delay24_reg_im[Delay24_t_0_1] <= Delay24_reg_next_im[Delay24_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay24_out1_re = Delay24_reg_re[2];
    Delay24_out1_im = Delay24_reg_im[2];
    Delay24_reg_next_re[0] = FFT8_out6_re;
    Delay24_reg_next_im[0] = FFT8_out6_im;

    for(Delay24_t_0_0 = 32'sd0; Delay24_t_0_0 <= 32'sd1; Delay24_t_0_0 = Delay24_t_0_0 + 32'sd1) begin
      Delay24_reg_next_re[Delay24_t_0_0 + 32'sd1] = Delay24_reg_re[Delay24_t_0_0];
      Delay24_reg_next_im[Delay24_t_0_0 + 32'sd1] = Delay24_reg_im[Delay24_t_0_0];
    end

  end



  always @(posedge clk or posedge reset)
    begin : Delay35_process
      if (reset == 1'b1) begin
        for(Delay35_t_1 = 32'sd0; Delay35_t_1 <= 32'sd2; Delay35_t_1 = Delay35_t_1 + 32'sd1) begin
          Delay35_reg_re[Delay35_t_1] <= 22'sb0000000000000000000000;
          Delay35_reg_im[Delay35_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay35_t_0_1 = 32'sd0; Delay35_t_0_1 <= 32'sd2; Delay35_t_0_1 = Delay35_t_0_1 + 32'sd1) begin
            Delay35_reg_re[Delay35_t_0_1] <= Delay35_reg_next_re[Delay35_t_0_1];
            Delay35_reg_im[Delay35_t_0_1] <= Delay35_reg_next_im[Delay35_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay35_out1_re = Delay35_reg_re[2];
    Delay35_out1_im = Delay35_reg_im[2];
    Delay35_reg_next_re[0] = Delay24_out1_re;
    Delay35_reg_next_im[0] = Delay24_out1_im;

    for(Delay35_t_0_0 = 32'sd0; Delay35_t_0_0 <= 32'sd1; Delay35_t_0_0 = Delay35_t_0_0 + 32'sd1) begin
      Delay35_reg_next_re[Delay35_t_0_0 + 32'sd1] = Delay35_reg_re[Delay35_t_0_0];
      Delay35_reg_next_im[Delay35_t_0_0 + 32'sd1] = Delay35_reg_im[Delay35_t_0_0];
    end

  end



  assign Constant3_out1_re = 18'sb110011110000010001;
  assign Constant3_out1_im = 18'sb100010011011111001;



  complexmult2_block2 u_complexmult2 (.clk(clk),
                                      .reset(reset),
                                      .enb_1_64_0(enb_1_64_0),
                                      .x1_re(FFT8_1_out6_re),  // sfix22_En15
                                      .x1_im(FFT8_1_out6_im),  // sfix22_En15
                                      .In3_re(Constant3_out1_re),  // sfix18_En17
                                      .In3_im(Constant3_out1_im),  // sfix18_En17
                                      .Out1_re(complexmult2_out1_re),  // sfix22_En15
                                      .Out1_im(complexmult2_out1_im)  // sfix22_En15
                                      );

  always @(posedge clk or posedge reset)
    begin : Delay42_process
      if (reset == 1'b1) begin
        Delay42_out1_re <= 22'sb0000000000000000000000;
        Delay42_out1_im <= 22'sb0000000000000000000000;
      end
      else begin
        if (enb_1_64_0) begin
          Delay42_out1_re <= complexmult2_out1_re;
          Delay42_out1_im <= complexmult2_out1_im;
        end
      end
    end



  assign Add10_add_cast = {{10{Delay35_out1_re[21]}}, Delay35_out1_re};
  assign Add10_add_cast_1 = {{10{Delay42_out1_re[21]}}, Delay42_out1_re};
  assign Add10_add_temp = Add10_add_cast + Add10_add_cast_1;
  assign Add10_out1_re = Add10_add_temp[21:0];
  assign Add10_add_cast_2 = {{10{Delay35_out1_im[21]}}, Delay35_out1_im};
  assign Add10_add_cast_3 = {{10{Delay42_out1_im[21]}}, Delay42_out1_im};
  assign Add10_add_temp_1 = Add10_add_cast_2 + Add10_add_cast_3;
  assign Add10_out1_im = Add10_add_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay5_process
      if (reset == 1'b1) begin
        for(Delay5_t_1 = 32'sd0; Delay5_t_1 <= 32'sd1; Delay5_t_1 = Delay5_t_1 + 32'sd1) begin
          Delay5_reg_re[Delay5_t_1] <= 22'sb0000000000000000000000;
          Delay5_reg_im[Delay5_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay5_t_0_0 = 32'sd0; Delay5_t_0_0 <= 32'sd1; Delay5_t_0_0 = Delay5_t_0_0 + 32'sd1) begin
            Delay5_reg_re[Delay5_t_0_0] <= Delay5_reg_next_re[Delay5_t_0_0];
            Delay5_reg_im[Delay5_t_0_0] <= Delay5_reg_next_im[Delay5_t_0_0];
          end
        end
      end
    end

  assign Delay5_out1_re = Delay5_reg_re[1];
  assign Delay5_out1_im = Delay5_reg_im[1];
  assign Delay5_reg_next_re[0] = Add10_out1_re;
  assign Delay5_reg_next_im[0] = Add10_out1_im;
  assign Delay5_reg_next_re[1] = Delay5_reg_re[0];
  assign Delay5_reg_next_im[1] = Delay5_reg_im[0];



  assign x5_re = Delay5_out1_re;

  assign x5_im = Delay5_out1_im;

  always @(posedge clk or posedge reset)
    begin : Delay26_process
      if (reset == 1'b1) begin
        for(Delay26_t_1 = 32'sd0; Delay26_t_1 <= 32'sd2; Delay26_t_1 = Delay26_t_1 + 32'sd1) begin
          Delay26_reg_re[Delay26_t_1] <= 22'sb0000000000000000000000;
          Delay26_reg_im[Delay26_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay26_t_0_1 = 32'sd0; Delay26_t_0_1 <= 32'sd2; Delay26_t_0_1 = Delay26_t_0_1 + 32'sd1) begin
            Delay26_reg_re[Delay26_t_0_1] <= Delay26_reg_next_re[Delay26_t_0_1];
            Delay26_reg_im[Delay26_t_0_1] <= Delay26_reg_next_im[Delay26_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay26_out1_re = Delay26_reg_re[2];
    Delay26_out1_im = Delay26_reg_im[2];
    Delay26_reg_next_re[0] = FFT8_out7_re;
    Delay26_reg_next_im[0] = FFT8_out7_im;

    for(Delay26_t_0_0 = 32'sd0; Delay26_t_0_0 <= 32'sd1; Delay26_t_0_0 = Delay26_t_0_0 + 32'sd1) begin
      Delay26_reg_next_re[Delay26_t_0_0 + 32'sd1] = Delay26_reg_re[Delay26_t_0_0];
      Delay26_reg_next_im[Delay26_t_0_0 + 32'sd1] = Delay26_reg_im[Delay26_t_0_0];
    end

  end



  always @(posedge clk or posedge reset)
    begin : Delay36_process
      if (reset == 1'b1) begin
        for(Delay36_t_1 = 32'sd0; Delay36_t_1 <= 32'sd2; Delay36_t_1 = Delay36_t_1 + 32'sd1) begin
          Delay36_reg_re[Delay36_t_1] <= 22'sb0000000000000000000000;
          Delay36_reg_im[Delay36_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay36_t_0_1 = 32'sd0; Delay36_t_0_1 <= 32'sd2; Delay36_t_0_1 = Delay36_t_0_1 + 32'sd1) begin
            Delay36_reg_re[Delay36_t_0_1] <= Delay36_reg_next_re[Delay36_t_0_1];
            Delay36_reg_im[Delay36_t_0_1] <= Delay36_reg_next_im[Delay36_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay36_out1_re = Delay36_reg_re[2];
    Delay36_out1_im = Delay36_reg_im[2];
    Delay36_reg_next_re[0] = Delay26_out1_re;
    Delay36_reg_next_im[0] = Delay26_out1_im;

    for(Delay36_t_0_0 = 32'sd0; Delay36_t_0_0 <= 32'sd1; Delay36_t_0_0 = Delay36_t_0_0 + 32'sd1) begin
      Delay36_reg_next_re[Delay36_t_0_0 + 32'sd1] = Delay36_reg_re[Delay36_t_0_0];
      Delay36_reg_next_im[Delay36_t_0_0 + 32'sd1] = Delay36_reg_im[Delay36_t_0_0];
    end

  end



  alpha4_1_block8 u_multByExp_j_Pi_4_1 (.clk(clk),
                                        .reset(reset),
                                        .enb_1_64_0(enb_1_64_0),
                                        .x4_re(FFT8_1_out7_re),  // sfix22_En15
                                        .x4_im(FFT8_1_out7_im),  // sfix22_En15
                                        .Out1_re(multByExp_j_Pi_4_1_out1_re),  // sfix22_En15
                                        .Out1_im(multByExp_j_Pi_4_1_out1_im)  // sfix22_En15
                                        );

  multByMinusJ3_block8 u_multByMinusJ3 (.In1_re(multByExp_j_Pi_4_1_out1_re),  // sfix22_En15
                                        .In1_im(multByExp_j_Pi_4_1_out1_im),  // sfix22_En15
                                        .Out1_re(multByMinusJ3_out1_re),  // sfix22_En15
                                        .Out1_im(multByMinusJ3_out1_im)  // sfix22_En15
                                        );

  always @(posedge clk or posedge reset)
    begin : Delay43_process
      if (reset == 1'b1) begin
        Delay43_out1_re <= 22'sb0000000000000000000000;
        Delay43_out1_im <= 22'sb0000000000000000000000;
      end
      else begin
        if (enb_1_64_0) begin
          Delay43_out1_re <= multByMinusJ3_out1_re;
          Delay43_out1_im <= multByMinusJ3_out1_im;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : Delay25_process
      if (reset == 1'b1) begin
        for(Delay25_t_1 = 32'sd0; Delay25_t_1 <= 32'sd2; Delay25_t_1 = Delay25_t_1 + 32'sd1) begin
          Delay25_reg_re[Delay25_t_1] <= 22'sb0000000000000000000000;
          Delay25_reg_im[Delay25_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay25_t_0_1 = 32'sd0; Delay25_t_0_1 <= 32'sd2; Delay25_t_0_1 = Delay25_t_0_1 + 32'sd1) begin
            Delay25_reg_re[Delay25_t_0_1] <= Delay25_reg_next_re[Delay25_t_0_1];
            Delay25_reg_im[Delay25_t_0_1] <= Delay25_reg_next_im[Delay25_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay25_out1_re = Delay25_reg_re[2];
    Delay25_out1_im = Delay25_reg_im[2];
    Delay25_reg_next_re[0] = Delay43_out1_re;
    Delay25_reg_next_im[0] = Delay43_out1_im;

    for(Delay25_t_0_0 = 32'sd0; Delay25_t_0_0 <= 32'sd1; Delay25_t_0_0 = Delay25_t_0_0 + 32'sd1) begin
      Delay25_reg_next_re[Delay25_t_0_0 + 32'sd1] = Delay25_reg_re[Delay25_t_0_0];
      Delay25_reg_next_im[Delay25_t_0_0 + 32'sd1] = Delay25_reg_im[Delay25_t_0_0];
    end

  end



  assign Add12_add_cast = {{10{Delay36_out1_re[21]}}, Delay36_out1_re};
  assign Add12_add_cast_1 = {{10{Delay25_out1_re[21]}}, Delay25_out1_re};
  assign Add12_add_temp = Add12_add_cast + Add12_add_cast_1;
  assign Add12_out1_re = Add12_add_temp[21:0];
  assign Add12_add_cast_2 = {{10{Delay36_out1_im[21]}}, Delay36_out1_im};
  assign Add12_add_cast_3 = {{10{Delay25_out1_im[21]}}, Delay25_out1_im};
  assign Add12_add_temp_1 = Add12_add_cast_2 + Add12_add_cast_3;
  assign Add12_out1_im = Add12_add_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        for(Delay3_t_1 = 32'sd0; Delay3_t_1 <= 32'sd1; Delay3_t_1 = Delay3_t_1 + 32'sd1) begin
          Delay3_reg_re[Delay3_t_1] <= 22'sb0000000000000000000000;
          Delay3_reg_im[Delay3_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay3_t_0_0 = 32'sd0; Delay3_t_0_0 <= 32'sd1; Delay3_t_0_0 = Delay3_t_0_0 + 32'sd1) begin
            Delay3_reg_re[Delay3_t_0_0] <= Delay3_reg_next_re[Delay3_t_0_0];
            Delay3_reg_im[Delay3_t_0_0] <= Delay3_reg_next_im[Delay3_t_0_0];
          end
        end
      end
    end

  assign Delay3_out1_re = Delay3_reg_re[1];
  assign Delay3_out1_im = Delay3_reg_im[1];
  assign Delay3_reg_next_re[0] = Add12_out1_re;
  assign Delay3_reg_next_im[0] = Add12_out1_im;
  assign Delay3_reg_next_re[1] = Delay3_reg_re[0];
  assign Delay3_reg_next_im[1] = Delay3_reg_im[0];



  assign x6_re = Delay3_out1_re;

  assign x6_im = Delay3_out1_im;

  always @(posedge clk or posedge reset)
    begin : Delay27_process
      if (reset == 1'b1) begin
        for(Delay27_t_1 = 32'sd0; Delay27_t_1 <= 32'sd2; Delay27_t_1 = Delay27_t_1 + 32'sd1) begin
          Delay27_reg_re[Delay27_t_1] <= 22'sb0000000000000000000000;
          Delay27_reg_im[Delay27_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay27_t_0_1 = 32'sd0; Delay27_t_0_1 <= 32'sd2; Delay27_t_0_1 = Delay27_t_0_1 + 32'sd1) begin
            Delay27_reg_re[Delay27_t_0_1] <= Delay27_reg_next_re[Delay27_t_0_1];
            Delay27_reg_im[Delay27_t_0_1] <= Delay27_reg_next_im[Delay27_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay27_out1_re = Delay27_reg_re[2];
    Delay27_out1_im = Delay27_reg_im[2];
    Delay27_reg_next_re[0] = FFT8_out8_re;
    Delay27_reg_next_im[0] = FFT8_out8_im;

    for(Delay27_t_0_0 = 32'sd0; Delay27_t_0_0 <= 32'sd1; Delay27_t_0_0 = Delay27_t_0_0 + 32'sd1) begin
      Delay27_reg_next_re[Delay27_t_0_0 + 32'sd1] = Delay27_reg_re[Delay27_t_0_0];
      Delay27_reg_next_im[Delay27_t_0_0 + 32'sd1] = Delay27_reg_im[Delay27_t_0_0];
    end

  end



  always @(posedge clk or posedge reset)
    begin : Delay37_process
      if (reset == 1'b1) begin
        for(Delay37_t_1 = 32'sd0; Delay37_t_1 <= 32'sd2; Delay37_t_1 = Delay37_t_1 + 32'sd1) begin
          Delay37_reg_re[Delay37_t_1] <= 22'sb0000000000000000000000;
          Delay37_reg_im[Delay37_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay37_t_0_1 = 32'sd0; Delay37_t_0_1 <= 32'sd2; Delay37_t_0_1 = Delay37_t_0_1 + 32'sd1) begin
            Delay37_reg_re[Delay37_t_0_1] <= Delay37_reg_next_re[Delay37_t_0_1];
            Delay37_reg_im[Delay37_t_0_1] <= Delay37_reg_next_im[Delay37_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay37_out1_re = Delay37_reg_re[2];
    Delay37_out1_im = Delay37_reg_im[2];
    Delay37_reg_next_re[0] = Delay27_out1_re;
    Delay37_reg_next_im[0] = Delay27_out1_im;

    for(Delay37_t_0_0 = 32'sd0; Delay37_t_0_0 <= 32'sd1; Delay37_t_0_0 = Delay37_t_0_0 + 32'sd1) begin
      Delay37_reg_next_re[Delay37_t_0_0 + 32'sd1] = Delay37_reg_re[Delay37_t_0_0];
      Delay37_reg_next_im[Delay37_t_0_0 + 32'sd1] = Delay37_reg_im[Delay37_t_0_0];
    end

  end



  assign Constant4_out1_re = 18'sb100010011011111001;
  assign Constant4_out1_im = 18'sb110011110000010001;



  complexmult3_block2 u_complexmult3 (.clk(clk),
                                      .reset(reset),
                                      .enb_1_64_0(enb_1_64_0),
                                      .x1_re(FFT8_1_out8_re),  // sfix22_En15
                                      .x1_im(FFT8_1_out8_im),  // sfix22_En15
                                      .In3_re(Constant4_out1_re),  // sfix18_En17
                                      .In3_im(Constant4_out1_im),  // sfix18_En17
                                      .Out1_re(complexmult3_out1_re),  // sfix22_En15
                                      .Out1_im(complexmult3_out1_im)  // sfix22_En15
                                      );

  always @(posedge clk or posedge reset)
    begin : Delay44_process
      if (reset == 1'b1) begin
        Delay44_out1_re <= 22'sb0000000000000000000000;
        Delay44_out1_im <= 22'sb0000000000000000000000;
      end
      else begin
        if (enb_1_64_0) begin
          Delay44_out1_re <= complexmult3_out1_re;
          Delay44_out1_im <= complexmult3_out1_im;
        end
      end
    end



  assign Add14_add_cast = {{10{Delay37_out1_re[21]}}, Delay37_out1_re};
  assign Add14_add_cast_1 = {{10{Delay44_out1_re[21]}}, Delay44_out1_re};
  assign Add14_add_temp = Add14_add_cast + Add14_add_cast_1;
  assign Add14_out1_re = Add14_add_temp[21:0];
  assign Add14_add_cast_2 = {{10{Delay37_out1_im[21]}}, Delay37_out1_im};
  assign Add14_add_cast_3 = {{10{Delay44_out1_im[21]}}, Delay44_out1_im};
  assign Add14_add_temp_1 = Add14_add_cast_2 + Add14_add_cast_3;
  assign Add14_out1_im = Add14_add_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        for(Delay1_t_1 = 32'sd0; Delay1_t_1 <= 32'sd1; Delay1_t_1 = Delay1_t_1 + 32'sd1) begin
          Delay1_reg_re[Delay1_t_1] <= 22'sb0000000000000000000000;
          Delay1_reg_im[Delay1_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay1_t_0_0 = 32'sd0; Delay1_t_0_0 <= 32'sd1; Delay1_t_0_0 = Delay1_t_0_0 + 32'sd1) begin
            Delay1_reg_re[Delay1_t_0_0] <= Delay1_reg_next_re[Delay1_t_0_0];
            Delay1_reg_im[Delay1_t_0_0] <= Delay1_reg_next_im[Delay1_t_0_0];
          end
        end
      end
    end

  assign Delay1_out1_re = Delay1_reg_re[1];
  assign Delay1_out1_im = Delay1_reg_im[1];
  assign Delay1_reg_next_re[0] = Add14_out1_re;
  assign Delay1_reg_next_im[0] = Add14_out1_im;
  assign Delay1_reg_next_re[1] = Delay1_reg_re[0];
  assign Delay1_reg_next_im[1] = Delay1_reg_im[0];



  assign x7_re = Delay1_out1_re;

  assign x7_im = Delay1_out1_im;

  assign Add1_sub_cast = {{10{Delay33_out1_re[21]}}, Delay33_out1_re};
  assign Add1_sub_cast_1 = {{10{Delay30_out1_re[21]}}, Delay30_out1_re};
  assign Add1_sub_temp = Add1_sub_cast - Add1_sub_cast_1;
  assign Add1_out1_re = Add1_sub_temp[21:0];
  assign Add1_sub_cast_2 = {{10{Delay33_out1_im[21]}}, Delay33_out1_im};
  assign Add1_sub_cast_3 = {{10{Delay30_out1_im[21]}}, Delay30_out1_im};
  assign Add1_sub_temp_1 = Add1_sub_cast_2 - Add1_sub_cast_3;
  assign Add1_out1_im = Add1_sub_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay14_process
      if (reset == 1'b1) begin
        for(Delay14_t_1 = 32'sd0; Delay14_t_1 <= 32'sd1; Delay14_t_1 = Delay14_t_1 + 32'sd1) begin
          Delay14_reg_re[Delay14_t_1] <= 22'sb0000000000000000000000;
          Delay14_reg_im[Delay14_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay14_t_0_0 = 32'sd0; Delay14_t_0_0 <= 32'sd1; Delay14_t_0_0 = Delay14_t_0_0 + 32'sd1) begin
            Delay14_reg_re[Delay14_t_0_0] <= Delay14_reg_next_re[Delay14_t_0_0];
            Delay14_reg_im[Delay14_t_0_0] <= Delay14_reg_next_im[Delay14_t_0_0];
          end
        end
      end
    end

  assign Delay14_out1_re = Delay14_reg_re[1];
  assign Delay14_out1_im = Delay14_reg_im[1];
  assign Delay14_reg_next_re[0] = Add1_out1_re;
  assign Delay14_reg_next_im[0] = Add1_out1_im;
  assign Delay14_reg_next_re[1] = Delay14_reg_re[0];
  assign Delay14_reg_next_im[1] = Delay14_reg_im[0];



  assign x8_re = Delay14_out1_re;

  assign x8_im = Delay14_out1_im;

  assign Add3_sub_cast = {{10{Delay31_out1_re[21]}}, Delay31_out1_re};
  assign Add3_sub_cast_1 = {{10{Delay38_out1_re[21]}}, Delay38_out1_re};
  assign Add3_sub_temp = Add3_sub_cast - Add3_sub_cast_1;
  assign Add3_out1_re = Add3_sub_temp[21:0];
  assign Add3_sub_cast_2 = {{10{Delay31_out1_im[21]}}, Delay31_out1_im};
  assign Add3_sub_cast_3 = {{10{Delay38_out1_im[21]}}, Delay38_out1_im};
  assign Add3_sub_temp_1 = Add3_sub_cast_2 - Add3_sub_cast_3;
  assign Add3_out1_im = Add3_sub_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay12_process
      if (reset == 1'b1) begin
        for(Delay12_t_1 = 32'sd0; Delay12_t_1 <= 32'sd1; Delay12_t_1 = Delay12_t_1 + 32'sd1) begin
          Delay12_reg_re[Delay12_t_1] <= 22'sb0000000000000000000000;
          Delay12_reg_im[Delay12_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay12_t_0_0 = 32'sd0; Delay12_t_0_0 <= 32'sd1; Delay12_t_0_0 = Delay12_t_0_0 + 32'sd1) begin
            Delay12_reg_re[Delay12_t_0_0] <= Delay12_reg_next_re[Delay12_t_0_0];
            Delay12_reg_im[Delay12_t_0_0] <= Delay12_reg_next_im[Delay12_t_0_0];
          end
        end
      end
    end

  assign Delay12_out1_re = Delay12_reg_re[1];
  assign Delay12_out1_im = Delay12_reg_im[1];
  assign Delay12_reg_next_re[0] = Add3_out1_re;
  assign Delay12_reg_next_im[0] = Add3_out1_im;
  assign Delay12_reg_next_re[1] = Delay12_reg_re[0];
  assign Delay12_reg_next_im[1] = Delay12_reg_im[0];



  assign x9_re = Delay12_out1_re;

  assign x9_im = Delay12_out1_im;

  assign Add5_sub_cast = {{10{Delay32_out1_re[21]}}, Delay32_out1_re};
  assign Add5_sub_cast_1 = {{10{Delay39_out1_re[21]}}, Delay39_out1_re};
  assign Add5_sub_temp = Add5_sub_cast - Add5_sub_cast_1;
  assign Add5_out1_re = Add5_sub_temp[21:0];
  assign Add5_sub_cast_2 = {{10{Delay32_out1_im[21]}}, Delay32_out1_im};
  assign Add5_sub_cast_3 = {{10{Delay39_out1_im[21]}}, Delay39_out1_im};
  assign Add5_sub_temp_1 = Add5_sub_cast_2 - Add5_sub_cast_3;
  assign Add5_out1_im = Add5_sub_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay10_process
      if (reset == 1'b1) begin
        for(Delay10_t_1 = 32'sd0; Delay10_t_1 <= 32'sd1; Delay10_t_1 = Delay10_t_1 + 32'sd1) begin
          Delay10_reg_re[Delay10_t_1] <= 22'sb0000000000000000000000;
          Delay10_reg_im[Delay10_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay10_t_0_0 = 32'sd0; Delay10_t_0_0 <= 32'sd1; Delay10_t_0_0 = Delay10_t_0_0 + 32'sd1) begin
            Delay10_reg_re[Delay10_t_0_0] <= Delay10_reg_next_re[Delay10_t_0_0];
            Delay10_reg_im[Delay10_t_0_0] <= Delay10_reg_next_im[Delay10_t_0_0];
          end
        end
      end
    end

  assign Delay10_out1_re = Delay10_reg_re[1];
  assign Delay10_out1_im = Delay10_reg_im[1];
  assign Delay10_reg_next_re[0] = Add5_out1_re;
  assign Delay10_reg_next_im[0] = Add5_out1_im;
  assign Delay10_reg_next_re[1] = Delay10_reg_re[0];
  assign Delay10_reg_next_im[1] = Delay10_reg_im[0];



  assign x10_re = Delay10_out1_re;

  assign x10_im = Delay10_out1_im;

  assign Add7_sub_cast = {{10{Delay29_out1_re[21]}}, Delay29_out1_re};
  assign Add7_sub_cast_1 = {{10{Delay40_out1_re[21]}}, Delay40_out1_re};
  assign Add7_sub_temp = Add7_sub_cast - Add7_sub_cast_1;
  assign Add7_out1_re = Add7_sub_temp[21:0];
  assign Add7_sub_cast_2 = {{10{Delay29_out1_im[21]}}, Delay29_out1_im};
  assign Add7_sub_cast_3 = {{10{Delay40_out1_im[21]}}, Delay40_out1_im};
  assign Add7_sub_temp_1 = Add7_sub_cast_2 - Add7_sub_cast_3;
  assign Add7_out1_im = Add7_sub_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay8_process
      if (reset == 1'b1) begin
        for(Delay8_t_1 = 32'sd0; Delay8_t_1 <= 32'sd1; Delay8_t_1 = Delay8_t_1 + 32'sd1) begin
          Delay8_reg_re[Delay8_t_1] <= 22'sb0000000000000000000000;
          Delay8_reg_im[Delay8_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay8_t_0_0 = 32'sd0; Delay8_t_0_0 <= 32'sd1; Delay8_t_0_0 = Delay8_t_0_0 + 32'sd1) begin
            Delay8_reg_re[Delay8_t_0_0] <= Delay8_reg_next_re[Delay8_t_0_0];
            Delay8_reg_im[Delay8_t_0_0] <= Delay8_reg_next_im[Delay8_t_0_0];
          end
        end
      end
    end

  assign Delay8_out1_re = Delay8_reg_re[1];
  assign Delay8_out1_im = Delay8_reg_im[1];
  assign Delay8_reg_next_re[0] = Add7_out1_re;
  assign Delay8_reg_next_im[0] = Add7_out1_im;
  assign Delay8_reg_next_re[1] = Delay8_reg_re[0];
  assign Delay8_reg_next_im[1] = Delay8_reg_im[0];



  assign x11_re = Delay8_out1_re;

  assign x11_im = Delay8_out1_im;

  assign Add9_sub_cast = {{10{Delay34_out1_re[21]}}, Delay34_out1_re};
  assign Add9_sub_cast_1 = {{10{Delay41_out1_re[21]}}, Delay41_out1_re};
  assign Add9_sub_temp = Add9_sub_cast - Add9_sub_cast_1;
  assign Add9_out1_re = Add9_sub_temp[21:0];
  assign Add9_sub_cast_2 = {{10{Delay34_out1_im[21]}}, Delay34_out1_im};
  assign Add9_sub_cast_3 = {{10{Delay41_out1_im[21]}}, Delay41_out1_im};
  assign Add9_sub_temp_1 = Add9_sub_cast_2 - Add9_sub_cast_3;
  assign Add9_out1_im = Add9_sub_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay6_process
      if (reset == 1'b1) begin
        for(Delay6_t_1 = 32'sd0; Delay6_t_1 <= 32'sd1; Delay6_t_1 = Delay6_t_1 + 32'sd1) begin
          Delay6_reg_re[Delay6_t_1] <= 22'sb0000000000000000000000;
          Delay6_reg_im[Delay6_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay6_t_0_0 = 32'sd0; Delay6_t_0_0 <= 32'sd1; Delay6_t_0_0 = Delay6_t_0_0 + 32'sd1) begin
            Delay6_reg_re[Delay6_t_0_0] <= Delay6_reg_next_re[Delay6_t_0_0];
            Delay6_reg_im[Delay6_t_0_0] <= Delay6_reg_next_im[Delay6_t_0_0];
          end
        end
      end
    end

  assign Delay6_out1_re = Delay6_reg_re[1];
  assign Delay6_out1_im = Delay6_reg_im[1];
  assign Delay6_reg_next_re[0] = Add9_out1_re;
  assign Delay6_reg_next_im[0] = Add9_out1_im;
  assign Delay6_reg_next_re[1] = Delay6_reg_re[0];
  assign Delay6_reg_next_im[1] = Delay6_reg_im[0];



  assign x12_re = Delay6_out1_re;

  assign x12_im = Delay6_out1_im;

  assign Add11_sub_cast = {{10{Delay35_out1_re[21]}}, Delay35_out1_re};
  assign Add11_sub_cast_1 = {{10{Delay42_out1_re[21]}}, Delay42_out1_re};
  assign Add11_sub_temp = Add11_sub_cast - Add11_sub_cast_1;
  assign Add11_out1_re = Add11_sub_temp[21:0];
  assign Add11_sub_cast_2 = {{10{Delay35_out1_im[21]}}, Delay35_out1_im};
  assign Add11_sub_cast_3 = {{10{Delay42_out1_im[21]}}, Delay42_out1_im};
  assign Add11_sub_temp_1 = Add11_sub_cast_2 - Add11_sub_cast_3;
  assign Add11_out1_im = Add11_sub_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        for(Delay4_t_1 = 32'sd0; Delay4_t_1 <= 32'sd1; Delay4_t_1 = Delay4_t_1 + 32'sd1) begin
          Delay4_reg_re[Delay4_t_1] <= 22'sb0000000000000000000000;
          Delay4_reg_im[Delay4_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay4_t_0_0 = 32'sd0; Delay4_t_0_0 <= 32'sd1; Delay4_t_0_0 = Delay4_t_0_0 + 32'sd1) begin
            Delay4_reg_re[Delay4_t_0_0] <= Delay4_reg_next_re[Delay4_t_0_0];
            Delay4_reg_im[Delay4_t_0_0] <= Delay4_reg_next_im[Delay4_t_0_0];
          end
        end
      end
    end

  assign Delay4_out1_re = Delay4_reg_re[1];
  assign Delay4_out1_im = Delay4_reg_im[1];
  assign Delay4_reg_next_re[0] = Add11_out1_re;
  assign Delay4_reg_next_im[0] = Add11_out1_im;
  assign Delay4_reg_next_re[1] = Delay4_reg_re[0];
  assign Delay4_reg_next_im[1] = Delay4_reg_im[0];



  assign x13_re = Delay4_out1_re;

  assign x13_im = Delay4_out1_im;

  assign Add13_sub_cast = {{10{Delay36_out1_re[21]}}, Delay36_out1_re};
  assign Add13_sub_cast_1 = {{10{Delay25_out1_re[21]}}, Delay25_out1_re};
  assign Add13_sub_temp = Add13_sub_cast - Add13_sub_cast_1;
  assign Add13_out1_re = Add13_sub_temp[21:0];
  assign Add13_sub_cast_2 = {{10{Delay36_out1_im[21]}}, Delay36_out1_im};
  assign Add13_sub_cast_3 = {{10{Delay25_out1_im[21]}}, Delay25_out1_im};
  assign Add13_sub_temp_1 = Add13_sub_cast_2 - Add13_sub_cast_3;
  assign Add13_out1_im = Add13_sub_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        for(Delay2_t_1 = 32'sd0; Delay2_t_1 <= 32'sd1; Delay2_t_1 = Delay2_t_1 + 32'sd1) begin
          Delay2_reg_re[Delay2_t_1] <= 22'sb0000000000000000000000;
          Delay2_reg_im[Delay2_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay2_t_0_0 = 32'sd0; Delay2_t_0_0 <= 32'sd1; Delay2_t_0_0 = Delay2_t_0_0 + 32'sd1) begin
            Delay2_reg_re[Delay2_t_0_0] <= Delay2_reg_next_re[Delay2_t_0_0];
            Delay2_reg_im[Delay2_t_0_0] <= Delay2_reg_next_im[Delay2_t_0_0];
          end
        end
      end
    end

  assign Delay2_out1_re = Delay2_reg_re[1];
  assign Delay2_out1_im = Delay2_reg_im[1];
  assign Delay2_reg_next_re[0] = Add13_out1_re;
  assign Delay2_reg_next_im[0] = Add13_out1_im;
  assign Delay2_reg_next_re[1] = Delay2_reg_re[0];
  assign Delay2_reg_next_im[1] = Delay2_reg_im[0];



  assign x14_re = Delay2_out1_re;

  assign x14_im = Delay2_out1_im;

  assign Add15_sub_cast = {{10{Delay37_out1_re[21]}}, Delay37_out1_re};
  assign Add15_sub_cast_1 = {{10{Delay44_out1_re[21]}}, Delay44_out1_re};
  assign Add15_sub_temp = Add15_sub_cast - Add15_sub_cast_1;
  assign Add15_out1_re = Add15_sub_temp[21:0];
  assign Add15_sub_cast_2 = {{10{Delay37_out1_im[21]}}, Delay37_out1_im};
  assign Add15_sub_cast_3 = {{10{Delay44_out1_im[21]}}, Delay44_out1_im};
  assign Add15_sub_temp_1 = Add15_sub_cast_2 - Add15_sub_cast_3;
  assign Add15_out1_im = Add15_sub_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay15_process
      if (reset == 1'b1) begin
        for(Delay15_t_1 = 32'sd0; Delay15_t_1 <= 32'sd1; Delay15_t_1 = Delay15_t_1 + 32'sd1) begin
          Delay15_reg_re[Delay15_t_1] <= 22'sb0000000000000000000000;
          Delay15_reg_im[Delay15_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay15_t_0_0 = 32'sd0; Delay15_t_0_0 <= 32'sd1; Delay15_t_0_0 = Delay15_t_0_0 + 32'sd1) begin
            Delay15_reg_re[Delay15_t_0_0] <= Delay15_reg_next_re[Delay15_t_0_0];
            Delay15_reg_im[Delay15_t_0_0] <= Delay15_reg_next_im[Delay15_t_0_0];
          end
        end
      end
    end

  assign Delay15_out1_re = Delay15_reg_re[1];
  assign Delay15_out1_im = Delay15_reg_im[1];
  assign Delay15_reg_next_re[0] = Add15_out1_re;
  assign Delay15_reg_next_im[0] = Add15_out1_im;
  assign Delay15_reg_next_re[1] = Delay15_reg_re[0];
  assign Delay15_reg_next_im[1] = Delay15_reg_im[0];



  assign x15_re = Delay15_out1_re;

  assign x15_im = Delay15_out1_im;

endmodule  // FFT16_block

