// -------------------------------------------------------------
// 
// File Name: /home/mori/Downloads/tomori_fft/hdlsrc/fft_overlap_tomori/FFT64_outMuxed.v
// Created: 2025-04-26 11:44:22
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 3.125e-10
// Target subsystem base rate: 2e-08
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        2e-08
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Out1_re                       ce_out        2e-08
// Out1_im                       ce_out        2e-08
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FFT64_outMuxed
// Source Path: fft_overlap_tomori/FFT64_outMuxed
// Hierarchy Level: 0
// Model version: 3.27
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FFT64_outMuxed
          (clk,
           reset,
           clk_enable,
           inputSamp_re,
           inputSamp_im,
           whichBin,
           ce_out,
           Out1_re,
           Out1_im);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [15:0] inputSamp_re;  // sfix16_En15
  input   signed [15:0] inputSamp_im;  // sfix16_En15
  input   [7:0] whichBin;  // uint8
  output  ce_out;
  output  signed [21:0] Out1_re;  // sfix22_En15
  output  signed [21:0] Out1_im;  // sfix22_En15


  wire signed [21:0] alpha64pointFFTchan_out1_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out1_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out2_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out2_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out3_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out3_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out4_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out4_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out5_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out5_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out6_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out6_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out7_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out7_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out8_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out8_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out9_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out9_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out10_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out10_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out11_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out11_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out12_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out12_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out13_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out13_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out14_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out14_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out15_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out15_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out16_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out16_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out17_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out17_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out18_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out18_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out19_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out19_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out20_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out20_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out21_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out21_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out22_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out22_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out23_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out23_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out24_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out24_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out25_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out25_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out26_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out26_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out27_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out27_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out28_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out28_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out29_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out29_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out30_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out30_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out31_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out31_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out32_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out32_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out33_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out33_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out34_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out34_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out35_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out35_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out36_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out36_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out37_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out37_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out38_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out38_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out39_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out39_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out40_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out40_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out41_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out41_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out42_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out42_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out43_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out43_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out44_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out44_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out45_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out45_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out46_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out46_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out47_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out47_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out48_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out48_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out49_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out49_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out50_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out50_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out51_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out51_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out52_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out52_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out53_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out53_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out54_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out54_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out55_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out55_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out56_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out56_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out57_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out57_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out58_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out58_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out59_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out59_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out60_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out60_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out61_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out61_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out62_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out62_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out63_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out63_im;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out64_re;  // sfix22_En15
  wire signed [21:0] alpha64pointFFTchan_out64_im;  // sfix22_En15
  wire signed [21:0] Multiport_Switch1_out1_re;  // sfix22_En15
  wire signed [21:0] Multiport_Switch1_out1_im;  // sfix22_En15


  alpha64pointFFTchan u_64pointFFTchan (.clk(clk),
                                        .reset(reset),
                                        .enb_1_64_0(clk_enable),
                                        .inputSamp_re(inputSamp_re),  // sfix16_En15
                                        .inputSamp_im(inputSamp_im),  // sfix16_En15
                                        .Out1_re(alpha64pointFFTchan_out1_re),  // sfix22_En15
                                        .Out1_im(alpha64pointFFTchan_out1_im),  // sfix22_En15
                                        .Out2_re(alpha64pointFFTchan_out2_re),  // sfix22_En15
                                        .Out2_im(alpha64pointFFTchan_out2_im),  // sfix22_En15
                                        .Out3_re(alpha64pointFFTchan_out3_re),  // sfix22_En15
                                        .Out3_im(alpha64pointFFTchan_out3_im),  // sfix22_En15
                                        .Out4_re(alpha64pointFFTchan_out4_re),  // sfix22_En15
                                        .Out4_im(alpha64pointFFTchan_out4_im),  // sfix22_En15
                                        .Out5_re(alpha64pointFFTchan_out5_re),  // sfix22_En15
                                        .Out5_im(alpha64pointFFTchan_out5_im),  // sfix22_En15
                                        .Out6_re(alpha64pointFFTchan_out6_re),  // sfix22_En15
                                        .Out6_im(alpha64pointFFTchan_out6_im),  // sfix22_En15
                                        .Out7_re(alpha64pointFFTchan_out7_re),  // sfix22_En15
                                        .Out7_im(alpha64pointFFTchan_out7_im),  // sfix22_En15
                                        .Out8_re(alpha64pointFFTchan_out8_re),  // sfix22_En15
                                        .Out8_im(alpha64pointFFTchan_out8_im),  // sfix22_En15
                                        .Out9_re(alpha64pointFFTchan_out9_re),  // sfix22_En15
                                        .Out9_im(alpha64pointFFTchan_out9_im),  // sfix22_En15
                                        .Out10_re(alpha64pointFFTchan_out10_re),  // sfix22_En15
                                        .Out10_im(alpha64pointFFTchan_out10_im),  // sfix22_En15
                                        .Out11_re(alpha64pointFFTchan_out11_re),  // sfix22_En15
                                        .Out11_im(alpha64pointFFTchan_out11_im),  // sfix22_En15
                                        .Out12_re(alpha64pointFFTchan_out12_re),  // sfix22_En15
                                        .Out12_im(alpha64pointFFTchan_out12_im),  // sfix22_En15
                                        .Out13_re(alpha64pointFFTchan_out13_re),  // sfix22_En15
                                        .Out13_im(alpha64pointFFTchan_out13_im),  // sfix22_En15
                                        .Out14_re(alpha64pointFFTchan_out14_re),  // sfix22_En15
                                        .Out14_im(alpha64pointFFTchan_out14_im),  // sfix22_En15
                                        .Out15_re(alpha64pointFFTchan_out15_re),  // sfix22_En15
                                        .Out15_im(alpha64pointFFTchan_out15_im),  // sfix22_En15
                                        .Out16_re(alpha64pointFFTchan_out16_re),  // sfix22_En15
                                        .Out16_im(alpha64pointFFTchan_out16_im),  // sfix22_En15
                                        .Out17_re(alpha64pointFFTchan_out17_re),  // sfix22_En15
                                        .Out17_im(alpha64pointFFTchan_out17_im),  // sfix22_En15
                                        .Out18_re(alpha64pointFFTchan_out18_re),  // sfix22_En15
                                        .Out18_im(alpha64pointFFTchan_out18_im),  // sfix22_En15
                                        .Out19_re(alpha64pointFFTchan_out19_re),  // sfix22_En15
                                        .Out19_im(alpha64pointFFTchan_out19_im),  // sfix22_En15
                                        .Out20_re(alpha64pointFFTchan_out20_re),  // sfix22_En15
                                        .Out20_im(alpha64pointFFTchan_out20_im),  // sfix22_En15
                                        .Out21_re(alpha64pointFFTchan_out21_re),  // sfix22_En15
                                        .Out21_im(alpha64pointFFTchan_out21_im),  // sfix22_En15
                                        .Out22_re(alpha64pointFFTchan_out22_re),  // sfix22_En15
                                        .Out22_im(alpha64pointFFTchan_out22_im),  // sfix22_En15
                                        .Out23_re(alpha64pointFFTchan_out23_re),  // sfix22_En15
                                        .Out23_im(alpha64pointFFTchan_out23_im),  // sfix22_En15
                                        .Out24_re(alpha64pointFFTchan_out24_re),  // sfix22_En15
                                        .Out24_im(alpha64pointFFTchan_out24_im),  // sfix22_En15
                                        .Out25_re(alpha64pointFFTchan_out25_re),  // sfix22_En15
                                        .Out25_im(alpha64pointFFTchan_out25_im),  // sfix22_En15
                                        .Out26_re(alpha64pointFFTchan_out26_re),  // sfix22_En15
                                        .Out26_im(alpha64pointFFTchan_out26_im),  // sfix22_En15
                                        .Out27_re(alpha64pointFFTchan_out27_re),  // sfix22_En15
                                        .Out27_im(alpha64pointFFTchan_out27_im),  // sfix22_En15
                                        .Out28_re(alpha64pointFFTchan_out28_re),  // sfix22_En15
                                        .Out28_im(alpha64pointFFTchan_out28_im),  // sfix22_En15
                                        .Out29_re(alpha64pointFFTchan_out29_re),  // sfix22_En15
                                        .Out29_im(alpha64pointFFTchan_out29_im),  // sfix22_En15
                                        .Out30_re(alpha64pointFFTchan_out30_re),  // sfix22_En15
                                        .Out30_im(alpha64pointFFTchan_out30_im),  // sfix22_En15
                                        .Out31_re(alpha64pointFFTchan_out31_re),  // sfix22_En15
                                        .Out31_im(alpha64pointFFTchan_out31_im),  // sfix22_En15
                                        .Out32_re(alpha64pointFFTchan_out32_re),  // sfix22_En15
                                        .Out32_im(alpha64pointFFTchan_out32_im),  // sfix22_En15
                                        .Out33_re(alpha64pointFFTchan_out33_re),  // sfix22_En15
                                        .Out33_im(alpha64pointFFTchan_out33_im),  // sfix22_En15
                                        .Out34_re(alpha64pointFFTchan_out34_re),  // sfix22_En15
                                        .Out34_im(alpha64pointFFTchan_out34_im),  // sfix22_En15
                                        .Out35_re(alpha64pointFFTchan_out35_re),  // sfix22_En15
                                        .Out35_im(alpha64pointFFTchan_out35_im),  // sfix22_En15
                                        .Out36_re(alpha64pointFFTchan_out36_re),  // sfix22_En15
                                        .Out36_im(alpha64pointFFTchan_out36_im),  // sfix22_En15
                                        .Out37_re(alpha64pointFFTchan_out37_re),  // sfix22_En15
                                        .Out37_im(alpha64pointFFTchan_out37_im),  // sfix22_En15
                                        .Out38_re(alpha64pointFFTchan_out38_re),  // sfix22_En15
                                        .Out38_im(alpha64pointFFTchan_out38_im),  // sfix22_En15
                                        .Out39_re(alpha64pointFFTchan_out39_re),  // sfix22_En15
                                        .Out39_im(alpha64pointFFTchan_out39_im),  // sfix22_En15
                                        .Out40_re(alpha64pointFFTchan_out40_re),  // sfix22_En15
                                        .Out40_im(alpha64pointFFTchan_out40_im),  // sfix22_En15
                                        .Out41_re(alpha64pointFFTchan_out41_re),  // sfix22_En15
                                        .Out41_im(alpha64pointFFTchan_out41_im),  // sfix22_En15
                                        .Out42_re(alpha64pointFFTchan_out42_re),  // sfix22_En15
                                        .Out42_im(alpha64pointFFTchan_out42_im),  // sfix22_En15
                                        .Out43_re(alpha64pointFFTchan_out43_re),  // sfix22_En15
                                        .Out43_im(alpha64pointFFTchan_out43_im),  // sfix22_En15
                                        .Out44_re(alpha64pointFFTchan_out44_re),  // sfix22_En15
                                        .Out44_im(alpha64pointFFTchan_out44_im),  // sfix22_En15
                                        .Out45_re(alpha64pointFFTchan_out45_re),  // sfix22_En15
                                        .Out45_im(alpha64pointFFTchan_out45_im),  // sfix22_En15
                                        .Out46_re(alpha64pointFFTchan_out46_re),  // sfix22_En15
                                        .Out46_im(alpha64pointFFTchan_out46_im),  // sfix22_En15
                                        .Out47_re(alpha64pointFFTchan_out47_re),  // sfix22_En15
                                        .Out47_im(alpha64pointFFTchan_out47_im),  // sfix22_En15
                                        .Out48_re(alpha64pointFFTchan_out48_re),  // sfix22_En15
                                        .Out48_im(alpha64pointFFTchan_out48_im),  // sfix22_En15
                                        .Out49_re(alpha64pointFFTchan_out49_re),  // sfix22_En15
                                        .Out49_im(alpha64pointFFTchan_out49_im),  // sfix22_En15
                                        .Out50_re(alpha64pointFFTchan_out50_re),  // sfix22_En15
                                        .Out50_im(alpha64pointFFTchan_out50_im),  // sfix22_En15
                                        .Out51_re(alpha64pointFFTchan_out51_re),  // sfix22_En15
                                        .Out51_im(alpha64pointFFTchan_out51_im),  // sfix22_En15
                                        .Out52_re(alpha64pointFFTchan_out52_re),  // sfix22_En15
                                        .Out52_im(alpha64pointFFTchan_out52_im),  // sfix22_En15
                                        .Out53_re(alpha64pointFFTchan_out53_re),  // sfix22_En15
                                        .Out53_im(alpha64pointFFTchan_out53_im),  // sfix22_En15
                                        .Out54_re(alpha64pointFFTchan_out54_re),  // sfix22_En15
                                        .Out54_im(alpha64pointFFTchan_out54_im),  // sfix22_En15
                                        .Out55_re(alpha64pointFFTchan_out55_re),  // sfix22_En15
                                        .Out55_im(alpha64pointFFTchan_out55_im),  // sfix22_En15
                                        .Out56_re(alpha64pointFFTchan_out56_re),  // sfix22_En15
                                        .Out56_im(alpha64pointFFTchan_out56_im),  // sfix22_En15
                                        .Out57_re(alpha64pointFFTchan_out57_re),  // sfix22_En15
                                        .Out57_im(alpha64pointFFTchan_out57_im),  // sfix22_En15
                                        .Out58_re(alpha64pointFFTchan_out58_re),  // sfix22_En15
                                        .Out58_im(alpha64pointFFTchan_out58_im),  // sfix22_En15
                                        .Out59_re(alpha64pointFFTchan_out59_re),  // sfix22_En15
                                        .Out59_im(alpha64pointFFTchan_out59_im),  // sfix22_En15
                                        .Out60_re(alpha64pointFFTchan_out60_re),  // sfix22_En15
                                        .Out60_im(alpha64pointFFTchan_out60_im),  // sfix22_En15
                                        .Out61_re(alpha64pointFFTchan_out61_re),  // sfix22_En15
                                        .Out61_im(alpha64pointFFTchan_out61_im),  // sfix22_En15
                                        .Out62_re(alpha64pointFFTchan_out62_re),  // sfix22_En15
                                        .Out62_im(alpha64pointFFTchan_out62_im),  // sfix22_En15
                                        .Out63_re(alpha64pointFFTchan_out63_re),  // sfix22_En15
                                        .Out63_im(alpha64pointFFTchan_out63_im),  // sfix22_En15
                                        .Out64_re(alpha64pointFFTchan_out64_re),  // sfix22_En15
                                        .Out64_im(alpha64pointFFTchan_out64_im)  // sfix22_En15
                                        );

  assign Multiport_Switch1_out1_re = (whichBin == 8'b00000000 ? alpha64pointFFTchan_out1_re :
              (whichBin == 8'b00000001 ? alpha64pointFFTchan_out2_re :
              (whichBin == 8'b00000010 ? alpha64pointFFTchan_out3_re :
              (whichBin == 8'b00000011 ? alpha64pointFFTchan_out4_re :
              (whichBin == 8'b00000100 ? alpha64pointFFTchan_out5_re :
              (whichBin == 8'b00000101 ? alpha64pointFFTchan_out6_re :
              (whichBin == 8'b00000110 ? alpha64pointFFTchan_out7_re :
              (whichBin == 8'b00000111 ? alpha64pointFFTchan_out8_re :
              (whichBin == 8'b00001000 ? alpha64pointFFTchan_out9_re :
              (whichBin == 8'b00001001 ? alpha64pointFFTchan_out10_re :
              (whichBin == 8'b00001010 ? alpha64pointFFTchan_out11_re :
              (whichBin == 8'b00001011 ? alpha64pointFFTchan_out12_re :
              (whichBin == 8'b00001100 ? alpha64pointFFTchan_out13_re :
              (whichBin == 8'b00001101 ? alpha64pointFFTchan_out14_re :
              (whichBin == 8'b00001110 ? alpha64pointFFTchan_out15_re :
              (whichBin == 8'b00001111 ? alpha64pointFFTchan_out16_re :
              (whichBin == 8'b00010000 ? alpha64pointFFTchan_out17_re :
              (whichBin == 8'b00010001 ? alpha64pointFFTchan_out18_re :
              (whichBin == 8'b00010010 ? alpha64pointFFTchan_out19_re :
              (whichBin == 8'b00010011 ? alpha64pointFFTchan_out20_re :
              (whichBin == 8'b00010100 ? alpha64pointFFTchan_out21_re :
              (whichBin == 8'b00010101 ? alpha64pointFFTchan_out22_re :
              (whichBin == 8'b00010110 ? alpha64pointFFTchan_out23_re :
              (whichBin == 8'b00010111 ? alpha64pointFFTchan_out24_re :
              (whichBin == 8'b00011000 ? alpha64pointFFTchan_out25_re :
              (whichBin == 8'b00011001 ? alpha64pointFFTchan_out26_re :
              (whichBin == 8'b00011010 ? alpha64pointFFTchan_out27_re :
              (whichBin == 8'b00011011 ? alpha64pointFFTchan_out28_re :
              (whichBin == 8'b00011100 ? alpha64pointFFTchan_out29_re :
              (whichBin == 8'b00011101 ? alpha64pointFFTchan_out30_re :
              (whichBin == 8'b00011110 ? alpha64pointFFTchan_out31_re :
              (whichBin == 8'b00011111 ? alpha64pointFFTchan_out32_re :
              (whichBin == 8'b00100000 ? alpha64pointFFTchan_out33_re :
              (whichBin == 8'b00100001 ? alpha64pointFFTchan_out34_re :
              (whichBin == 8'b00100010 ? alpha64pointFFTchan_out35_re :
              (whichBin == 8'b00100011 ? alpha64pointFFTchan_out36_re :
              (whichBin == 8'b00100100 ? alpha64pointFFTchan_out37_re :
              (whichBin == 8'b00100101 ? alpha64pointFFTchan_out38_re :
              (whichBin == 8'b00100110 ? alpha64pointFFTchan_out39_re :
              (whichBin == 8'b00100111 ? alpha64pointFFTchan_out40_re :
              (whichBin == 8'b00101000 ? alpha64pointFFTchan_out41_re :
              (whichBin == 8'b00101001 ? alpha64pointFFTchan_out42_re :
              (whichBin == 8'b00101010 ? alpha64pointFFTchan_out43_re :
              (whichBin == 8'b00101011 ? alpha64pointFFTchan_out44_re :
              (whichBin == 8'b00101100 ? alpha64pointFFTchan_out45_re :
              (whichBin == 8'b00101101 ? alpha64pointFFTchan_out46_re :
              (whichBin == 8'b00101110 ? alpha64pointFFTchan_out47_re :
              (whichBin == 8'b00101111 ? alpha64pointFFTchan_out48_re :
              (whichBin == 8'b00110000 ? alpha64pointFFTchan_out49_re :
              (whichBin == 8'b00110001 ? alpha64pointFFTchan_out50_re :
              (whichBin == 8'b00110010 ? alpha64pointFFTchan_out51_re :
              (whichBin == 8'b00110011 ? alpha64pointFFTchan_out52_re :
              (whichBin == 8'b00110100 ? alpha64pointFFTchan_out53_re :
              (whichBin == 8'b00110101 ? alpha64pointFFTchan_out54_re :
              (whichBin == 8'b00110110 ? alpha64pointFFTchan_out55_re :
              (whichBin == 8'b00110111 ? alpha64pointFFTchan_out56_re :
              (whichBin == 8'b00111000 ? alpha64pointFFTchan_out57_re :
              (whichBin == 8'b00111001 ? alpha64pointFFTchan_out58_re :
              (whichBin == 8'b00111010 ? alpha64pointFFTchan_out59_re :
              (whichBin == 8'b00111011 ? alpha64pointFFTchan_out60_re :
              (whichBin == 8'b00111100 ? alpha64pointFFTchan_out61_re :
              (whichBin == 8'b00111101 ? alpha64pointFFTchan_out62_re :
              (whichBin == 8'b00111110 ? alpha64pointFFTchan_out63_re :
              alpha64pointFFTchan_out64_re)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));
  assign Multiport_Switch1_out1_im = (whichBin == 8'b00000000 ? alpha64pointFFTchan_out1_im :
              (whichBin == 8'b00000001 ? alpha64pointFFTchan_out2_im :
              (whichBin == 8'b00000010 ? alpha64pointFFTchan_out3_im :
              (whichBin == 8'b00000011 ? alpha64pointFFTchan_out4_im :
              (whichBin == 8'b00000100 ? alpha64pointFFTchan_out5_im :
              (whichBin == 8'b00000101 ? alpha64pointFFTchan_out6_im :
              (whichBin == 8'b00000110 ? alpha64pointFFTchan_out7_im :
              (whichBin == 8'b00000111 ? alpha64pointFFTchan_out8_im :
              (whichBin == 8'b00001000 ? alpha64pointFFTchan_out9_im :
              (whichBin == 8'b00001001 ? alpha64pointFFTchan_out10_im :
              (whichBin == 8'b00001010 ? alpha64pointFFTchan_out11_im :
              (whichBin == 8'b00001011 ? alpha64pointFFTchan_out12_im :
              (whichBin == 8'b00001100 ? alpha64pointFFTchan_out13_im :
              (whichBin == 8'b00001101 ? alpha64pointFFTchan_out14_im :
              (whichBin == 8'b00001110 ? alpha64pointFFTchan_out15_im :
              (whichBin == 8'b00001111 ? alpha64pointFFTchan_out16_im :
              (whichBin == 8'b00010000 ? alpha64pointFFTchan_out17_im :
              (whichBin == 8'b00010001 ? alpha64pointFFTchan_out18_im :
              (whichBin == 8'b00010010 ? alpha64pointFFTchan_out19_im :
              (whichBin == 8'b00010011 ? alpha64pointFFTchan_out20_im :
              (whichBin == 8'b00010100 ? alpha64pointFFTchan_out21_im :
              (whichBin == 8'b00010101 ? alpha64pointFFTchan_out22_im :
              (whichBin == 8'b00010110 ? alpha64pointFFTchan_out23_im :
              (whichBin == 8'b00010111 ? alpha64pointFFTchan_out24_im :
              (whichBin == 8'b00011000 ? alpha64pointFFTchan_out25_im :
              (whichBin == 8'b00011001 ? alpha64pointFFTchan_out26_im :
              (whichBin == 8'b00011010 ? alpha64pointFFTchan_out27_im :
              (whichBin == 8'b00011011 ? alpha64pointFFTchan_out28_im :
              (whichBin == 8'b00011100 ? alpha64pointFFTchan_out29_im :
              (whichBin == 8'b00011101 ? alpha64pointFFTchan_out30_im :
              (whichBin == 8'b00011110 ? alpha64pointFFTchan_out31_im :
              (whichBin == 8'b00011111 ? alpha64pointFFTchan_out32_im :
              (whichBin == 8'b00100000 ? alpha64pointFFTchan_out33_im :
              (whichBin == 8'b00100001 ? alpha64pointFFTchan_out34_im :
              (whichBin == 8'b00100010 ? alpha64pointFFTchan_out35_im :
              (whichBin == 8'b00100011 ? alpha64pointFFTchan_out36_im :
              (whichBin == 8'b00100100 ? alpha64pointFFTchan_out37_im :
              (whichBin == 8'b00100101 ? alpha64pointFFTchan_out38_im :
              (whichBin == 8'b00100110 ? alpha64pointFFTchan_out39_im :
              (whichBin == 8'b00100111 ? alpha64pointFFTchan_out40_im :
              (whichBin == 8'b00101000 ? alpha64pointFFTchan_out41_im :
              (whichBin == 8'b00101001 ? alpha64pointFFTchan_out42_im :
              (whichBin == 8'b00101010 ? alpha64pointFFTchan_out43_im :
              (whichBin == 8'b00101011 ? alpha64pointFFTchan_out44_im :
              (whichBin == 8'b00101100 ? alpha64pointFFTchan_out45_im :
              (whichBin == 8'b00101101 ? alpha64pointFFTchan_out46_im :
              (whichBin == 8'b00101110 ? alpha64pointFFTchan_out47_im :
              (whichBin == 8'b00101111 ? alpha64pointFFTchan_out48_im :
              (whichBin == 8'b00110000 ? alpha64pointFFTchan_out49_im :
              (whichBin == 8'b00110001 ? alpha64pointFFTchan_out50_im :
              (whichBin == 8'b00110010 ? alpha64pointFFTchan_out51_im :
              (whichBin == 8'b00110011 ? alpha64pointFFTchan_out52_im :
              (whichBin == 8'b00110100 ? alpha64pointFFTchan_out53_im :
              (whichBin == 8'b00110101 ? alpha64pointFFTchan_out54_im :
              (whichBin == 8'b00110110 ? alpha64pointFFTchan_out55_im :
              (whichBin == 8'b00110111 ? alpha64pointFFTchan_out56_im :
              (whichBin == 8'b00111000 ? alpha64pointFFTchan_out57_im :
              (whichBin == 8'b00111001 ? alpha64pointFFTchan_out58_im :
              (whichBin == 8'b00111010 ? alpha64pointFFTchan_out59_im :
              (whichBin == 8'b00111011 ? alpha64pointFFTchan_out60_im :
              (whichBin == 8'b00111100 ? alpha64pointFFTchan_out61_im :
              (whichBin == 8'b00111101 ? alpha64pointFFTchan_out62_im :
              (whichBin == 8'b00111110 ? alpha64pointFFTchan_out63_im :
              alpha64pointFFTchan_out64_im)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));



  assign Out1_re = Multiport_Switch1_out1_re;

  assign Out1_im = Multiport_Switch1_out1_im;

  assign ce_out = clk_enable;

endmodule  // FFT64_outMuxed

