// -------------------------------------------------------------
// 
// File Name: /home/mori/Downloads/tomori_fft/hdlsrc/fft_overlap_tomori/FFT8_1_block2.v
// Created: 2025-04-26 11:44:22
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FFT8_1_block2
// Source Path: fft_overlap_tomori/FFT64_outMuxed/64pointFFTchan/FFT64/FFT32_1/FFT16_1/FFT8_1
// Hierarchy Level: 5
// Model version: 3.27
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FFT8_1_block2
          (clk,
           reset,
           enb_1_64_0,
           In1_re,
           In1_im,
           In2_re,
           In2_im,
           In3_re,
           In3_im,
           In4_re,
           In4_im,
           In5_re,
           In5_im,
           In6_re,
           In6_im,
           In7_re,
           In7_im,
           In8_re,
           In8_im,
           x0_re,
           x0_im,
           x1_re,
           x1_im,
           x2_re,
           x2_im,
           x3_re,
           x3_im,
           x4_re,
           x4_im,
           x5_re,
           x5_im,
           x6_re,
           x6_im,
           x7_re,
           x7_im);


  input   clk;
  input   reset;
  input   enb_1_64_0;
  input   signed [15:0] In1_re;  // sfix16_En15
  input   signed [15:0] In1_im;  // sfix16_En15
  input   signed [15:0] In2_re;  // sfix16_En15
  input   signed [15:0] In2_im;  // sfix16_En15
  input   signed [15:0] In3_re;  // sfix16_En15
  input   signed [15:0] In3_im;  // sfix16_En15
  input   signed [15:0] In4_re;  // sfix16_En15
  input   signed [15:0] In4_im;  // sfix16_En15
  input   signed [15:0] In5_re;  // sfix16_En15
  input   signed [15:0] In5_im;  // sfix16_En15
  input   signed [15:0] In6_re;  // sfix16_En15
  input   signed [15:0] In6_im;  // sfix16_En15
  input   signed [15:0] In7_re;  // sfix16_En15
  input   signed [15:0] In7_im;  // sfix16_En15
  input   signed [15:0] In8_re;  // sfix16_En15
  input   signed [15:0] In8_im;  // sfix16_En15
  output  signed [21:0] x0_re;  // sfix22_En15
  output  signed [21:0] x0_im;  // sfix22_En15
  output  signed [21:0] x1_re;  // sfix22_En15
  output  signed [21:0] x1_im;  // sfix22_En15
  output  signed [21:0] x2_re;  // sfix22_En15
  output  signed [21:0] x2_im;  // sfix22_En15
  output  signed [21:0] x3_re;  // sfix22_En15
  output  signed [21:0] x3_im;  // sfix22_En15
  output  signed [21:0] x4_re;  // sfix22_En15
  output  signed [21:0] x4_im;  // sfix22_En15
  output  signed [21:0] x5_re;  // sfix22_En15
  output  signed [21:0] x5_im;  // sfix22_En15
  output  signed [21:0] x6_re;  // sfix22_En15
  output  signed [21:0] x6_im;  // sfix22_En15
  output  signed [21:0] x7_re;  // sfix22_En15
  output  signed [21:0] x7_im;  // sfix22_En15


  wire signed [31:0] Add_add_cast;  // sfix32_En15
  wire signed [31:0] Add_add_cast_1;  // sfix32_En15
  wire signed [31:0] Add_add_temp;  // sfix32_En15
  wire signed [31:0] Add_add_cast_2;  // sfix32_En15
  wire signed [31:0] Add_add_cast_3;  // sfix32_En15
  wire signed [31:0] Add_add_temp_1;  // sfix32_En15
  wire signed [21:0] Add_out1_re;  // sfix22_En15
  wire signed [21:0] Add_out1_im;  // sfix22_En15
  reg signed [21:0] Delay_out1_re;  // sfix22_En15
  reg signed [21:0] Delay_out1_im;  // sfix22_En15
  wire signed [31:0] Add6_add_cast;  // sfix32_En15
  wire signed [31:0] Add6_add_cast_1;  // sfix32_En15
  wire signed [31:0] Add6_add_temp;  // sfix32_En15
  wire signed [31:0] Add6_add_cast_2;  // sfix32_En15
  wire signed [31:0] Add6_add_cast_3;  // sfix32_En15
  wire signed [31:0] Add6_add_temp_1;  // sfix32_En15
  wire signed [21:0] Add6_out1_re;  // sfix22_En15
  wire signed [21:0] Add6_out1_im;  // sfix22_En15
  reg signed [21:0] Delay6_out1_re;  // sfix22_En15
  reg signed [21:0] Delay6_out1_im;  // sfix22_En15
  wire signed [31:0] Add2_add_cast;  // sfix32_En15
  wire signed [31:0] Add2_add_cast_1;  // sfix32_En15
  wire signed [31:0] Add2_add_temp;  // sfix32_En15
  wire signed [31:0] Add2_add_cast_2;  // sfix32_En15
  wire signed [31:0] Add2_add_cast_3;  // sfix32_En15
  wire signed [31:0] Add2_add_temp_1;  // sfix32_En15
  wire signed [21:0] Add2_out1_re;  // sfix22_En15
  wire signed [21:0] Add2_out1_im;  // sfix22_En15
  reg signed [21:0] Delay31_reg_re [0:1];  // sfix22_En15 [2]
  reg signed [21:0] Delay31_reg_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay31_reg_next_re [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay31_reg_next_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay31_out1_re;  // sfix22_En15
  wire signed [21:0] Delay31_out1_im;  // sfix22_En15
  reg signed [21:0] Delay2_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay2_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay2_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay2_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay2_out1_re;  // sfix22_En15
  reg signed [21:0] Delay2_out1_im;  // sfix22_En15
  wire signed [31:0] Add4_add_cast;  // sfix32_En15
  wire signed [31:0] Add4_add_cast_1;  // sfix32_En15
  wire signed [31:0] Add4_add_temp;  // sfix32_En15
  wire signed [31:0] Add4_add_cast_2;  // sfix32_En15
  wire signed [31:0] Add4_add_cast_3;  // sfix32_En15
  wire signed [31:0] Add4_add_temp_1;  // sfix32_En15
  wire signed [21:0] Add4_out1_re;  // sfix22_En15
  wire signed [21:0] Add4_out1_im;  // sfix22_En15
  reg signed [21:0] Delay4_out1_re;  // sfix22_En15
  reg signed [21:0] Delay4_out1_im;  // sfix22_En15
  wire signed [31:0] Add8_add_cast;  // sfix32_En15
  wire signed [31:0] Add8_add_cast_1;  // sfix32_En15
  wire signed [31:0] Add8_add_temp;  // sfix32_En15
  wire signed [31:0] Add8_add_cast_2;  // sfix32_En15
  wire signed [31:0] Add8_add_cast_3;  // sfix32_En15
  wire signed [31:0] Add8_add_temp_1;  // sfix32_En15
  wire signed [21:0] Add8_out1_re;  // sfix22_En15
  wire signed [21:0] Add8_out1_im;  // sfix22_En15
  reg signed [21:0] Delay8_out1_re;  // sfix22_En15
  reg signed [21:0] Delay8_out1_im;  // sfix22_En15
  wire signed [31:0] Add10_add_cast;  // sfix32_En15
  wire signed [31:0] Add10_add_cast_1;  // sfix32_En15
  wire signed [31:0] Add10_add_temp;  // sfix32_En15
  wire signed [31:0] Add10_add_cast_2;  // sfix32_En15
  wire signed [31:0] Add10_add_cast_3;  // sfix32_En15
  wire signed [31:0] Add10_add_temp_1;  // sfix32_En15
  wire signed [21:0] Add10_out1_re;  // sfix22_En15
  wire signed [21:0] Add10_out1_im;  // sfix22_En15
  reg signed [21:0] Delay29_reg_re [0:1];  // sfix22_En15 [2]
  reg signed [21:0] Delay29_reg_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay29_reg_next_re [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay29_reg_next_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay29_out1_re;  // sfix22_En15
  wire signed [21:0] Delay29_out1_im;  // sfix22_En15
  reg signed [21:0] Delay10_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay10_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay10_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay10_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay10_out1_re;  // sfix22_En15
  reg signed [21:0] Delay10_out1_im;  // sfix22_En15
  wire signed [31:0] Add22_add_cast;  // sfix32_En15
  wire signed [31:0] Add22_add_cast_1;  // sfix32_En15
  wire signed [31:0] Add22_add_temp;  // sfix32_En15
  wire signed [31:0] Add22_add_cast_2;  // sfix32_En15
  wire signed [31:0] Add22_add_cast_3;  // sfix32_En15
  wire signed [31:0] Add22_add_temp_1;  // sfix32_En15
  wire signed [21:0] Add22_out1_re;  // sfix22_En15
  wire signed [21:0] Add22_out1_im;  // sfix22_En15
  reg signed [21:0] Delay12_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay12_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay12_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay12_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay12_out1_re;  // sfix22_En15
  reg signed [21:0] Delay12_out1_im;  // sfix22_En15
  wire signed [31:0] Add1_sub_cast;  // sfix32_En15
  wire signed [31:0] Add1_sub_cast_1;  // sfix32_En15
  wire signed [31:0] Add1_sub_temp;  // sfix32_En15
  wire signed [31:0] Add1_sub_cast_2;  // sfix32_En15
  wire signed [31:0] Add1_sub_cast_3;  // sfix32_En15
  wire signed [31:0] Add1_sub_temp_1;  // sfix32_En15
  wire signed [21:0] Add1_out1_re;  // sfix22_En15
  wire signed [21:0] Add1_out1_im;  // sfix22_En15
  reg signed [21:0] Delay1_out1_re;  // sfix22_En15
  reg signed [21:0] Delay1_out1_im;  // sfix22_En15
  wire signed [31:0] Add7_sub_cast;  // sfix32_En15
  wire signed [31:0] Add7_sub_cast_1;  // sfix32_En15
  wire signed [31:0] Add7_sub_temp;  // sfix32_En15
  wire signed [31:0] Add7_sub_cast_2;  // sfix32_En15
  wire signed [31:0] Add7_sub_cast_3;  // sfix32_En15
  wire signed [31:0] Add7_sub_temp_1;  // sfix32_En15
  wire signed [21:0] Add7_out1_re;  // sfix22_En15
  wire signed [21:0] Add7_out1_im;  // sfix22_En15
  wire signed [21:0] multByMinusJ_out1_re;  // sfix22_En15
  wire signed [21:0] multByMinusJ_out1_im;  // sfix22_En15
  reg signed [21:0] Delay7_out1_re;  // sfix22_En15
  reg signed [21:0] Delay7_out1_im;  // sfix22_En15
  wire signed [31:0] Add14_add_cast;  // sfix32_En15
  wire signed [31:0] Add14_add_cast_1;  // sfix32_En15
  wire signed [31:0] Add14_add_temp;  // sfix32_En15
  wire signed [31:0] Add14_add_cast_2;  // sfix32_En15
  wire signed [31:0] Add14_add_cast_3;  // sfix32_En15
  wire signed [31:0] Add14_add_temp_1;  // sfix32_En15
  wire signed [21:0] Add14_out1_re;  // sfix22_En15
  wire signed [21:0] Add14_out1_im;  // sfix22_En15
  reg signed [21:0] Delay27_reg_re [0:1];  // sfix22_En15 [2]
  reg signed [21:0] Delay27_reg_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay27_reg_next_re [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay27_reg_next_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay27_out1_re;  // sfix22_En15
  wire signed [21:0] Delay27_out1_im;  // sfix22_En15
  reg signed [21:0] Delay14_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay14_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay14_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay14_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay14_out1_re;  // sfix22_En15
  reg signed [21:0] Delay14_out1_im;  // sfix22_En15
  wire signed [31:0] Add5_sub_cast;  // sfix32_En15
  wire signed [31:0] Add5_sub_cast_1;  // sfix32_En15
  wire signed [31:0] Add5_sub_temp;  // sfix32_En15
  wire signed [31:0] Add5_sub_cast_2;  // sfix32_En15
  wire signed [31:0] Add5_sub_cast_3;  // sfix32_En15
  wire signed [31:0] Add5_sub_temp_1;  // sfix32_En15
  wire signed [21:0] Add5_out1_re;  // sfix22_En15
  wire signed [21:0] Add5_out1_im;  // sfix22_En15
  reg signed [21:0] Delay5_out1_re;  // sfix22_En15
  reg signed [21:0] Delay5_out1_im;  // sfix22_En15
  wire signed [31:0] Add9_sub_cast;  // sfix32_En15
  wire signed [31:0] Add9_sub_cast_1;  // sfix32_En15
  wire signed [31:0] Add9_sub_temp;  // sfix32_En15
  wire signed [31:0] Add9_sub_cast_2;  // sfix32_En15
  wire signed [31:0] Add9_sub_cast_3;  // sfix32_En15
  wire signed [31:0] Add9_sub_temp_1;  // sfix32_En15
  wire signed [21:0] Add9_out1_re;  // sfix22_En15
  wire signed [21:0] Add9_out1_im;  // sfix22_En15
  wire signed [21:0] multByMinusJ1_out1_re;  // sfix22_En15
  wire signed [21:0] multByMinusJ1_out1_im;  // sfix22_En15
  reg signed [21:0] Delay9_out1_re;  // sfix22_En15
  reg signed [21:0] Delay9_out1_im;  // sfix22_En15
  wire signed [31:0] Add16_add_cast;  // sfix32_En15
  wire signed [31:0] Add16_add_cast_1;  // sfix32_En15
  wire signed [31:0] Add16_add_temp;  // sfix32_En15
  wire signed [31:0] Add16_add_cast_2;  // sfix32_En15
  wire signed [31:0] Add16_add_cast_3;  // sfix32_En15
  wire signed [31:0] Add16_add_temp_1;  // sfix32_En15
  wire signed [21:0] Add16_out1_re;  // sfix22_En15
  wire signed [21:0] Add16_out1_im;  // sfix22_En15
  reg signed [21:0] Delay25_reg_re [0:1];  // sfix22_En15 [2]
  reg signed [21:0] Delay25_reg_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay25_reg_next_re [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay25_reg_next_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay25_out1_re;  // sfix22_En15
  wire signed [21:0] Delay25_out1_im;  // sfix22_En15
  wire signed [21:0] multByExp_j_Pi_4_out1_re;  // sfix22_En15
  wire signed [21:0] multByExp_j_Pi_4_out1_im;  // sfix22_En15
  reg signed [21:0] Delay16_out1_re;  // sfix22_En15
  reg signed [21:0] Delay16_out1_im;  // sfix22_En15
  wire signed [31:0] Add18_add_cast;  // sfix32_En15
  wire signed [31:0] Add18_add_cast_1;  // sfix32_En15
  wire signed [31:0] Add18_add_temp;  // sfix32_En15
  wire signed [31:0] Add18_add_cast_2;  // sfix32_En15
  wire signed [31:0] Add18_add_cast_3;  // sfix32_En15
  wire signed [31:0] Add18_add_temp_1;  // sfix32_En15
  wire signed [21:0] Add18_out1_re;  // sfix22_En15
  wire signed [21:0] Add18_out1_im;  // sfix22_En15
  reg signed [21:0] Delay20_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay20_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay20_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay20_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay20_out1_re;  // sfix22_En15
  reg signed [21:0] Delay20_out1_im;  // sfix22_En15
  wire signed [31:0] Add3_sub_cast;  // sfix32_En15
  wire signed [31:0] Add3_sub_cast_1;  // sfix32_En15
  wire signed [31:0] Add3_sub_temp;  // sfix32_En15
  wire signed [31:0] Add3_sub_cast_2;  // sfix32_En15
  wire signed [31:0] Add3_sub_cast_3;  // sfix32_En15
  wire signed [31:0] Add3_sub_temp_1;  // sfix32_En15
  wire signed [21:0] Add3_out1_re;  // sfix22_En15
  wire signed [21:0] Add3_out1_im;  // sfix22_En15
  reg signed [21:0] Delay30_reg_re [0:1];  // sfix22_En15 [2]
  reg signed [21:0] Delay30_reg_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay30_reg_next_re [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay30_reg_next_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay30_out1_re;  // sfix22_En15
  wire signed [21:0] Delay30_out1_im;  // sfix22_En15
  reg signed [21:0] Delay3_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay3_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay3_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay3_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay3_out1_re;  // sfix22_En15
  reg signed [21:0] Delay3_out1_im;  // sfix22_En15
  wire signed [31:0] Add11_sub_cast;  // sfix32_En15
  wire signed [31:0] Add11_sub_cast_1;  // sfix32_En15
  wire signed [31:0] Add11_sub_temp;  // sfix32_En15
  wire signed [31:0] Add11_sub_cast_2;  // sfix32_En15
  wire signed [31:0] Add11_sub_cast_3;  // sfix32_En15
  wire signed [31:0] Add11_sub_temp_1;  // sfix32_En15
  wire signed [21:0] Add11_out1_re;  // sfix22_En15
  wire signed [21:0] Add11_out1_im;  // sfix22_En15
  reg signed [21:0] Delay28_reg_re [0:1];  // sfix22_En15 [2]
  reg signed [21:0] Delay28_reg_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay28_reg_next_re [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay28_reg_next_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay28_out1_re;  // sfix22_En15
  wire signed [21:0] Delay28_out1_im;  // sfix22_En15
  wire signed [21:0] multByMinusJ2_out1_re;  // sfix22_En15
  wire signed [21:0] multByMinusJ2_out1_im;  // sfix22_En15
  reg signed [21:0] Delay11_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay11_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay11_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay11_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay11_out1_re;  // sfix22_En15
  reg signed [21:0] Delay11_out1_im;  // sfix22_En15
  wire signed [31:0] Add12_add_cast;  // sfix32_En15
  wire signed [31:0] Add12_add_cast_1;  // sfix32_En15
  wire signed [31:0] Add12_add_temp;  // sfix32_En15
  wire signed [31:0] Add12_add_cast_2;  // sfix32_En15
  wire signed [31:0] Add12_add_cast_3;  // sfix32_En15
  wire signed [31:0] Add12_add_temp_1;  // sfix32_En15
  wire signed [21:0] Add12_out1_re;  // sfix22_En15
  wire signed [21:0] Add12_out1_im;  // sfix22_En15
  reg signed [21:0] Delay18_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay18_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay18_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay18_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay18_out1_re;  // sfix22_En15
  reg signed [21:0] Delay18_out1_im;  // sfix22_En15
  wire signed [31:0] Add15_sub_cast;  // sfix32_En15
  wire signed [31:0] Add15_sub_cast_1;  // sfix32_En15
  wire signed [31:0] Add15_sub_temp;  // sfix32_En15
  wire signed [31:0] Add15_sub_cast_2;  // sfix32_En15
  wire signed [31:0] Add15_sub_cast_3;  // sfix32_En15
  wire signed [31:0] Add15_sub_temp_1;  // sfix32_En15
  wire signed [21:0] Add15_out1_re;  // sfix22_En15
  wire signed [21:0] Add15_out1_im;  // sfix22_En15
  reg signed [21:0] Delay26_reg_re [0:1];  // sfix22_En15 [2]
  reg signed [21:0] Delay26_reg_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay26_reg_next_re [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay26_reg_next_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay26_out1_re;  // sfix22_En15
  wire signed [21:0] Delay26_out1_im;  // sfix22_En15
  reg signed [21:0] Delay15_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay15_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay15_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay15_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay15_out1_re;  // sfix22_En15
  reg signed [21:0] Delay15_out1_im;  // sfix22_En15
  wire signed [31:0] Add17_sub_cast;  // sfix32_En15
  wire signed [31:0] Add17_sub_cast_1;  // sfix32_En15
  wire signed [31:0] Add17_sub_temp;  // sfix32_En15
  wire signed [31:0] Add17_sub_cast_2;  // sfix32_En15
  wire signed [31:0] Add17_sub_cast_3;  // sfix32_En15
  wire signed [31:0] Add17_sub_temp_1;  // sfix32_En15
  wire signed [21:0] Add17_out1_re;  // sfix22_En15
  wire signed [21:0] Add17_out1_im;  // sfix22_En15
  reg signed [21:0] Delay24_reg_re [0:1];  // sfix22_En15 [2]
  reg signed [21:0] Delay24_reg_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay24_reg_next_re [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay24_reg_next_im [0:1];  // sfix22_En15 [2]
  wire signed [21:0] Delay24_out1_re;  // sfix22_En15
  wire signed [21:0] Delay24_out1_im;  // sfix22_En15
  wire signed [21:0] multByExp_j_Pi_4_1_out1_re;  // sfix22_En15
  wire signed [21:0] multByExp_j_Pi_4_1_out1_im;  // sfix22_En15
  wire signed [21:0] multByMinusJ3_out1_re;  // sfix22_En15
  wire signed [21:0] multByMinusJ3_out1_im;  // sfix22_En15
  reg signed [21:0] Delay17_out1_re;  // sfix22_En15
  reg signed [21:0] Delay17_out1_im;  // sfix22_En15
  wire signed [31:0] Add20_add_cast;  // sfix32_En15
  wire signed [31:0] Add20_add_cast_1;  // sfix32_En15
  wire signed [31:0] Add20_add_temp;  // sfix32_En15
  wire signed [31:0] Add20_add_cast_2;  // sfix32_En15
  wire signed [31:0] Add20_add_cast_3;  // sfix32_En15
  wire signed [31:0] Add20_add_temp_1;  // sfix32_En15
  wire signed [21:0] Add20_out1_re;  // sfix22_En15
  wire signed [21:0] Add20_out1_im;  // sfix22_En15
  reg signed [21:0] Delay22_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay22_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay22_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay22_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay22_out1_re;  // sfix22_En15
  reg signed [21:0] Delay22_out1_im;  // sfix22_En15
  wire signed [31:0] Add23_sub_cast;  // sfix32_En15
  wire signed [31:0] Add23_sub_cast_1;  // sfix32_En15
  wire signed [31:0] Add23_sub_temp;  // sfix32_En15
  wire signed [31:0] Add23_sub_cast_2;  // sfix32_En15
  wire signed [31:0] Add23_sub_cast_3;  // sfix32_En15
  wire signed [31:0] Add23_sub_temp_1;  // sfix32_En15
  wire signed [21:0] Add23_out1_re;  // sfix22_En15
  wire signed [21:0] Add23_out1_im;  // sfix22_En15
  reg signed [21:0] Delay13_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay13_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay13_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay13_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay13_out1_re;  // sfix22_En15
  reg signed [21:0] Delay13_out1_im;  // sfix22_En15
  wire signed [31:0] Add19_sub_cast;  // sfix32_En15
  wire signed [31:0] Add19_sub_cast_1;  // sfix32_En15
  wire signed [31:0] Add19_sub_temp;  // sfix32_En15
  wire signed [31:0] Add19_sub_cast_2;  // sfix32_En15
  wire signed [31:0] Add19_sub_cast_3;  // sfix32_En15
  wire signed [31:0] Add19_sub_temp_1;  // sfix32_En15
  wire signed [21:0] Add19_out1_re;  // sfix22_En15
  wire signed [21:0] Add19_out1_im;  // sfix22_En15
  reg signed [21:0] Delay21_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay21_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay21_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay21_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay21_out1_re;  // sfix22_En15
  reg signed [21:0] Delay21_out1_im;  // sfix22_En15
  wire signed [31:0] Add13_sub_cast;  // sfix32_En15
  wire signed [31:0] Add13_sub_cast_1;  // sfix32_En15
  wire signed [31:0] Add13_sub_temp;  // sfix32_En15
  wire signed [31:0] Add13_sub_cast_2;  // sfix32_En15
  wire signed [31:0] Add13_sub_cast_3;  // sfix32_En15
  wire signed [31:0] Add13_sub_temp_1;  // sfix32_En15
  wire signed [21:0] Add13_out1_re;  // sfix22_En15
  wire signed [21:0] Add13_out1_im;  // sfix22_En15
  reg signed [21:0] Delay19_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay19_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay19_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay19_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay19_out1_re;  // sfix22_En15
  reg signed [21:0] Delay19_out1_im;  // sfix22_En15
  wire signed [31:0] Add21_sub_cast;  // sfix32_En15
  wire signed [31:0] Add21_sub_cast_1;  // sfix32_En15
  wire signed [31:0] Add21_sub_temp;  // sfix32_En15
  wire signed [31:0] Add21_sub_cast_2;  // sfix32_En15
  wire signed [31:0] Add21_sub_cast_3;  // sfix32_En15
  wire signed [31:0] Add21_sub_temp_1;  // sfix32_En15
  wire signed [21:0] Add21_out1_re;  // sfix22_En15
  wire signed [21:0] Add21_out1_im;  // sfix22_En15
  reg signed [21:0] Delay23_reg_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay23_reg_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay23_reg_next_re [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay23_reg_next_im [0:2];  // sfix22_En15 [3]
  reg signed [21:0] Delay23_out1_re;  // sfix22_En15
  reg signed [21:0] Delay23_out1_im;  // sfix22_En15
  reg signed [31:0] Delay31_t_0_0;  // int32
  reg signed [31:0] Delay31_t_1;  // int32
  reg signed [31:0] Delay2_t_0_0;  // int32
  reg signed [31:0] Delay2_t_0_1;  // int32
  reg signed [31:0] Delay2_t_1;  // int32
  reg signed [31:0] Delay29_t_0_0;  // int32
  reg signed [31:0] Delay29_t_1;  // int32
  reg signed [31:0] Delay10_t_0_0;  // int32
  reg signed [31:0] Delay10_t_0_1;  // int32
  reg signed [31:0] Delay10_t_1;  // int32
  reg signed [31:0] Delay12_t_0_0;  // int32
  reg signed [31:0] Delay12_t_0_1;  // int32
  reg signed [31:0] Delay12_t_1;  // int32
  reg signed [31:0] Delay27_t_0_0;  // int32
  reg signed [31:0] Delay27_t_1;  // int32
  reg signed [31:0] Delay14_t_0_0;  // int32
  reg signed [31:0] Delay14_t_0_1;  // int32
  reg signed [31:0] Delay14_t_1;  // int32
  reg signed [31:0] Delay25_t_0_0;  // int32
  reg signed [31:0] Delay25_t_1;  // int32
  reg signed [31:0] Delay20_t_0_0;  // int32
  reg signed [31:0] Delay20_t_0_1;  // int32
  reg signed [31:0] Delay20_t_1;  // int32
  reg signed [31:0] Delay30_t_0_0;  // int32
  reg signed [31:0] Delay30_t_1;  // int32
  reg signed [31:0] Delay3_t_0_0;  // int32
  reg signed [31:0] Delay3_t_0_1;  // int32
  reg signed [31:0] Delay3_t_1;  // int32
  reg signed [31:0] Delay28_t_0_0;  // int32
  reg signed [31:0] Delay28_t_1;  // int32
  reg signed [31:0] Delay11_t_0_0;  // int32
  reg signed [31:0] Delay11_t_0_1;  // int32
  reg signed [31:0] Delay11_t_1;  // int32
  reg signed [31:0] Delay18_t_0_0;  // int32
  reg signed [31:0] Delay18_t_0_1;  // int32
  reg signed [31:0] Delay18_t_1;  // int32
  reg signed [31:0] Delay26_t_0_0;  // int32
  reg signed [31:0] Delay26_t_1;  // int32
  reg signed [31:0] Delay15_t_0_0;  // int32
  reg signed [31:0] Delay15_t_0_1;  // int32
  reg signed [31:0] Delay15_t_1;  // int32
  reg signed [31:0] Delay24_t_0_0;  // int32
  reg signed [31:0] Delay24_t_1;  // int32
  reg signed [31:0] Delay22_t_0_0;  // int32
  reg signed [31:0] Delay22_t_0_1;  // int32
  reg signed [31:0] Delay22_t_1;  // int32
  reg signed [31:0] Delay13_t_0_0;  // int32
  reg signed [31:0] Delay13_t_0_1;  // int32
  reg signed [31:0] Delay13_t_1;  // int32
  reg signed [31:0] Delay21_t_0_0;  // int32
  reg signed [31:0] Delay21_t_0_1;  // int32
  reg signed [31:0] Delay21_t_1;  // int32
  reg signed [31:0] Delay19_t_0_0;  // int32
  reg signed [31:0] Delay19_t_0_1;  // int32
  reg signed [31:0] Delay19_t_1;  // int32
  reg signed [31:0] Delay23_t_0_0;  // int32
  reg signed [31:0] Delay23_t_0_1;  // int32
  reg signed [31:0] Delay23_t_1;  // int32


  assign Add_add_cast = {{16{In1_re[15]}}, In1_re};
  assign Add_add_cast_1 = {{16{In5_re[15]}}, In5_re};
  assign Add_add_temp = Add_add_cast + Add_add_cast_1;
  assign Add_out1_re = Add_add_temp[21:0];
  assign Add_add_cast_2 = {{16{In1_im[15]}}, In1_im};
  assign Add_add_cast_3 = {{16{In5_im[15]}}, In5_im};
  assign Add_add_temp_1 = Add_add_cast_2 + Add_add_cast_3;
  assign Add_out1_im = Add_add_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1_re <= 22'sb0000000000000000000000;
        Delay_out1_im <= 22'sb0000000000000000000000;
      end
      else begin
        if (enb_1_64_0) begin
          Delay_out1_re <= Add_out1_re;
          Delay_out1_im <= Add_out1_im;
        end
      end
    end



  assign Add6_add_cast = {{16{In3_re[15]}}, In3_re};
  assign Add6_add_cast_1 = {{16{In7_re[15]}}, In7_re};
  assign Add6_add_temp = Add6_add_cast + Add6_add_cast_1;
  assign Add6_out1_re = Add6_add_temp[21:0];
  assign Add6_add_cast_2 = {{16{In3_im[15]}}, In3_im};
  assign Add6_add_cast_3 = {{16{In7_im[15]}}, In7_im};
  assign Add6_add_temp_1 = Add6_add_cast_2 + Add6_add_cast_3;
  assign Add6_out1_im = Add6_add_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay6_process
      if (reset == 1'b1) begin
        Delay6_out1_re <= 22'sb0000000000000000000000;
        Delay6_out1_im <= 22'sb0000000000000000000000;
      end
      else begin
        if (enb_1_64_0) begin
          Delay6_out1_re <= Add6_out1_re;
          Delay6_out1_im <= Add6_out1_im;
        end
      end
    end



  assign Add2_add_cast = {{10{Delay_out1_re[21]}}, Delay_out1_re};
  assign Add2_add_cast_1 = {{10{Delay6_out1_re[21]}}, Delay6_out1_re};
  assign Add2_add_temp = Add2_add_cast + Add2_add_cast_1;
  assign Add2_out1_re = Add2_add_temp[21:0];
  assign Add2_add_cast_2 = {{10{Delay_out1_im[21]}}, Delay_out1_im};
  assign Add2_add_cast_3 = {{10{Delay6_out1_im[21]}}, Delay6_out1_im};
  assign Add2_add_temp_1 = Add2_add_cast_2 + Add2_add_cast_3;
  assign Add2_out1_im = Add2_add_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay31_process
      if (reset == 1'b1) begin
        for(Delay31_t_1 = 32'sd0; Delay31_t_1 <= 32'sd1; Delay31_t_1 = Delay31_t_1 + 32'sd1) begin
          Delay31_reg_re[Delay31_t_1] <= 22'sb0000000000000000000000;
          Delay31_reg_im[Delay31_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay31_t_0_0 = 32'sd0; Delay31_t_0_0 <= 32'sd1; Delay31_t_0_0 = Delay31_t_0_0 + 32'sd1) begin
            Delay31_reg_re[Delay31_t_0_0] <= Delay31_reg_next_re[Delay31_t_0_0];
            Delay31_reg_im[Delay31_t_0_0] <= Delay31_reg_next_im[Delay31_t_0_0];
          end
        end
      end
    end

  assign Delay31_out1_re = Delay31_reg_re[1];
  assign Delay31_out1_im = Delay31_reg_im[1];
  assign Delay31_reg_next_re[0] = Add2_out1_re;
  assign Delay31_reg_next_im[0] = Add2_out1_im;
  assign Delay31_reg_next_re[1] = Delay31_reg_re[0];
  assign Delay31_reg_next_im[1] = Delay31_reg_im[0];



  always @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        for(Delay2_t_1 = 32'sd0; Delay2_t_1 <= 32'sd2; Delay2_t_1 = Delay2_t_1 + 32'sd1) begin
          Delay2_reg_re[Delay2_t_1] <= 22'sb0000000000000000000000;
          Delay2_reg_im[Delay2_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay2_t_0_1 = 32'sd0; Delay2_t_0_1 <= 32'sd2; Delay2_t_0_1 = Delay2_t_0_1 + 32'sd1) begin
            Delay2_reg_re[Delay2_t_0_1] <= Delay2_reg_next_re[Delay2_t_0_1];
            Delay2_reg_im[Delay2_t_0_1] <= Delay2_reg_next_im[Delay2_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay2_out1_re = Delay2_reg_re[2];
    Delay2_out1_im = Delay2_reg_im[2];
    Delay2_reg_next_re[0] = Delay31_out1_re;
    Delay2_reg_next_im[0] = Delay31_out1_im;

    for(Delay2_t_0_0 = 32'sd0; Delay2_t_0_0 <= 32'sd1; Delay2_t_0_0 = Delay2_t_0_0 + 32'sd1) begin
      Delay2_reg_next_re[Delay2_t_0_0 + 32'sd1] = Delay2_reg_re[Delay2_t_0_0];
      Delay2_reg_next_im[Delay2_t_0_0 + 32'sd1] = Delay2_reg_im[Delay2_t_0_0];
    end

  end



  assign Add4_add_cast = {{16{In2_re[15]}}, In2_re};
  assign Add4_add_cast_1 = {{16{In6_re[15]}}, In6_re};
  assign Add4_add_temp = Add4_add_cast + Add4_add_cast_1;
  assign Add4_out1_re = Add4_add_temp[21:0];
  assign Add4_add_cast_2 = {{16{In2_im[15]}}, In2_im};
  assign Add4_add_cast_3 = {{16{In6_im[15]}}, In6_im};
  assign Add4_add_temp_1 = Add4_add_cast_2 + Add4_add_cast_3;
  assign Add4_out1_im = Add4_add_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1_re <= 22'sb0000000000000000000000;
        Delay4_out1_im <= 22'sb0000000000000000000000;
      end
      else begin
        if (enb_1_64_0) begin
          Delay4_out1_re <= Add4_out1_re;
          Delay4_out1_im <= Add4_out1_im;
        end
      end
    end



  assign Add8_add_cast = {{16{In4_re[15]}}, In4_re};
  assign Add8_add_cast_1 = {{16{In8_re[15]}}, In8_re};
  assign Add8_add_temp = Add8_add_cast + Add8_add_cast_1;
  assign Add8_out1_re = Add8_add_temp[21:0];
  assign Add8_add_cast_2 = {{16{In4_im[15]}}, In4_im};
  assign Add8_add_cast_3 = {{16{In8_im[15]}}, In8_im};
  assign Add8_add_temp_1 = Add8_add_cast_2 + Add8_add_cast_3;
  assign Add8_out1_im = Add8_add_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay8_process
      if (reset == 1'b1) begin
        Delay8_out1_re <= 22'sb0000000000000000000000;
        Delay8_out1_im <= 22'sb0000000000000000000000;
      end
      else begin
        if (enb_1_64_0) begin
          Delay8_out1_re <= Add8_out1_re;
          Delay8_out1_im <= Add8_out1_im;
        end
      end
    end



  assign Add10_add_cast = {{10{Delay4_out1_re[21]}}, Delay4_out1_re};
  assign Add10_add_cast_1 = {{10{Delay8_out1_re[21]}}, Delay8_out1_re};
  assign Add10_add_temp = Add10_add_cast + Add10_add_cast_1;
  assign Add10_out1_re = Add10_add_temp[21:0];
  assign Add10_add_cast_2 = {{10{Delay4_out1_im[21]}}, Delay4_out1_im};
  assign Add10_add_cast_3 = {{10{Delay8_out1_im[21]}}, Delay8_out1_im};
  assign Add10_add_temp_1 = Add10_add_cast_2 + Add10_add_cast_3;
  assign Add10_out1_im = Add10_add_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay29_process
      if (reset == 1'b1) begin
        for(Delay29_t_1 = 32'sd0; Delay29_t_1 <= 32'sd1; Delay29_t_1 = Delay29_t_1 + 32'sd1) begin
          Delay29_reg_re[Delay29_t_1] <= 22'sb0000000000000000000000;
          Delay29_reg_im[Delay29_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay29_t_0_0 = 32'sd0; Delay29_t_0_0 <= 32'sd1; Delay29_t_0_0 = Delay29_t_0_0 + 32'sd1) begin
            Delay29_reg_re[Delay29_t_0_0] <= Delay29_reg_next_re[Delay29_t_0_0];
            Delay29_reg_im[Delay29_t_0_0] <= Delay29_reg_next_im[Delay29_t_0_0];
          end
        end
      end
    end

  assign Delay29_out1_re = Delay29_reg_re[1];
  assign Delay29_out1_im = Delay29_reg_im[1];
  assign Delay29_reg_next_re[0] = Add10_out1_re;
  assign Delay29_reg_next_im[0] = Add10_out1_im;
  assign Delay29_reg_next_re[1] = Delay29_reg_re[0];
  assign Delay29_reg_next_im[1] = Delay29_reg_im[0];



  always @(posedge clk or posedge reset)
    begin : Delay10_process
      if (reset == 1'b1) begin
        for(Delay10_t_1 = 32'sd0; Delay10_t_1 <= 32'sd2; Delay10_t_1 = Delay10_t_1 + 32'sd1) begin
          Delay10_reg_re[Delay10_t_1] <= 22'sb0000000000000000000000;
          Delay10_reg_im[Delay10_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay10_t_0_1 = 32'sd0; Delay10_t_0_1 <= 32'sd2; Delay10_t_0_1 = Delay10_t_0_1 + 32'sd1) begin
            Delay10_reg_re[Delay10_t_0_1] <= Delay10_reg_next_re[Delay10_t_0_1];
            Delay10_reg_im[Delay10_t_0_1] <= Delay10_reg_next_im[Delay10_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay10_out1_re = Delay10_reg_re[2];
    Delay10_out1_im = Delay10_reg_im[2];
    Delay10_reg_next_re[0] = Delay29_out1_re;
    Delay10_reg_next_im[0] = Delay29_out1_im;

    for(Delay10_t_0_0 = 32'sd0; Delay10_t_0_0 <= 32'sd1; Delay10_t_0_0 = Delay10_t_0_0 + 32'sd1) begin
      Delay10_reg_next_re[Delay10_t_0_0 + 32'sd1] = Delay10_reg_re[Delay10_t_0_0];
      Delay10_reg_next_im[Delay10_t_0_0 + 32'sd1] = Delay10_reg_im[Delay10_t_0_0];
    end

  end



  assign Add22_add_cast = {{10{Delay2_out1_re[21]}}, Delay2_out1_re};
  assign Add22_add_cast_1 = {{10{Delay10_out1_re[21]}}, Delay10_out1_re};
  assign Add22_add_temp = Add22_add_cast + Add22_add_cast_1;
  assign Add22_out1_re = Add22_add_temp[21:0];
  assign Add22_add_cast_2 = {{10{Delay2_out1_im[21]}}, Delay2_out1_im};
  assign Add22_add_cast_3 = {{10{Delay10_out1_im[21]}}, Delay10_out1_im};
  assign Add22_add_temp_1 = Add22_add_cast_2 + Add22_add_cast_3;
  assign Add22_out1_im = Add22_add_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay12_process
      if (reset == 1'b1) begin
        for(Delay12_t_1 = 32'sd0; Delay12_t_1 <= 32'sd2; Delay12_t_1 = Delay12_t_1 + 32'sd1) begin
          Delay12_reg_re[Delay12_t_1] <= 22'sb0000000000000000000000;
          Delay12_reg_im[Delay12_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay12_t_0_1 = 32'sd0; Delay12_t_0_1 <= 32'sd2; Delay12_t_0_1 = Delay12_t_0_1 + 32'sd1) begin
            Delay12_reg_re[Delay12_t_0_1] <= Delay12_reg_next_re[Delay12_t_0_1];
            Delay12_reg_im[Delay12_t_0_1] <= Delay12_reg_next_im[Delay12_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay12_out1_re = Delay12_reg_re[2];
    Delay12_out1_im = Delay12_reg_im[2];
    Delay12_reg_next_re[0] = Add22_out1_re;
    Delay12_reg_next_im[0] = Add22_out1_im;

    for(Delay12_t_0_0 = 32'sd0; Delay12_t_0_0 <= 32'sd1; Delay12_t_0_0 = Delay12_t_0_0 + 32'sd1) begin
      Delay12_reg_next_re[Delay12_t_0_0 + 32'sd1] = Delay12_reg_re[Delay12_t_0_0];
      Delay12_reg_next_im[Delay12_t_0_0 + 32'sd1] = Delay12_reg_im[Delay12_t_0_0];
    end

  end



  assign x0_re = Delay12_out1_re;

  assign x0_im = Delay12_out1_im;

  assign Add1_sub_cast = {{16{In1_re[15]}}, In1_re};
  assign Add1_sub_cast_1 = {{16{In5_re[15]}}, In5_re};
  assign Add1_sub_temp = Add1_sub_cast - Add1_sub_cast_1;
  assign Add1_out1_re = Add1_sub_temp[21:0];
  assign Add1_sub_cast_2 = {{16{In1_im[15]}}, In1_im};
  assign Add1_sub_cast_3 = {{16{In5_im[15]}}, In5_im};
  assign Add1_sub_temp_1 = Add1_sub_cast_2 - Add1_sub_cast_3;
  assign Add1_out1_im = Add1_sub_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1_re <= 22'sb0000000000000000000000;
        Delay1_out1_im <= 22'sb0000000000000000000000;
      end
      else begin
        if (enb_1_64_0) begin
          Delay1_out1_re <= Add1_out1_re;
          Delay1_out1_im <= Add1_out1_im;
        end
      end
    end



  assign Add7_sub_cast = {{16{In3_re[15]}}, In3_re};
  assign Add7_sub_cast_1 = {{16{In7_re[15]}}, In7_re};
  assign Add7_sub_temp = Add7_sub_cast - Add7_sub_cast_1;
  assign Add7_out1_re = Add7_sub_temp[21:0];
  assign Add7_sub_cast_2 = {{16{In3_im[15]}}, In3_im};
  assign Add7_sub_cast_3 = {{16{In7_im[15]}}, In7_im};
  assign Add7_sub_temp_1 = Add7_sub_cast_2 - Add7_sub_cast_3;
  assign Add7_out1_im = Add7_sub_temp_1[21:0];



  multByMinusJ_block10 u_multByMinusJ (.In1_re(Add7_out1_re),  // sfix22_En15
                                       .In1_im(Add7_out1_im),  // sfix22_En15
                                       .Out1_re(multByMinusJ_out1_re),  // sfix22_En15
                                       .Out1_im(multByMinusJ_out1_im)  // sfix22_En15
                                       );

  always @(posedge clk or posedge reset)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_out1_re <= 22'sb0000000000000000000000;
        Delay7_out1_im <= 22'sb0000000000000000000000;
      end
      else begin
        if (enb_1_64_0) begin
          Delay7_out1_re <= multByMinusJ_out1_re;
          Delay7_out1_im <= multByMinusJ_out1_im;
        end
      end
    end



  assign Add14_add_cast = {{10{Delay1_out1_re[21]}}, Delay1_out1_re};
  assign Add14_add_cast_1 = {{10{Delay7_out1_re[21]}}, Delay7_out1_re};
  assign Add14_add_temp = Add14_add_cast + Add14_add_cast_1;
  assign Add14_out1_re = Add14_add_temp[21:0];
  assign Add14_add_cast_2 = {{10{Delay1_out1_im[21]}}, Delay1_out1_im};
  assign Add14_add_cast_3 = {{10{Delay7_out1_im[21]}}, Delay7_out1_im};
  assign Add14_add_temp_1 = Add14_add_cast_2 + Add14_add_cast_3;
  assign Add14_out1_im = Add14_add_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay27_process
      if (reset == 1'b1) begin
        for(Delay27_t_1 = 32'sd0; Delay27_t_1 <= 32'sd1; Delay27_t_1 = Delay27_t_1 + 32'sd1) begin
          Delay27_reg_re[Delay27_t_1] <= 22'sb0000000000000000000000;
          Delay27_reg_im[Delay27_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay27_t_0_0 = 32'sd0; Delay27_t_0_0 <= 32'sd1; Delay27_t_0_0 = Delay27_t_0_0 + 32'sd1) begin
            Delay27_reg_re[Delay27_t_0_0] <= Delay27_reg_next_re[Delay27_t_0_0];
            Delay27_reg_im[Delay27_t_0_0] <= Delay27_reg_next_im[Delay27_t_0_0];
          end
        end
      end
    end

  assign Delay27_out1_re = Delay27_reg_re[1];
  assign Delay27_out1_im = Delay27_reg_im[1];
  assign Delay27_reg_next_re[0] = Add14_out1_re;
  assign Delay27_reg_next_im[0] = Add14_out1_im;
  assign Delay27_reg_next_re[1] = Delay27_reg_re[0];
  assign Delay27_reg_next_im[1] = Delay27_reg_im[0];



  always @(posedge clk or posedge reset)
    begin : Delay14_process
      if (reset == 1'b1) begin
        for(Delay14_t_1 = 32'sd0; Delay14_t_1 <= 32'sd2; Delay14_t_1 = Delay14_t_1 + 32'sd1) begin
          Delay14_reg_re[Delay14_t_1] <= 22'sb0000000000000000000000;
          Delay14_reg_im[Delay14_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay14_t_0_1 = 32'sd0; Delay14_t_0_1 <= 32'sd2; Delay14_t_0_1 = Delay14_t_0_1 + 32'sd1) begin
            Delay14_reg_re[Delay14_t_0_1] <= Delay14_reg_next_re[Delay14_t_0_1];
            Delay14_reg_im[Delay14_t_0_1] <= Delay14_reg_next_im[Delay14_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay14_out1_re = Delay14_reg_re[2];
    Delay14_out1_im = Delay14_reg_im[2];
    Delay14_reg_next_re[0] = Delay27_out1_re;
    Delay14_reg_next_im[0] = Delay27_out1_im;

    for(Delay14_t_0_0 = 32'sd0; Delay14_t_0_0 <= 32'sd1; Delay14_t_0_0 = Delay14_t_0_0 + 32'sd1) begin
      Delay14_reg_next_re[Delay14_t_0_0 + 32'sd1] = Delay14_reg_re[Delay14_t_0_0];
      Delay14_reg_next_im[Delay14_t_0_0 + 32'sd1] = Delay14_reg_im[Delay14_t_0_0];
    end

  end



  assign Add5_sub_cast = {{16{In2_re[15]}}, In2_re};
  assign Add5_sub_cast_1 = {{16{In6_re[15]}}, In6_re};
  assign Add5_sub_temp = Add5_sub_cast - Add5_sub_cast_1;
  assign Add5_out1_re = Add5_sub_temp[21:0];
  assign Add5_sub_cast_2 = {{16{In2_im[15]}}, In2_im};
  assign Add5_sub_cast_3 = {{16{In6_im[15]}}, In6_im};
  assign Add5_sub_temp_1 = Add5_sub_cast_2 - Add5_sub_cast_3;
  assign Add5_out1_im = Add5_sub_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay5_process
      if (reset == 1'b1) begin
        Delay5_out1_re <= 22'sb0000000000000000000000;
        Delay5_out1_im <= 22'sb0000000000000000000000;
      end
      else begin
        if (enb_1_64_0) begin
          Delay5_out1_re <= Add5_out1_re;
          Delay5_out1_im <= Add5_out1_im;
        end
      end
    end



  assign Add9_sub_cast = {{16{In4_re[15]}}, In4_re};
  assign Add9_sub_cast_1 = {{16{In8_re[15]}}, In8_re};
  assign Add9_sub_temp = Add9_sub_cast - Add9_sub_cast_1;
  assign Add9_out1_re = Add9_sub_temp[21:0];
  assign Add9_sub_cast_2 = {{16{In4_im[15]}}, In4_im};
  assign Add9_sub_cast_3 = {{16{In8_im[15]}}, In8_im};
  assign Add9_sub_temp_1 = Add9_sub_cast_2 - Add9_sub_cast_3;
  assign Add9_out1_im = Add9_sub_temp_1[21:0];



  multByMinusJ1_block6 u_multByMinusJ1 (.In1_re(Add9_out1_re),  // sfix22_En15
                                        .In1_im(Add9_out1_im),  // sfix22_En15
                                        .Out1_re(multByMinusJ1_out1_re),  // sfix22_En15
                                        .Out1_im(multByMinusJ1_out1_im)  // sfix22_En15
                                        );

  always @(posedge clk or posedge reset)
    begin : Delay9_process
      if (reset == 1'b1) begin
        Delay9_out1_re <= 22'sb0000000000000000000000;
        Delay9_out1_im <= 22'sb0000000000000000000000;
      end
      else begin
        if (enb_1_64_0) begin
          Delay9_out1_re <= multByMinusJ1_out1_re;
          Delay9_out1_im <= multByMinusJ1_out1_im;
        end
      end
    end



  assign Add16_add_cast = {{10{Delay5_out1_re[21]}}, Delay5_out1_re};
  assign Add16_add_cast_1 = {{10{Delay9_out1_re[21]}}, Delay9_out1_re};
  assign Add16_add_temp = Add16_add_cast + Add16_add_cast_1;
  assign Add16_out1_re = Add16_add_temp[21:0];
  assign Add16_add_cast_2 = {{10{Delay5_out1_im[21]}}, Delay5_out1_im};
  assign Add16_add_cast_3 = {{10{Delay9_out1_im[21]}}, Delay9_out1_im};
  assign Add16_add_temp_1 = Add16_add_cast_2 + Add16_add_cast_3;
  assign Add16_out1_im = Add16_add_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay25_process
      if (reset == 1'b1) begin
        for(Delay25_t_1 = 32'sd0; Delay25_t_1 <= 32'sd1; Delay25_t_1 = Delay25_t_1 + 32'sd1) begin
          Delay25_reg_re[Delay25_t_1] <= 22'sb0000000000000000000000;
          Delay25_reg_im[Delay25_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay25_t_0_0 = 32'sd0; Delay25_t_0_0 <= 32'sd1; Delay25_t_0_0 = Delay25_t_0_0 + 32'sd1) begin
            Delay25_reg_re[Delay25_t_0_0] <= Delay25_reg_next_re[Delay25_t_0_0];
            Delay25_reg_im[Delay25_t_0_0] <= Delay25_reg_next_im[Delay25_t_0_0];
          end
        end
      end
    end

  assign Delay25_out1_re = Delay25_reg_re[1];
  assign Delay25_out1_im = Delay25_reg_im[1];
  assign Delay25_reg_next_re[0] = Add16_out1_re;
  assign Delay25_reg_next_im[0] = Add16_out1_im;
  assign Delay25_reg_next_re[1] = Delay25_reg_re[0];
  assign Delay25_reg_next_im[1] = Delay25_reg_im[0];



  alpha4_block10 u_multByExp_j_Pi_4 (.clk(clk),
                                     .reset(reset),
                                     .enb_1_64_0(enb_1_64_0),
                                     .x4_re(Delay25_out1_re),  // sfix22_En15
                                     .x4_im(Delay25_out1_im),  // sfix22_En15
                                     .Out1_re(multByExp_j_Pi_4_out1_re),  // sfix22_En15
                                     .Out1_im(multByExp_j_Pi_4_out1_im)  // sfix22_En15
                                     );

  always @(posedge clk or posedge reset)
    begin : Delay16_process
      if (reset == 1'b1) begin
        Delay16_out1_re <= 22'sb0000000000000000000000;
        Delay16_out1_im <= 22'sb0000000000000000000000;
      end
      else begin
        if (enb_1_64_0) begin
          Delay16_out1_re <= multByExp_j_Pi_4_out1_re;
          Delay16_out1_im <= multByExp_j_Pi_4_out1_im;
        end
      end
    end



  assign Add18_add_cast = {{10{Delay14_out1_re[21]}}, Delay14_out1_re};
  assign Add18_add_cast_1 = {{10{Delay16_out1_re[21]}}, Delay16_out1_re};
  assign Add18_add_temp = Add18_add_cast + Add18_add_cast_1;
  assign Add18_out1_re = Add18_add_temp[21:0];
  assign Add18_add_cast_2 = {{10{Delay14_out1_im[21]}}, Delay14_out1_im};
  assign Add18_add_cast_3 = {{10{Delay16_out1_im[21]}}, Delay16_out1_im};
  assign Add18_add_temp_1 = Add18_add_cast_2 + Add18_add_cast_3;
  assign Add18_out1_im = Add18_add_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay20_process
      if (reset == 1'b1) begin
        for(Delay20_t_1 = 32'sd0; Delay20_t_1 <= 32'sd2; Delay20_t_1 = Delay20_t_1 + 32'sd1) begin
          Delay20_reg_re[Delay20_t_1] <= 22'sb0000000000000000000000;
          Delay20_reg_im[Delay20_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay20_t_0_1 = 32'sd0; Delay20_t_0_1 <= 32'sd2; Delay20_t_0_1 = Delay20_t_0_1 + 32'sd1) begin
            Delay20_reg_re[Delay20_t_0_1] <= Delay20_reg_next_re[Delay20_t_0_1];
            Delay20_reg_im[Delay20_t_0_1] <= Delay20_reg_next_im[Delay20_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay20_out1_re = Delay20_reg_re[2];
    Delay20_out1_im = Delay20_reg_im[2];
    Delay20_reg_next_re[0] = Add18_out1_re;
    Delay20_reg_next_im[0] = Add18_out1_im;

    for(Delay20_t_0_0 = 32'sd0; Delay20_t_0_0 <= 32'sd1; Delay20_t_0_0 = Delay20_t_0_0 + 32'sd1) begin
      Delay20_reg_next_re[Delay20_t_0_0 + 32'sd1] = Delay20_reg_re[Delay20_t_0_0];
      Delay20_reg_next_im[Delay20_t_0_0 + 32'sd1] = Delay20_reg_im[Delay20_t_0_0];
    end

  end



  assign x1_re = Delay20_out1_re;

  assign x1_im = Delay20_out1_im;

  assign Add3_sub_cast = {{10{Delay_out1_re[21]}}, Delay_out1_re};
  assign Add3_sub_cast_1 = {{10{Delay6_out1_re[21]}}, Delay6_out1_re};
  assign Add3_sub_temp = Add3_sub_cast - Add3_sub_cast_1;
  assign Add3_out1_re = Add3_sub_temp[21:0];
  assign Add3_sub_cast_2 = {{10{Delay_out1_im[21]}}, Delay_out1_im};
  assign Add3_sub_cast_3 = {{10{Delay6_out1_im[21]}}, Delay6_out1_im};
  assign Add3_sub_temp_1 = Add3_sub_cast_2 - Add3_sub_cast_3;
  assign Add3_out1_im = Add3_sub_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay30_process
      if (reset == 1'b1) begin
        for(Delay30_t_1 = 32'sd0; Delay30_t_1 <= 32'sd1; Delay30_t_1 = Delay30_t_1 + 32'sd1) begin
          Delay30_reg_re[Delay30_t_1] <= 22'sb0000000000000000000000;
          Delay30_reg_im[Delay30_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay30_t_0_0 = 32'sd0; Delay30_t_0_0 <= 32'sd1; Delay30_t_0_0 = Delay30_t_0_0 + 32'sd1) begin
            Delay30_reg_re[Delay30_t_0_0] <= Delay30_reg_next_re[Delay30_t_0_0];
            Delay30_reg_im[Delay30_t_0_0] <= Delay30_reg_next_im[Delay30_t_0_0];
          end
        end
      end
    end

  assign Delay30_out1_re = Delay30_reg_re[1];
  assign Delay30_out1_im = Delay30_reg_im[1];
  assign Delay30_reg_next_re[0] = Add3_out1_re;
  assign Delay30_reg_next_im[0] = Add3_out1_im;
  assign Delay30_reg_next_re[1] = Delay30_reg_re[0];
  assign Delay30_reg_next_im[1] = Delay30_reg_im[0];



  always @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        for(Delay3_t_1 = 32'sd0; Delay3_t_1 <= 32'sd2; Delay3_t_1 = Delay3_t_1 + 32'sd1) begin
          Delay3_reg_re[Delay3_t_1] <= 22'sb0000000000000000000000;
          Delay3_reg_im[Delay3_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay3_t_0_1 = 32'sd0; Delay3_t_0_1 <= 32'sd2; Delay3_t_0_1 = Delay3_t_0_1 + 32'sd1) begin
            Delay3_reg_re[Delay3_t_0_1] <= Delay3_reg_next_re[Delay3_t_0_1];
            Delay3_reg_im[Delay3_t_0_1] <= Delay3_reg_next_im[Delay3_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay3_out1_re = Delay3_reg_re[2];
    Delay3_out1_im = Delay3_reg_im[2];
    Delay3_reg_next_re[0] = Delay30_out1_re;
    Delay3_reg_next_im[0] = Delay30_out1_im;

    for(Delay3_t_0_0 = 32'sd0; Delay3_t_0_0 <= 32'sd1; Delay3_t_0_0 = Delay3_t_0_0 + 32'sd1) begin
      Delay3_reg_next_re[Delay3_t_0_0 + 32'sd1] = Delay3_reg_re[Delay3_t_0_0];
      Delay3_reg_next_im[Delay3_t_0_0 + 32'sd1] = Delay3_reg_im[Delay3_t_0_0];
    end

  end



  assign Add11_sub_cast = {{10{Delay4_out1_re[21]}}, Delay4_out1_re};
  assign Add11_sub_cast_1 = {{10{Delay8_out1_re[21]}}, Delay8_out1_re};
  assign Add11_sub_temp = Add11_sub_cast - Add11_sub_cast_1;
  assign Add11_out1_re = Add11_sub_temp[21:0];
  assign Add11_sub_cast_2 = {{10{Delay4_out1_im[21]}}, Delay4_out1_im};
  assign Add11_sub_cast_3 = {{10{Delay8_out1_im[21]}}, Delay8_out1_im};
  assign Add11_sub_temp_1 = Add11_sub_cast_2 - Add11_sub_cast_3;
  assign Add11_out1_im = Add11_sub_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay28_process
      if (reset == 1'b1) begin
        for(Delay28_t_1 = 32'sd0; Delay28_t_1 <= 32'sd1; Delay28_t_1 = Delay28_t_1 + 32'sd1) begin
          Delay28_reg_re[Delay28_t_1] <= 22'sb0000000000000000000000;
          Delay28_reg_im[Delay28_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay28_t_0_0 = 32'sd0; Delay28_t_0_0 <= 32'sd1; Delay28_t_0_0 = Delay28_t_0_0 + 32'sd1) begin
            Delay28_reg_re[Delay28_t_0_0] <= Delay28_reg_next_re[Delay28_t_0_0];
            Delay28_reg_im[Delay28_t_0_0] <= Delay28_reg_next_im[Delay28_t_0_0];
          end
        end
      end
    end

  assign Delay28_out1_re = Delay28_reg_re[1];
  assign Delay28_out1_im = Delay28_reg_im[1];
  assign Delay28_reg_next_re[0] = Add11_out1_re;
  assign Delay28_reg_next_im[0] = Add11_out1_im;
  assign Delay28_reg_next_re[1] = Delay28_reg_re[0];
  assign Delay28_reg_next_im[1] = Delay28_reg_im[0];



  multByMinusJ2_block6 u_multByMinusJ2 (.In1_re(Delay28_out1_re),  // sfix22_En15
                                        .In1_im(Delay28_out1_im),  // sfix22_En15
                                        .Out1_re(multByMinusJ2_out1_re),  // sfix22_En15
                                        .Out1_im(multByMinusJ2_out1_im)  // sfix22_En15
                                        );

  always @(posedge clk or posedge reset)
    begin : Delay11_process
      if (reset == 1'b1) begin
        for(Delay11_t_1 = 32'sd0; Delay11_t_1 <= 32'sd2; Delay11_t_1 = Delay11_t_1 + 32'sd1) begin
          Delay11_reg_re[Delay11_t_1] <= 22'sb0000000000000000000000;
          Delay11_reg_im[Delay11_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay11_t_0_1 = 32'sd0; Delay11_t_0_1 <= 32'sd2; Delay11_t_0_1 = Delay11_t_0_1 + 32'sd1) begin
            Delay11_reg_re[Delay11_t_0_1] <= Delay11_reg_next_re[Delay11_t_0_1];
            Delay11_reg_im[Delay11_t_0_1] <= Delay11_reg_next_im[Delay11_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay11_out1_re = Delay11_reg_re[2];
    Delay11_out1_im = Delay11_reg_im[2];
    Delay11_reg_next_re[0] = multByMinusJ2_out1_re;
    Delay11_reg_next_im[0] = multByMinusJ2_out1_im;

    for(Delay11_t_0_0 = 32'sd0; Delay11_t_0_0 <= 32'sd1; Delay11_t_0_0 = Delay11_t_0_0 + 32'sd1) begin
      Delay11_reg_next_re[Delay11_t_0_0 + 32'sd1] = Delay11_reg_re[Delay11_t_0_0];
      Delay11_reg_next_im[Delay11_t_0_0 + 32'sd1] = Delay11_reg_im[Delay11_t_0_0];
    end

  end



  assign Add12_add_cast = {{10{Delay3_out1_re[21]}}, Delay3_out1_re};
  assign Add12_add_cast_1 = {{10{Delay11_out1_re[21]}}, Delay11_out1_re};
  assign Add12_add_temp = Add12_add_cast + Add12_add_cast_1;
  assign Add12_out1_re = Add12_add_temp[21:0];
  assign Add12_add_cast_2 = {{10{Delay3_out1_im[21]}}, Delay3_out1_im};
  assign Add12_add_cast_3 = {{10{Delay11_out1_im[21]}}, Delay11_out1_im};
  assign Add12_add_temp_1 = Add12_add_cast_2 + Add12_add_cast_3;
  assign Add12_out1_im = Add12_add_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay18_process
      if (reset == 1'b1) begin
        for(Delay18_t_1 = 32'sd0; Delay18_t_1 <= 32'sd2; Delay18_t_1 = Delay18_t_1 + 32'sd1) begin
          Delay18_reg_re[Delay18_t_1] <= 22'sb0000000000000000000000;
          Delay18_reg_im[Delay18_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay18_t_0_1 = 32'sd0; Delay18_t_0_1 <= 32'sd2; Delay18_t_0_1 = Delay18_t_0_1 + 32'sd1) begin
            Delay18_reg_re[Delay18_t_0_1] <= Delay18_reg_next_re[Delay18_t_0_1];
            Delay18_reg_im[Delay18_t_0_1] <= Delay18_reg_next_im[Delay18_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay18_out1_re = Delay18_reg_re[2];
    Delay18_out1_im = Delay18_reg_im[2];
    Delay18_reg_next_re[0] = Add12_out1_re;
    Delay18_reg_next_im[0] = Add12_out1_im;

    for(Delay18_t_0_0 = 32'sd0; Delay18_t_0_0 <= 32'sd1; Delay18_t_0_0 = Delay18_t_0_0 + 32'sd1) begin
      Delay18_reg_next_re[Delay18_t_0_0 + 32'sd1] = Delay18_reg_re[Delay18_t_0_0];
      Delay18_reg_next_im[Delay18_t_0_0 + 32'sd1] = Delay18_reg_im[Delay18_t_0_0];
    end

  end



  assign x2_re = Delay18_out1_re;

  assign x2_im = Delay18_out1_im;

  assign Add15_sub_cast = {{10{Delay1_out1_re[21]}}, Delay1_out1_re};
  assign Add15_sub_cast_1 = {{10{Delay7_out1_re[21]}}, Delay7_out1_re};
  assign Add15_sub_temp = Add15_sub_cast - Add15_sub_cast_1;
  assign Add15_out1_re = Add15_sub_temp[21:0];
  assign Add15_sub_cast_2 = {{10{Delay1_out1_im[21]}}, Delay1_out1_im};
  assign Add15_sub_cast_3 = {{10{Delay7_out1_im[21]}}, Delay7_out1_im};
  assign Add15_sub_temp_1 = Add15_sub_cast_2 - Add15_sub_cast_3;
  assign Add15_out1_im = Add15_sub_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay26_process
      if (reset == 1'b1) begin
        for(Delay26_t_1 = 32'sd0; Delay26_t_1 <= 32'sd1; Delay26_t_1 = Delay26_t_1 + 32'sd1) begin
          Delay26_reg_re[Delay26_t_1] <= 22'sb0000000000000000000000;
          Delay26_reg_im[Delay26_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay26_t_0_0 = 32'sd0; Delay26_t_0_0 <= 32'sd1; Delay26_t_0_0 = Delay26_t_0_0 + 32'sd1) begin
            Delay26_reg_re[Delay26_t_0_0] <= Delay26_reg_next_re[Delay26_t_0_0];
            Delay26_reg_im[Delay26_t_0_0] <= Delay26_reg_next_im[Delay26_t_0_0];
          end
        end
      end
    end

  assign Delay26_out1_re = Delay26_reg_re[1];
  assign Delay26_out1_im = Delay26_reg_im[1];
  assign Delay26_reg_next_re[0] = Add15_out1_re;
  assign Delay26_reg_next_im[0] = Add15_out1_im;
  assign Delay26_reg_next_re[1] = Delay26_reg_re[0];
  assign Delay26_reg_next_im[1] = Delay26_reg_im[0];



  always @(posedge clk or posedge reset)
    begin : Delay15_process
      if (reset == 1'b1) begin
        for(Delay15_t_1 = 32'sd0; Delay15_t_1 <= 32'sd2; Delay15_t_1 = Delay15_t_1 + 32'sd1) begin
          Delay15_reg_re[Delay15_t_1] <= 22'sb0000000000000000000000;
          Delay15_reg_im[Delay15_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay15_t_0_1 = 32'sd0; Delay15_t_0_1 <= 32'sd2; Delay15_t_0_1 = Delay15_t_0_1 + 32'sd1) begin
            Delay15_reg_re[Delay15_t_0_1] <= Delay15_reg_next_re[Delay15_t_0_1];
            Delay15_reg_im[Delay15_t_0_1] <= Delay15_reg_next_im[Delay15_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay15_out1_re = Delay15_reg_re[2];
    Delay15_out1_im = Delay15_reg_im[2];
    Delay15_reg_next_re[0] = Delay26_out1_re;
    Delay15_reg_next_im[0] = Delay26_out1_im;

    for(Delay15_t_0_0 = 32'sd0; Delay15_t_0_0 <= 32'sd1; Delay15_t_0_0 = Delay15_t_0_0 + 32'sd1) begin
      Delay15_reg_next_re[Delay15_t_0_0 + 32'sd1] = Delay15_reg_re[Delay15_t_0_0];
      Delay15_reg_next_im[Delay15_t_0_0 + 32'sd1] = Delay15_reg_im[Delay15_t_0_0];
    end

  end



  assign Add17_sub_cast = {{10{Delay5_out1_re[21]}}, Delay5_out1_re};
  assign Add17_sub_cast_1 = {{10{Delay9_out1_re[21]}}, Delay9_out1_re};
  assign Add17_sub_temp = Add17_sub_cast - Add17_sub_cast_1;
  assign Add17_out1_re = Add17_sub_temp[21:0];
  assign Add17_sub_cast_2 = {{10{Delay5_out1_im[21]}}, Delay5_out1_im};
  assign Add17_sub_cast_3 = {{10{Delay9_out1_im[21]}}, Delay9_out1_im};
  assign Add17_sub_temp_1 = Add17_sub_cast_2 - Add17_sub_cast_3;
  assign Add17_out1_im = Add17_sub_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay24_process
      if (reset == 1'b1) begin
        for(Delay24_t_1 = 32'sd0; Delay24_t_1 <= 32'sd1; Delay24_t_1 = Delay24_t_1 + 32'sd1) begin
          Delay24_reg_re[Delay24_t_1] <= 22'sb0000000000000000000000;
          Delay24_reg_im[Delay24_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay24_t_0_0 = 32'sd0; Delay24_t_0_0 <= 32'sd1; Delay24_t_0_0 = Delay24_t_0_0 + 32'sd1) begin
            Delay24_reg_re[Delay24_t_0_0] <= Delay24_reg_next_re[Delay24_t_0_0];
            Delay24_reg_im[Delay24_t_0_0] <= Delay24_reg_next_im[Delay24_t_0_0];
          end
        end
      end
    end

  assign Delay24_out1_re = Delay24_reg_re[1];
  assign Delay24_out1_im = Delay24_reg_im[1];
  assign Delay24_reg_next_re[0] = Add17_out1_re;
  assign Delay24_reg_next_im[0] = Add17_out1_im;
  assign Delay24_reg_next_re[1] = Delay24_reg_re[0];
  assign Delay24_reg_next_im[1] = Delay24_reg_im[0];



  alpha4_1_block10 u_multByExp_j_Pi_4_1 (.clk(clk),
                                         .reset(reset),
                                         .enb_1_64_0(enb_1_64_0),
                                         .x4_re(Delay24_out1_re),  // sfix22_En15
                                         .x4_im(Delay24_out1_im),  // sfix22_En15
                                         .Out1_re(multByExp_j_Pi_4_1_out1_re),  // sfix22_En15
                                         .Out1_im(multByExp_j_Pi_4_1_out1_im)  // sfix22_En15
                                         );

  multByMinusJ3_block10 u_multByMinusJ3 (.In1_re(multByExp_j_Pi_4_1_out1_re),  // sfix22_En15
                                         .In1_im(multByExp_j_Pi_4_1_out1_im),  // sfix22_En15
                                         .Out1_re(multByMinusJ3_out1_re),  // sfix22_En15
                                         .Out1_im(multByMinusJ3_out1_im)  // sfix22_En15
                                         );

  always @(posedge clk or posedge reset)
    begin : Delay17_process
      if (reset == 1'b1) begin
        Delay17_out1_re <= 22'sb0000000000000000000000;
        Delay17_out1_im <= 22'sb0000000000000000000000;
      end
      else begin
        if (enb_1_64_0) begin
          Delay17_out1_re <= multByMinusJ3_out1_re;
          Delay17_out1_im <= multByMinusJ3_out1_im;
        end
      end
    end



  assign Add20_add_cast = {{10{Delay15_out1_re[21]}}, Delay15_out1_re};
  assign Add20_add_cast_1 = {{10{Delay17_out1_re[21]}}, Delay17_out1_re};
  assign Add20_add_temp = Add20_add_cast + Add20_add_cast_1;
  assign Add20_out1_re = Add20_add_temp[21:0];
  assign Add20_add_cast_2 = {{10{Delay15_out1_im[21]}}, Delay15_out1_im};
  assign Add20_add_cast_3 = {{10{Delay17_out1_im[21]}}, Delay17_out1_im};
  assign Add20_add_temp_1 = Add20_add_cast_2 + Add20_add_cast_3;
  assign Add20_out1_im = Add20_add_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay22_process
      if (reset == 1'b1) begin
        for(Delay22_t_1 = 32'sd0; Delay22_t_1 <= 32'sd2; Delay22_t_1 = Delay22_t_1 + 32'sd1) begin
          Delay22_reg_re[Delay22_t_1] <= 22'sb0000000000000000000000;
          Delay22_reg_im[Delay22_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay22_t_0_1 = 32'sd0; Delay22_t_0_1 <= 32'sd2; Delay22_t_0_1 = Delay22_t_0_1 + 32'sd1) begin
            Delay22_reg_re[Delay22_t_0_1] <= Delay22_reg_next_re[Delay22_t_0_1];
            Delay22_reg_im[Delay22_t_0_1] <= Delay22_reg_next_im[Delay22_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay22_out1_re = Delay22_reg_re[2];
    Delay22_out1_im = Delay22_reg_im[2];
    Delay22_reg_next_re[0] = Add20_out1_re;
    Delay22_reg_next_im[0] = Add20_out1_im;

    for(Delay22_t_0_0 = 32'sd0; Delay22_t_0_0 <= 32'sd1; Delay22_t_0_0 = Delay22_t_0_0 + 32'sd1) begin
      Delay22_reg_next_re[Delay22_t_0_0 + 32'sd1] = Delay22_reg_re[Delay22_t_0_0];
      Delay22_reg_next_im[Delay22_t_0_0 + 32'sd1] = Delay22_reg_im[Delay22_t_0_0];
    end

  end



  assign x3_re = Delay22_out1_re;

  assign x3_im = Delay22_out1_im;

  assign Add23_sub_cast = {{10{Delay2_out1_re[21]}}, Delay2_out1_re};
  assign Add23_sub_cast_1 = {{10{Delay10_out1_re[21]}}, Delay10_out1_re};
  assign Add23_sub_temp = Add23_sub_cast - Add23_sub_cast_1;
  assign Add23_out1_re = Add23_sub_temp[21:0];
  assign Add23_sub_cast_2 = {{10{Delay2_out1_im[21]}}, Delay2_out1_im};
  assign Add23_sub_cast_3 = {{10{Delay10_out1_im[21]}}, Delay10_out1_im};
  assign Add23_sub_temp_1 = Add23_sub_cast_2 - Add23_sub_cast_3;
  assign Add23_out1_im = Add23_sub_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay13_process
      if (reset == 1'b1) begin
        for(Delay13_t_1 = 32'sd0; Delay13_t_1 <= 32'sd2; Delay13_t_1 = Delay13_t_1 + 32'sd1) begin
          Delay13_reg_re[Delay13_t_1] <= 22'sb0000000000000000000000;
          Delay13_reg_im[Delay13_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay13_t_0_1 = 32'sd0; Delay13_t_0_1 <= 32'sd2; Delay13_t_0_1 = Delay13_t_0_1 + 32'sd1) begin
            Delay13_reg_re[Delay13_t_0_1] <= Delay13_reg_next_re[Delay13_t_0_1];
            Delay13_reg_im[Delay13_t_0_1] <= Delay13_reg_next_im[Delay13_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay13_out1_re = Delay13_reg_re[2];
    Delay13_out1_im = Delay13_reg_im[2];
    Delay13_reg_next_re[0] = Add23_out1_re;
    Delay13_reg_next_im[0] = Add23_out1_im;

    for(Delay13_t_0_0 = 32'sd0; Delay13_t_0_0 <= 32'sd1; Delay13_t_0_0 = Delay13_t_0_0 + 32'sd1) begin
      Delay13_reg_next_re[Delay13_t_0_0 + 32'sd1] = Delay13_reg_re[Delay13_t_0_0];
      Delay13_reg_next_im[Delay13_t_0_0 + 32'sd1] = Delay13_reg_im[Delay13_t_0_0];
    end

  end



  assign x4_re = Delay13_out1_re;

  assign x4_im = Delay13_out1_im;

  assign Add19_sub_cast = {{10{Delay14_out1_re[21]}}, Delay14_out1_re};
  assign Add19_sub_cast_1 = {{10{Delay16_out1_re[21]}}, Delay16_out1_re};
  assign Add19_sub_temp = Add19_sub_cast - Add19_sub_cast_1;
  assign Add19_out1_re = Add19_sub_temp[21:0];
  assign Add19_sub_cast_2 = {{10{Delay14_out1_im[21]}}, Delay14_out1_im};
  assign Add19_sub_cast_3 = {{10{Delay16_out1_im[21]}}, Delay16_out1_im};
  assign Add19_sub_temp_1 = Add19_sub_cast_2 - Add19_sub_cast_3;
  assign Add19_out1_im = Add19_sub_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay21_process
      if (reset == 1'b1) begin
        for(Delay21_t_1 = 32'sd0; Delay21_t_1 <= 32'sd2; Delay21_t_1 = Delay21_t_1 + 32'sd1) begin
          Delay21_reg_re[Delay21_t_1] <= 22'sb0000000000000000000000;
          Delay21_reg_im[Delay21_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay21_t_0_1 = 32'sd0; Delay21_t_0_1 <= 32'sd2; Delay21_t_0_1 = Delay21_t_0_1 + 32'sd1) begin
            Delay21_reg_re[Delay21_t_0_1] <= Delay21_reg_next_re[Delay21_t_0_1];
            Delay21_reg_im[Delay21_t_0_1] <= Delay21_reg_next_im[Delay21_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay21_out1_re = Delay21_reg_re[2];
    Delay21_out1_im = Delay21_reg_im[2];
    Delay21_reg_next_re[0] = Add19_out1_re;
    Delay21_reg_next_im[0] = Add19_out1_im;

    for(Delay21_t_0_0 = 32'sd0; Delay21_t_0_0 <= 32'sd1; Delay21_t_0_0 = Delay21_t_0_0 + 32'sd1) begin
      Delay21_reg_next_re[Delay21_t_0_0 + 32'sd1] = Delay21_reg_re[Delay21_t_0_0];
      Delay21_reg_next_im[Delay21_t_0_0 + 32'sd1] = Delay21_reg_im[Delay21_t_0_0];
    end

  end



  assign x5_re = Delay21_out1_re;

  assign x5_im = Delay21_out1_im;

  assign Add13_sub_cast = {{10{Delay3_out1_re[21]}}, Delay3_out1_re};
  assign Add13_sub_cast_1 = {{10{Delay11_out1_re[21]}}, Delay11_out1_re};
  assign Add13_sub_temp = Add13_sub_cast - Add13_sub_cast_1;
  assign Add13_out1_re = Add13_sub_temp[21:0];
  assign Add13_sub_cast_2 = {{10{Delay3_out1_im[21]}}, Delay3_out1_im};
  assign Add13_sub_cast_3 = {{10{Delay11_out1_im[21]}}, Delay11_out1_im};
  assign Add13_sub_temp_1 = Add13_sub_cast_2 - Add13_sub_cast_3;
  assign Add13_out1_im = Add13_sub_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay19_process
      if (reset == 1'b1) begin
        for(Delay19_t_1 = 32'sd0; Delay19_t_1 <= 32'sd2; Delay19_t_1 = Delay19_t_1 + 32'sd1) begin
          Delay19_reg_re[Delay19_t_1] <= 22'sb0000000000000000000000;
          Delay19_reg_im[Delay19_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay19_t_0_1 = 32'sd0; Delay19_t_0_1 <= 32'sd2; Delay19_t_0_1 = Delay19_t_0_1 + 32'sd1) begin
            Delay19_reg_re[Delay19_t_0_1] <= Delay19_reg_next_re[Delay19_t_0_1];
            Delay19_reg_im[Delay19_t_0_1] <= Delay19_reg_next_im[Delay19_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay19_out1_re = Delay19_reg_re[2];
    Delay19_out1_im = Delay19_reg_im[2];
    Delay19_reg_next_re[0] = Add13_out1_re;
    Delay19_reg_next_im[0] = Add13_out1_im;

    for(Delay19_t_0_0 = 32'sd0; Delay19_t_0_0 <= 32'sd1; Delay19_t_0_0 = Delay19_t_0_0 + 32'sd1) begin
      Delay19_reg_next_re[Delay19_t_0_0 + 32'sd1] = Delay19_reg_re[Delay19_t_0_0];
      Delay19_reg_next_im[Delay19_t_0_0 + 32'sd1] = Delay19_reg_im[Delay19_t_0_0];
    end

  end



  assign x6_re = Delay19_out1_re;

  assign x6_im = Delay19_out1_im;

  assign Add21_sub_cast = {{10{Delay15_out1_re[21]}}, Delay15_out1_re};
  assign Add21_sub_cast_1 = {{10{Delay17_out1_re[21]}}, Delay17_out1_re};
  assign Add21_sub_temp = Add21_sub_cast - Add21_sub_cast_1;
  assign Add21_out1_re = Add21_sub_temp[21:0];
  assign Add21_sub_cast_2 = {{10{Delay15_out1_im[21]}}, Delay15_out1_im};
  assign Add21_sub_cast_3 = {{10{Delay17_out1_im[21]}}, Delay17_out1_im};
  assign Add21_sub_temp_1 = Add21_sub_cast_2 - Add21_sub_cast_3;
  assign Add21_out1_im = Add21_sub_temp_1[21:0];



  always @(posedge clk or posedge reset)
    begin : Delay23_process
      if (reset == 1'b1) begin
        for(Delay23_t_1 = 32'sd0; Delay23_t_1 <= 32'sd2; Delay23_t_1 = Delay23_t_1 + 32'sd1) begin
          Delay23_reg_re[Delay23_t_1] <= 22'sb0000000000000000000000;
          Delay23_reg_im[Delay23_t_1] <= 22'sb0000000000000000000000;
        end
      end
      else begin
        if (enb_1_64_0) begin
          for(Delay23_t_0_1 = 32'sd0; Delay23_t_0_1 <= 32'sd2; Delay23_t_0_1 = Delay23_t_0_1 + 32'sd1) begin
            Delay23_reg_re[Delay23_t_0_1] <= Delay23_reg_next_re[Delay23_t_0_1];
            Delay23_reg_im[Delay23_t_0_1] <= Delay23_reg_next_im[Delay23_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay23_out1_re = Delay23_reg_re[2];
    Delay23_out1_im = Delay23_reg_im[2];
    Delay23_reg_next_re[0] = Add21_out1_re;
    Delay23_reg_next_im[0] = Add21_out1_im;

    for(Delay23_t_0_0 = 32'sd0; Delay23_t_0_0 <= 32'sd1; Delay23_t_0_0 = Delay23_t_0_0 + 32'sd1) begin
      Delay23_reg_next_re[Delay23_t_0_0 + 32'sd1] = Delay23_reg_re[Delay23_t_0_0];
      Delay23_reg_next_im[Delay23_t_0_0 + 32'sd1] = Delay23_reg_im[Delay23_t_0_0];
    end

  end



  assign x7_re = Delay23_out1_re;

  assign x7_im = Delay23_out1_im;

endmodule  // FFT8_1_block2

