// -------------------------------------------------------------
// 
// File Name: /home/mori/Downloads/tomori_fft/hdlsrc/fft_overlap_tomori/multByMinusJ_block11.v
// Created: 2025-04-26 11:44:22
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: multByMinusJ_block11
// Source Path: fft_overlap_tomori/FFT64_outMuxed/64pointFFTchan/FFT64/FFT32_1/FFT16_1/multByMinusJ
// Hierarchy Level: 5
// Model version: 3.27
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module multByMinusJ_block11
          (x4_re,
           x4_im,
           Out1_re,
           Out1_im);


  input   signed [21:0] x4_re;  // sfix22_En15
  input   signed [21:0] x4_im;  // sfix22_En15
  output  signed [21:0] Out1_re;  // sfix22_En15
  output  signed [21:0] Out1_im;  // sfix22_En15


  wire signed [22:0] Unary_Minus1_cast;  // sfix23_En15
  wire signed [22:0] Unary_Minus1_cast_1;  // sfix23_En15
  wire signed [21:0] Unary_Minus1_out1;  // sfix22_En15


  assign Out1_re = x4_im;

  assign Unary_Minus1_cast = {x4_re[21], x4_re};
  assign Unary_Minus1_cast_1 =  - (Unary_Minus1_cast);
  assign Unary_Minus1_out1 = Unary_Minus1_cast_1[21:0];



  assign Out1_im = Unary_Minus1_out1;

endmodule  // multByMinusJ_block11

