// -------------------------------------------------------------
// 
// File Name: /home/mori/Downloads/tomori_fft/hdlsrc/fft_overlap_tomori/multByMinusJ1_block2.v
// Created: 2025-04-26 11:44:22
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: multByMinusJ1_block2
// Source Path: fft_overlap_tomori/FFT64_outMuxed/64pointFFTchan/FFT64/FFT32/FFT16_1/FFT8_1/multByMinusJ1
// Hierarchy Level: 6
// Model version: 3.27
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module multByMinusJ1_block2
          (In1_re,
           In1_im,
           Out1_re,
           Out1_im);


  input   signed [21:0] In1_re;  // sfix22_En15
  input   signed [21:0] In1_im;  // sfix22_En15
  output  signed [21:0] Out1_re;  // sfix22_En15
  output  signed [21:0] Out1_im;  // sfix22_En15


  wire signed [22:0] Unary_Minus1_cast;  // sfix23_En15
  wire signed [22:0] Unary_Minus1_cast_1;  // sfix23_En15
  wire signed [21:0] Unary_Minus1_out1;  // sfix22_En15


  assign Out1_re = In1_im;

  assign Unary_Minus1_cast = {In1_re[21], In1_re};
  assign Unary_Minus1_cast_1 =  - (Unary_Minus1_cast);
  assign Unary_Minus1_out1 = Unary_Minus1_cast_1[21:0];



  assign Out1_im = Unary_Minus1_out1;

endmodule  // multByMinusJ1_block2

